internal/stores/objects.go, slab/slab.go
Changed the type of `EphemeralObjectStore.slabs` to `map[string]refSlab`. The JSON object store was not persisted because `slab.EncryptionKey` did not implement encoding.TextMarshaller. There was an additional reference issue between the slabs map and `refObject.SlabID` after reloading the store if left as a `slab.EncryptionKey`.
=> Fix JSON object store

cmd/renterd/slab.go
If you try and perform many downloads in parallel, all requests are stalled until the slowest download is finished.
```
============================
benchmark
============================
- thread count 16...
Percentile stats (15 timings):
50p: 8075ms
80p: 8075ms
90p: 8075ms
99p: 8075ms
99.9p: 8075ms
```
In `DownloadSector` in `session.go` we acquire the session and defer a release after `readSector` is finished. This is a problem because `withHosts` defers a call to `UnlockContract` that tries to acquire the mutex that's being released after `readSector`. The PR unlocks the contract in a goroutine ensuring the request itself is unblocked and contract is unlocked.
```
============================
benchmark
============================
- thread count 16...
Percentile stats (15 timings): …
```
=> Fix: unlock contract in goroutine

api/server.go
I ran into the following error a couple of times 
_http: superfluous response.WriteHeader call from go.sia.tech/jape.Context.Error (server.go:34)_
There was a couple of is-nil checks that were supposed to be is-not-nil checks.
=> Fix superfluous response.WriteHeader call

api/api.go, api/api_test.go, api/client.go, api/server.go, cmd/renterd/slab.go, cmd/renterd/web.go, go.mod, go.sum, internal/slabutil/mock.go, object/object_test.go, rhp/v2/session.go, slab/reedsolomon.go, slab/transfer.go, slab/transfer_test.go
If these endpoints accept multiple slabs, then they can fail halfway through, which means we need a way to report errors out-of-band. For example, if `/slabs/download` downloads one slice and streams it, but the second slice fails, what do we do? You can't report an error the typical way (by setting a 5xx response code and writing the error to the body) because we've already set a 200 code and written some data. To work around this, I considered adding a `Link` header to the responses, which would give the client a separate route to poll while the download was occurring. This brings a fair amount of complexity with it, though (e.g. how long should the reserve retain the "download job" metadata?), and it moves scheduling decisions into `renterd` (e.g. if you have a 5-slab download and a …
=> Single-slab endpoints

autopilot/autopilot.go, autopilot/hosts.go, worker/api.go, worker/client.go, worker/worker.go
Add a new field, `ping`, to the response type returned by `/rhp/scan`.  
It represents the time it takes to fetch the host's settings, returned in milliseconds.  
This field can be used to perform a very rudimentary host ranking based on its latency.
=> Add ping to `/rhp/scan`

bus/bus.go, cmd/renterd/node.go, internal/stores/hostdb.go, internal/stores/objects.go, internal/stores/objects_test.go, object/object.go, slab/slab.go, worker/worker.go
Similar to the HostDB this PR replaces the JSON-based store for storing objects with an SQL based one.
For now the interface remains exactly the same and the behaviour as well.
=> Replace JSONObjectStore with SQLObjectStore

autopilot/api.go, autopilot/autopilot.go, autopilot/contracts.go, bus/api.go, bus/client.go, internal/stores/autopilot.go
This PR adds an initial version of the contract loop. I have extended the `Bus` interface with some methods that I found are going to be required in some shape or form, these are however not finalised yet and I want to revisit them in consecutive PRs.
It essentially defines a loop that performs the following steps:
- run contract checks
- perform renewals
- form new contracts
The contract checks are a series of checks that update a contract's metadata to signal whether the contract is good for upload and/or renew. Both the renewal code as well as the contract formation code has some TODOs in there still but all-in-all should be close to how it will end up being implemented.
I have added a `State` variable to the autopilot, that contains things like the current block height and period. I …
=> Contract Loop - Initial Structure

bus/bus.go, cmd/renterd/main.go, cmd/renterd/node.go, internal/stores/contracts.go, internal/stores/contracts_test.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go, internal/stores/objects.go, internal/stores/objects_test.go
Same refactor as before. Migrating the contract store to a SQL based backend.
NOTE: Still a WIP so no need to review yet. The diff will clear up once https://github.com/SiaFoundation/renterd/pull/22 is merged
=> Replace JSONContractStore with SQLContractStore

cmd/renterd/node.go, internal/stores/contracts.go, internal/stores/contracts_test.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go, internal/stores/hostsets.go, internal/stores/hostsets_test.go, internal/stores/objects.go, internal/stores/objects_test.go, internal/stores/sql.go, internal/stores/sql_test.go
This PR does a few smaller refactors.
1. add soft-deletion and update/creation/deletion times to the db by adding the corresponding columns to the database tables.
2. Refactor the database types into a single one that simply implements the corresponding interfaces.
3. Moves the methods for the hostsets into a separate file. That way every interface gets its own file.
=> Store refactor

cmd/renterd/main.go
getWalletKey() is called twice when both bus and worker API are enabled, so if the RENTERD_WALLET_SEED variable is not set, a user is also prompted twice for the password input.
=> Fix a bug where wallet password would be read twice from terminal

autopilot/api.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/contracts.go, autopilot/hosts.go, autopilot/scanner.go, autopilot/server.go, bus/api.go, bus/bus.go, bus/client.go, cmd/renterd/main.go, cmd/renterd/node.go, internal/stores/autopilot.go, slab/metrics.go
This PR adds `contractor` and `scanner` structs. It's an attempt to add some structure in the `autopilot` and house certain responsibilities under separate entities that can each manage their own respective state.
Originally I went for a design where every "subsystem" had its own lifecycle and managed its own loops, but Luke pointed out that it would be better to have a single lifecycle in the autopilot in combination with inert subsystems that are being controlled by the autopilot, which I like because it makes for cleaner stack traces.
In the current proposal the `autopilot` uses a `ticker` which can be useful in testing. What I don't really like is that the `contractor` and `scanner` also need a way to break out of semi-long running loops (like renewals), for this they would need to …
=> Add Contractor and Scanner

bus/client.go, worker/server.go, worker/worker.go
This turned out to be surprisingly annoying. I wish `http.ServeContent` could be used with things other than an `io.ReadSeeker` :/
=> worker: Add Range request support

autopilot/api.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostscore.go, autopilot/hostscore_test.go, bus/client.go
This PR adds a new file that holds all scoring functions we apply to a host.
Left two TODOs:
- `priceAdjustmentScore`
- `storageRemainingScore` 
Those use a bunch of arbitrary values we might want to revisit or get rid of all together.
I'll add those in a separate PR to keep the PR small.
=> Host Score

autopilot/autopilot.go, autopilot/contractor.go, bus/api.go, bus/bus.go, bus/client.go, internal/stores/contracts.go, internal/stores/contracts_test.go, internal/stores/sql.go
After a renew is done we should atomically update the state within the store. That is moving the old contract to the archive and the new one to the set of active contracts.
=> Add `AddRenewedContract` for atomically performing renews within the contract store

autopilot/scanner_test.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go
There's a bug in `AllHosts` where it does not return hosts without interactions. This is because of the `notSince` parameter that needs to `JOIN` on interactions to figure out `MAX(timestamp)` to be able to compare it to `notSince`. I updated the query a bit and added a test.
The end result is actually quite a funny catch-22, the autopilot's scanner fetches all hosts in order to scan them and add interactions, but in fact is getting an empty list every time because hosts don't have interactions attached.
edit: highjacking this PR to take a small NDF fix along wrt scanner_test
=> Hosts query fix

rhp/v2/rhp.go
Need `ChainIndex` to build `ConsensusState` for `RPCFormContract` and `RenewContract` outside of `renterd`. Would it be better to move `consensus` out of `internal` instead of having exports everywhere?
=> Export ChainIndex in rhp

autopilot/scanner.go, autopilot/scanner_test.go
Turns out there was a data race in the scanner pool. I ran the integration tests in a loop to try and reproduce it and caught it. The handling of the channels and threads in `performHostScan` was a bit sloppy and was mainly due to the `scanPool` object. Instead of adding more locking I decided to just inline the scan pool which makes everything a lot simpler.
race: https://github.com/SiaFoundation/renterd/actions/runs/3687188966/jobs/6240446150
fix: https://github.com/SiaFoundation/renterd/actions/runs/3687664093/jobs/6241531530
=> Fix Scanpool Race 

autopilot/contractor.go, autopilot/contracts.go, autopilot/hostfilter.go, bus/client.go
When contracts run out of funds they were currently being renewed instead of refreshed. The key difference between a renew and refresh is that a refreshed contract uses the same `endheight` as the contract it's refreshing, while a renewed contract extends into the next period.
=> Contract Refresh

autopilot/autopilot.go, bus/bus.go, bus/client.go, internal/stores/contracts.go, internal/stores/contractsets.go, internal/stores/contractsets_test.go, internal/stores/sql.go, worker/worker.go
Establishing a relation between contracts and contract sets allows for fetching contracts for a set more efficiently.
=> Establish many2many relation between contracts and contractsets

autopilot/contractor.go, autopilot/host.go, autopilot/host_test.go, autopilot/hostfilter.go, autopilot/hostscore.go, autopilot/hostscore_test.go, autopilot/ipfilter.go, autopilot/scanner.go, hostdb/hostdb.go, internal/stores/contracts.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go, internal/stores/sql.go
At this time syncing renterd from scratch results in a database that contains around 80k hosts and around 350k announcements. Since we never use any of them but the most recent one, they take up quite a lot of space without being of any use to us.
Additionally they slow down all host related queries because when we return a host through the API we include all of its announcements. So when we fetch all hosts, we slow things down quite a bit by querying for all the announcements as well even though we only need the most recent one per host.
To clean this up, this PR inlines only the necessary info into the host table and gets rid of the announcements.
=> Inline dbAnnouncement into dbHost

internal/stores/contracts.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go
Confirmed in production that this gets rid of the `database locked` errors. Apparently it's not a great idea to create transactions which read from one table and write to another with multiple queries on tables that get inserted to a lot such as the interactions ^^
=> Query performance improvements

api/params.go, api/worker.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/migrator.go, autopilot/scanner.go, internal/testing/cluster.go, internal/testing/cluster_test.go, wallet/wallet.go, worker/client.go, worker/session.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
The `worker` currently has an active contracts endpoint that queries the bus for the active contracts and fetches the latest revision from the hosts. This endpoint however will error out as soon as we fail to retrieve a single revision. This is an issue because contract maintenance is blocked by this.
This PR adds a timeout that's applied to every revision fetch from the host. By doing so contract maintenance can continue for hosts that are reachable, the error message is logged by the autopilot so it doesn't go by completely unnoticed.
NOTE: the timeout is only applied to components that use the context, the worker transport for instance is currently not aware  yet of any context and thus won't apply the context to reads for instance. It is applied to the `Dial` which is the most …
=> Active Contracts

api/bus.go, autopilot/autopilot.go, autopilot/contractor.go, bus/bus.go, bus/client.go, bus/contractlocking.go, bus/contractlocking_test.go, internal/stores/contracts.go, internal/stores/contracts_test.go
Until we have EA uploads we need some sort of locking for when we use contracts. This PR adds an in-memory locking structure to the Bus that achieves exactly that.
=> Add in-memory contract locking to bus for multi-worker setups

.github/workflows/test.yml, autopilot/autopilot.go, autopilot/client.go, cmd/renterd/main.go
I have been debugging the autopilot today and feel it is necessary at times to be able to trigger the autopilot loop. There are other debug related tools/requirements like this such as `pprof` for instance. I have added the route as `/debug/trigger`, which is meant to be the first in a (small) series of debug endpoints we add to the autopilot.
The trigger itself is quite straightforward. It will trigger the autopilot loop and reset the ticker to ensure we don't run it again only moments after. I also trigger the loop when we update the autopilot config, which makes sense I think, maybe we should be a little smarter about that but I figured it's probably fine like this for now (?)
=> Autopilot Trigger

api/bus.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/migrator.go, bus/bus.go, bus/client.go, internal/stores/contracts.go, internal/stores/contracts_test.go, internal/stores/hostdb_test.go, internal/stores/objects.go, internal/stores/objects_test.go, internal/stores/sql.go, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/gouging_test.go, internal/testing/migrations_test.go, worker/client.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
This PR adds migrations. 
It changes a couple of things, but nothing major:
- move away from `fromContracts` and `toContracts`
- we can get rid of `MigrationParams`
- we can migrate using the contract set name (seeing as we merged contract set store and contract store)
- we can reuse the upload code for migrations
I added two fields: 
- `LastHost`: something we really need to figure out what slabs to migrate (contact me in PM if you want to hear why)
- `TotalShards`: something we don't really need, but it saves an inner query and I figured it's not too bad..
=> Migrations

internal/stores/hostdb.go, internal/stores/hostdb_test.go
Currently when we batch insert announcements for the same host that happens to be blocked by a rule in the blocklist, the unique constraint on the blocklist entry fails. Fixed by using `INSERT OR IGNORE`. Extended `TestInsertAnnouncements` - so it's a regression test for this particular issue.
=> Blocklist Unique Constraint

internal/stores/objects.go, internal/stores/objects_test.go, worker/transfer.go
Instead of pushing used hosts to the back of the hosts array when we're migrating, we want to filter them out. I extended `TestSlabsForMigration` to ensure it catches slabs where not every sector is on a distinct host.
=> Migration Reused Hosts

autopilot/autopilot.go, autopilot/contractor.go, rhp/v3/transport.go, worker/pricetable.go, worker/worker.go
This PR allows for workers to keep around price tables and reuse them instead of fetching a new one every time a pricetable is needed. 
Every worker manages its own price tables with hosts. The same way it manages its own ephemeral accounts with hosts.
=> Add pricetable support to bus

autopilot/autopilot.go, autopilot/contractor.go
The contractor has some redundant `bus` calls that I wanted to get rid of. This PR changes some method signatures and adds a small helper type that combines host/contract info and passes it around.
- redundant host/settings call in renew/refresh funding estimates
- redundant host/contract call in `runContractChecks`
- redundant host call in `runContractFormations`
=> Contractor Redundant Calls

autopilot/contractor.go, autopilot/ipfilter.go
Implement leftover TODO to apply a timeout to the context we pass into the net resolver when looking up a host's IP
=> IP Filter Timeout

api/autopilot.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/hostscore.go, autopilot/migrator.go, bus/bus.go, bus/client.go, go.mod, go.sum, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/gouging_test.go, internal/testing/migrations_test.go, worker/worker.go
This PR gets rid of the hardcoded `autopilot` contract set, allowing users to configure a custom contract set name in the autopilot config as well as overriding the contract set on the worker endpoints. The autopilot will update a `bus` setting to configure the default contract set when the autopilot starts up and when the config is updated.
=> ContractSet Setting

api/bus.go, api/contract.go, api/worker.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/contractorspending.go, autopilot/errors.go, autopilot/hostfilter.go, autopilot/hostscore.go, bus/bus.go, bus/client.go, go.mod, go.sum, hostdb/hostdb.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go, rhp/v2/contracts.go, worker/client.go, worker/worker.go
This PR refreshes a contract when its remaining collateral drops below a certain threshold. It also changes the initial collateral so it reflects the expected storage instead of basing it solely off of the renter funds. The host collateral now has to be supplied to the worker, which is better because it's consistent with forming a contract and we can check whether the collateral makes sense before trying to renew/refresh.
=> Collateral Refresh

internal/testing/cluster_test.go, internal/testing/migrations_test.go, worker/worker.go
`objectsKeyHandlerGET` and `objectsKeyHandlerPUT` implicitly added another `/` to the beginning of the object's name within the bus.
That's because when `foo` is passed to an endpoint, the path param is actually `/foo`. So when we passed `foo` to the worker it became `/foo` and the worker calls the bus endpoint which makes it `//foo`.
Same goes for fetching objects from the bus. We need to pass `""` to get the root dir `/` because passing `/` returns the dir `//`. 
I extended the test to make sure the entries are stored with a single slash within the bus as expected.
=> bus/worker: remove unnecessary '/' at beginning of object name

bus/bus.go, bus/client_test.go, cmd/renterd/main.go, internal/node/node.go, internal/stores/hostdb_test.go, internal/stores/logger.go, internal/stores/sql.go, internal/stores/sql_test.go, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/gouging_test.go, internal/testing/migrations_test.go, worker/worker.go
This PR passes a custom logger to `Gorm`, a zap logger to ensure the `sql` logs are consistent with the other log output. While I was at it I added a logger to the worker and bus as well. 
It looks pretty good now, the slow sql logs are neatly in line with all other logs:
We now have full control over the logs, I made it so the default config ignores not found errors. I also made sure the loggers we use in unit tests and integration tests still show sql logs, I've even made the slow sql a little more strict there.
=> Custom Gorm Logger + Worker/Bus Loggers

autopilot/migrator.go, internal/stores/hostdb.go, internal/stores/sql.go, object/object.go
There's a `SLOW SQL` mention that's been bothering me for a while, so I decided to investigate it and found out there's a missing index on a join table. There's a combined `PRIMARY` index and two foreign key constraints but there's no index on `db_host_id`, which we use in the blocklist:
``` 
"SELECT `hosts`.`public_key`,`hosts`.`net_address` FROM `hosts` WHERE last_scan < 1675589085000000000 AND NOT EXISTS (SELECT 1 FROM host_blocklist_entry_hosts hbeh WHERE hbeh.db_host_id = hosts.id) ORDER BY last_scan ASC,`hosts`.`id` LIMIT 1000 OFFSET 5000"
```
Query plan before and after the index is added
```
QUERY PLAN
|--SEARCH TABLE hosts USING INDEX idx_hosts_last_scan (last_scan<?)
`--CORRELATED SCALAR SUBQUERY 1
`--SCAN TABLE host_blocklist_entry_hosts AS hbeh
```
```
QUERY PLAN
|--SEARCH …
```
=> Fix Slow SQL 

README.md
I extended the `README.md` with a `usage` section. It is definitely not an extensive document with everything one needs to know to run `renterd`, but it should be a good resource for people that want to play around with the software already. It lists most of the endpoints I use on a daily basis to debug and verify whether everything is running smoothly.
=> Extend Documentation

autopilot/autopilot.go, autopilot/contractor.go, autopilot/migrator.go, autopilot/scanner.go, autopilot/scanner_test.go, bus/bus.go, bus/client_test.go, cmd/renterd/main.go, internal/node/node.go, internal/testing/cluster.go, worker/worker.go
This PR improves server shutdowns. It unifies all "cleanup functions" into a function that takes a context and returns an error. I added `node.shutdownTimeout` to the command line options and default it to 5 minutes. I added a small max heap for all of the shutdown functions to allow us to control the order with which our components shut down.
edit: last commit disables the connection pool, I was running into an NDF in the test suite and since we have been running into the `database is locked` issue even after our `WAL` mode and all other SQL related fixes it is time to try and disable the connection pool to see if it gets rid of the database locks (?)
=> Shutdown Timeout

internal/stores/metadata.go, worker/worker.go
To further reduce the number of `database is locked` errors this PR moves reading the slab out of the transaction in `UpdateSlab`.
That shouldn't harm consistency since the update will fail if the slab is deleted between looking it up and applying the transaction.
=> Move finding slab in UpdateSlab out of transaction

worker/sessionpool.go, worker/worker.go
This PR changes the renew endpoint to also make use of the session pool instead of creating a separate transport and manually creating a locked session by calling `withHost`.
=> Improve locking in rhpRenewHandler

api/autopilot.go, api/bus.go, autopilot/contractor.go, autopilot/host_test.go, autopilot/hostfilter.go, autopilot/hostscore.go, autopilot/hostscore_test.go, internal/testing/cluster.go, worker/gouging.go
This PR adds gouging checks for `MaxCollateral`, adds a score adjustment mechanism for remaining storage on hosts and extends the contract maintenance with a score check against a minimal score threshold.
That way we should be a lot less likely to select hosts with insufficient storage for contract formation and we will be able to avoid hosts which are not willing to put a minimum amount of collateral into contracts.
=> Improve host scoring by including MaxCollateral and RemainingStorage

worker/worker.go
small bug that got through, leading to renew panics when trying to fetch a contract's `HostKey`
```
2023/02/21 13:50:11 http: panic serving 127.0.0.1:62922: runtime error: index out of range [1] with length 0
goroutine 1574 [running]:
net/http.(*conn).serve.func1()
/opt/homebrew/Cellar/go/1.19.5/libexec/src/net/http/server.go:1850 +0xe4
panic({0x103b6f400, 0xc0009a0360})
/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:890 +0x258
go.sia.tech/core/rhp/v2.ContractRevision.HostKey(...)
/Users/peterjan/go/pkg/mod/go.sia.tech/core@v0.1.7/rhp/v2/rhp.go:38
go.sia.tech/renterd/internal/stores.addContract(_, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
/Users/peterjan/code/siafoundation/renterd/internal/stores/metadata.go:795 +0x770
```
=> Fix Renew Panic

internal/stores/metadata.go
I keep getting 700ms query times when saving contracts since the query updates every field on `save`. This changes the query to only update the fields we are interested in.
=> Speed up RecordContractSpending by using Updates instead of save

autopilot/contractor.go
I noticed on a fresh set of contracts that one of the contracts was ignored due to being in a redundant ip range.
Seems like the reason for that was that excluded hosts never have `isUsableHost` called on them. So `isRedundantIP` is also never called and the subnet never gets registered in the filter.
So my node formed a contract and during the next contract maintenance realised that it now has 2 contracts from the same subnet.
=> Add excluded hosts to ipFilter in candidateHosts

worker/rhpv2.go, worker/spending.go, worker/worker.go
+ Removes the panic from a non-existent ContractSpendingRecorder
+ Publishes `Record` in the interface so packages outside renterd can satisfy it.
=> Publish ContractSpendingRecorder.Record

autopilot/contractor.go, bus/bus.go, go.mod, go.sum, internal/testing/cluster_test.go, worker/rhpv2.go, worker/sessionpool.go
Uploads in renterd appear to fail if contracts get renewed mid-upload. The reason is the error `Lock: contract cannot be revised further`.
After investigating a bit it seems like every upload fetches a `sharedSession` and acquires/releases the session multiple times. Between theses calls it's possible for another `sharedSession` to renew the associated contract.
Unfortunately the `contractID` within a `sharedSession` never gets updated so the slow, ongoing upload is stuck with the `contractID` of the renewed contract.
What's even worse is that the `if s.Revision().ID() != ss.contractID` - check in `(*SessionPool).acquire` will try to reconnect on every `acquire` since the contract IDs no longer match.
As a solution, I propose a `renewedFrom` field in the `Session`. That way, a …
=> Fix uploads failing when contracts renew mid-upload

go.mod, go.sum
Fixes
```
2023-02-22T16:29:15.658948337Z http: panic serving 172.21.0.1:59028: unsupported type *string
2023-02-22T16:29:15.659003630Z goroutine 3896 [running]:
2023-02-22T16:29:15.659016683Z net/http.(*conn).serve.func1()
2023-02-22T16:29:15.659025683Z 	/usr/local/go/src/net/http/server.go:1850 +0xbf
2023-02-22T16:29:15.659034418Z panic({0xf427a0, 0xc00192eea0})
2023-02-22T16:29:15.659042643Z 	/usr/local/go/src/runtime/panic.go:890 +0x262
2023-02-22T16:29:15.659051770Z go.sia.tech/jape.Context.DecodeForm({{0x124cd48, 0xc00010ef60}, 0xc00012ac00, {0xc001ec5b80, 0x1, 0x1}}, {0x10bd43e, 0xb}, {0xf24e80, 0xc00192ee90})
2023-02-22T16:29:15.659061880Z 	/go/pkg/mod/go.sia.tech/jape@v0.8.0/server.go:123 +0x4ad
2023-02-22T16:29:15.659071800Z …
```
=> Update jape dependency

api/bus.go, autopilot/autopilot.go, autopilot/migrator.go, bus/bus.go, bus/client.go, cmd/renterd/main.go, internal/node/node.go, internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/cluster.go, worker/rhpv2.go, worker/sessionpool.go, worker/worker.go
I noticed on my node that we sometimes temporarily lose contracts from the contract set for minor reasons. e.g. the contract being up for a refresh and not refreshing since there are no unspent outputs in the wallet.
In that case GiBs of data are downloaded and migrated simply because the contract is unavailable for 10 minutes. To avoid that I'm introducing a health threshold which allows us to only fetch slabs for migration which are below a certain health threshold. e.g. if 25% of the redundancy shards are lost.
=> Introduce healthCutoff to UnhealthySlabs

worker/rhpv2.go
When force-closing a transport on timeouts we set it to `nil` to trigger a reconnect. To avoid a panic when the caller tries to closet the transport gracefully again, this PR wraps closing a transport in a check.
=> Fix nil pointer dereference panic in Session

internal/stores/sql.go
Removing the `UpdatedAt` field for now since we haven't used it and we keep getting logging about deadlocked database transactions launched by Gorm for updating that field.
=> Remove UpdatedAt field from Model type

cmd/renterd/main.go
Added support for graceful shutdown upon receiving a SIGTERM as docker uses a SIGTERM followed by a SIGKILL after a grace period to shut down containers.
https://docs.docker.com/engine/reference/commandline/stop/
=> Handle SIGTERM

api/bus.go, api/worker.go, autopilot/autopilot.go, autopilot/contractor.go, autopilot/hostfilter.go, bus/bus.go, cmd/renterd/main.go, internal/testing/cluster.go, internal/testing/cluster_test.go, worker/client.go, worker/gouging.go, worker/rhpv3.go, worker/sessionpool.go, worker/worker.go
This PR adds gouging checks that use a price table rather than host settings. It does so by extending the gouging checker to check for gouging for both host settings and a host price table. For the time being, nobody is passing a price table but #169 will be updated to do so once this is merged.
=> Pricetable Gouging

autopilot/autopilot.go, autopilot/contractor.go, autopilot/contractorspending.go, autopilot/migrator.go, autopilot/scanner.go, autopilot/scanner_test.go
This PR adds a `loopState` struct that contains some of the stuff we need constantly and are currently passing around all the time. We update it in every iteration of the autopilot loop, ensuring the entire loop uses the same data and we don't needless fetch the same info twice.
=> Autopilot Loop State

internal/stores/metadata.go, internal/stores/sql.go
I ran into the following error on my node:
```bash
2023-03-08T11:03:30+01:00      ERROR    db   gorm@v1.24.3/finisher_api.go:647  database is locked      {"elapsed": "0.090ms", "rows": 0, "sql": "UPDATE `contracts` SET `upload_spending`=\"20573601380386548285440\" WHERE `id` = 994"}
2023-03-08T11:03:30+01:00      ERROR    worker.worker   worker/spending.go:91  failed to record contract spending: failed to record spending metrics for contract: database is locked
```
We missed wrapping a transaction in a retry. I've added a logger to the sql store as well so we can log the retry attempts and make sure it does not go by completely unnoticed.
=> Record ContractSpending inside a transaction

api/bus.go
The default gouging settings are quite tight. This loosens them a little since it's meant as a measure to prevent hosts from gouging their prices. The host scoring should make it so the autopilot forms contracts with cheap hosts rather than super expensive hosts.
=> Update Gouging Settings

bus/bus.go, bus/client.go, internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/cluster_test.go
Adds the `/contracts/sets` endpoint to list all contract sets currently stored in the bus
=> Add endpoint to list all contract sets known to the bus

api/bus.go, bus/bus.go, bus/client.go, internal/stores/metadata.go, internal/stores/metadata_test.go, worker/client.go, worker/worker.go
I was testing the download endpoints and found that the endpoint is broken because it can not handle the default limit (`-1`) and throws `Error 1690 (22003): signed integer value is out of range in 'mysqld_stmt_execute'`.  More importantly, I found that if you try and fetch the entries at some non-existent path `foo/` you get this weird error that says `object has no data`. I figured that was going to be confusing to a lot of people so I changed the behaviour a little.
For the `limit` I figured it's easiest to set it to `math.MaxInt` where necessary. I considered wrapping it in a convenience function but landed with simply immediately checking the parameter in every method that uses a limit 🤷🏻‍♂️ to avoid rewriting the queries and making them harder to read.
For the non-existing object …
=> Fix object entries

autopilot/contractor.go, autopilot/hostfilter.go
Nate reported a silly mistake in the `contractor` logging:
```
DEBUG    autopilot.contractor    autopilot/contractor.go:721    looking for 53 candidate hosts
DEBUG    autopilot.contractor    autopilot/contractor.go:739    found -25 candidate hosts
DEBUG    autopilot.contractor    autopilot/contractor.go:771    scored -25 candidate hosts, took 1.214668ms
DEBUG    autopilot.contractor    autopilot/contractor.go:785    could not fetch 'wanted' candidate hosts, 
```
Refactored `candidateHosts` to avoid safe sub checks and bumped the lack of candidate hosts to a warning. Also added a breakdown of error counts if we are unable to get the amount of candidate hosts we are looking for. Should give insights into why your hosts are no good to allow you to more easily debug what's off.
=> Contractor Logging

autopilot/autopilot.go, autopilot/client.go, autopilot/contractor.go, bus/bus.go, bus/client.go, internal/stores/hostdb.go, internal/stores/hostdb_test.go, internal/stores/metadata.go, internal/testing/cluster_test.go, internal/testing/migrations_test.go, worker/worker.go
Chris ran into "Every derived table must have its own alias". Turns out there was never an integration test to check whether path prefixes behave as they should so I extended the integration tests to cover that case. I also exposed `offset` and `limit` in the worker API while I was at it... I was on the fence there but I figure it makes sense.
=> Fix ObjectEntries Query

internal/testing/cluster_test.go, worker/worker.go
Make sure the worker is able to return an empty entries list if it is required. We used to encode the entries if and only if we had some, but that is wrong since there are numerous ways you can end up with no entries but still want to serve that empty list.
=> Fix worker API

api/worker.go, autopilot/accounts.go, autopilot/autopilot.go, worker/client.go, worker/worker.go
I think we should try and fund after syncing. I can't see of downsides really there's only upsides. One of the reasons driving this change is the logging in the autopilot which says `"Successfully funded account"` after potentially failing to fund but succeeding so sync (which clears the error). With this change, seeing that log line will effectively mean that the account was funded to the expected balance.
edit: updated PR to update the `/fund` endpoint to take the expected balance instead
=> Refill after sync

bus/client.go, worker/worker.go
`ContractsForSlab` doesn't really make sense we keep fetching all contracts in the download set and filtering them down
=> Remove ContractsForSlab

api/worker.go, autopilot/accounts.go, autopilot/autopilot.go, worker/client.go, worker/worker.go
There's a couple of redundant `Host` calls to the `bus` to fetch the host IP and mux address. We have that info in the autopilot already so I added it to the requests.
=> worker: add siamux addr to fund/sync request types

autopilot/contractor.go, autopilot/hostfilter.go
This PR adds some zero checks:
- check for zero allowance/hosts/period in `/hosts/:hostkey` endpoint
- skip maintenance and warn if cfg is not sane
- add score breakdown to the result to avoid scoring twice**
** fetching the breakdown separately leads to errors, we weren't passing storage and redundancy and we also don't calculate the score if the host has no price table for instance, overloading the result is not ideal but I don't think we should care too much about that in this case
=> autopilot: hardening/fixes

api/account.go, api/bus.go, api/worker.go, autopilot/accounts.go, autopilot/autopilot.go, bus/accounts.go, bus/accounts_test.go, bus/bus.go, bus/client.go, cmd/renterd/main.go, internal/stores/accounts.go, internal/testing/cluster.go, internal/testing/cluster_test.go, worker/client.go, worker/rhpv3.go, worker/worker.go
This PR makes renterd use shared accounts which are tracked and locked through the bus. There is a trade-off here considering that we are doing network I/O now to lock accounts. Ideally this is <1ms since the cluster is running on the same local network over a wired connection but if that ever becomes a problem we can explore a more fuzzy, lock-free approach. Since we do have tracing in place we should be able to easily keep an eye on this though.
=> Use shared accounts between workers

api/worker.go, go.mod, worker/client.go, worker/gouging.go, worker/rhpv3.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
Adds support for the LatestRevision RPC which is part of rhpv3. That way we can finally have pure rhpv3 endpoints which don't require both the `hostIP` of v2 and the `siamuxAddr` of v3. 
It also speeds things up a bit since we no longer need to lock a v2 session to get the latest revision. Instead we can just pay via account. This should be especially useful for endpoints fetching revisions frequently or just large numbers of them.
=> Fetch revisions over rhpv3

worker/rhpv3.go, worker/transfer.go, worker/worker.go
So instead of marking hosts as "bad" or "slow" it makes sense to use timings and sort hosts based on their performance so consecutive downloads primarily use fasts hosts. Benchmarks definitely show an improvement but mostly on higher thread counts, which is to be expected.
[benchmark_renterd-benchmark_2023-03-14_14-09-35.txt](https://github.com/SiaFoundation/renterd/files/11029484/benchmark_renterd-benchmark_2023-03-14_14-09-35.txt)
[benchmark_renterd-benchmark_2023-03-14_14-25-53.txt](https://github.com/SiaFoundation/renterd/files/11029485/benchmark_renterd-benchmark_2023-03-14_14-25-53.txt)
=> Favour Fast Hosts

internal/stores/hostdb.go, internal/stores/hostdb_test.go, internal/stores/sql.go
If my node needs to sync up I sometimes run into the following warning:
```go
2023-03-21T10:01:37+01:00       WARN    db      stores/hostdb.go:822    transaction attempt 5/5 failed, err: Error 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`renterd`.`host_allowlist_entry_hosts`, CONSTRAINT `fk_host_allowlist_entry_hosts_db_host` FOREIGN KEY (`db_host_id`) REFERENCES `hosts` (`id`) ON DELETE CASCADE); ...  Error 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`renterd`.`host_allowlist_entry_hosts`, CONSTRAINT `fk_host_allowlist_entry_hosts_db_host` FOREIGN KEY (`db_host_id`) REFERENCES `hosts` (`id`) ON DELETE CASCADE); Error 1452 (23000): Cannot add or update a child row: a foreign key constraint fails …
```
=> Host AfterCreate Hook

worker/rhpv3.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
Passed a logger to `upload`, `download` and `migrate`. I considered making them methods on the `worker` but we still have to pass in the `worker` because of the provider interface which is kind of silly. 
I rewrote the `rhpFundHandler` because on my node I'm seeing some of these errors which are terribly non-descriptive and should not even be happening. 
```
2023-03-23T09:28:25+01:00       ERROR   worker.worker   worker/worker.go:692    failed to fund account: FundAccount: ReadResponse: [Funding ephemeral failed; Could not deposit funds; Deposit failed; ephemeral account maximum balance exceeded] {"host": "ed25519:70c74a963eb31ee10decbc3ee508697a6cd549dfd1908b1326f548595952422b", "balance": "1 SC"}
```
=> worker: add logging

internal/testing/cluster_test.go, worker/worker.go
Handling the `path` is pretty annoying. We have to perform the suffix check on the path param and not the sanitised path. I think it's annoying because our clients don't handle paths that well I feel. They expect the user to pass in the path without the slash prefix. 
I played around with stripping the slash in the client but quickly ran into trouble because we have both a worker and bus client and it becomes messy really fast. Since most people are using the API I think it's fine for the time being.
=> ObjectList at root

bus/bus.go, bus/client.go, internal/stores/metadata.go
1. Create a `DELETE /bus/contracts/set:set` endpoint that allows deleting a contract set, which isn't needed anymore.
2. Create a `DELETE /bus/contracts/all` endpoint to batch delete all contracts from the bus.
=> Add extra endpoints

worker/rhpv3.go, worker/transfer.go, worker/worker.go, worker/worker_test.go
This PR fixes delays on releasing contracts due to passing already cancelled contexts by swapping out the context in `ReleaseContract` with a different one that eventually times out for safety. The span is retrieved from the original context and attached to the new one to maintain traceability. 
Update: I've been running this over night without issues.
=> Make sure releasing a contract isn't blocked by a cancelled context

internal/stores/hostdb.go
blocked hosts should be included for scanning for two reasons:
- we definitely want to keep tabs on a host's uptime even if it is currently on the blocklist (or not on the allowlist)
- host pruning does not kick in if hosts are not being scanned
essentially this will "hurt" the autopilot for a while (~10days) and after that it should get rid of 95% of the bad hosts and continue with the actual host network
=> Include Blocked Hosts in HostsForScanning 

.github/workflows/publish.yml
Add the `stable` branch to the list of branches for which to trigger the publish action.
Verified the publish action: https://github.com/SiaFoundation/renterd/actions/runs/4562155511/jobs/8048993165
```json
{
"tags": [
"ghcr.io/siafoundation/renterd:pj-publish-stable",
"ghcr.io/siafoundation/renterd:347f0f7"
],
"labels": {
"org.opencontainers.image.title": "renterd",
"org.opencontainers.image.description": "A renter for Sia",
"org.opencontainers.image.url": "https://github.com/SiaFoundation/renterd",
"org.opencontainers.image.source": "https://github.com/SiaFoundation/renterd",
"org.opencontainers.image.version": "pj-publish-stable",
"org.opencontainers.image.created": "2023-03-30T08:18:58.556Z",
"org.opencontainers.image.revision": "347f0f7f3e1ba6fb3bf219fcd44a5825c5ca0164", …
```
=> Stable Image

autopilot/scanner.go
good to catch it now I guess, I would personally _not_ ignore the context in `Shutdown` but perhaps this would've gone unnoticed so...
```
goroutine 1 [semacquire, 18 minutes]:
runtime.gopark(0xc0004abb80?, 0x49d5bd?, 0x60?, 0xe0?, 0xc004cecf80?)
/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc0004aba98 sp=0xc0004aba78 pc=0x443056
runtime.goparkunlock(...)
/usr/local/go/src/runtime/proc.go:369
runtime.semacquire1(0xc0005819c8, 0x48?, 0x1, 0x0)
/usr/local/go/src/runtime/sema.go:150 +0x1fe fp=0xc0004abb00 sp=0xc0004aba98 pc=0x453fbe
sync.runtime_Semacquire(0xc0004abb48?)
/usr/local/go/src/runtime/sema.go:62 +0x25 fp=0xc0004abb30 sp=0xc0004abb00 pc=0x470045
sync.(*WaitGroup).Wait(0xc000388ba0?)
/usr/local/go/src/sync/waitgroup.go:139 +0x52 fp=0xc0004abb58 sp=0xc0004abb30 pc=0x47fcd2 …
```
=> Autopilot Shutdown

api/bus.go, bus/bus.go, bus/client.go, internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/cluster_test.go
New endpoint that provides some info related to objects stored in the bus.
It returns:
- number of objects
- size of all objects before uploading
- size of all distinct sectors that make up the objects
- size of all sectors that make up the objects
The last 2 usually match unless objects are repaired.
=> Add /objectsinfo endpoint

internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/pruning_test.go
I found out we are not retrying adding a contract, that's definitely not ideal so I added that. Alex told me some hosts have more than one active contract, and he's right. There are some active (renewed) contracts that weren't properly removed. That's a bit odd because we do that in a transaction that includes the deletion so I think it may be a legacy issue. I'm not sure so I figured I would add an assertion on `RowsAffected` after the deletion.
I added `TestArchiveContracts` since I was there anyway and it's a test I wanted to add to the HostDB pruning PR that got merged already. It's just a basic test that asserts contract archival works and the reason gets set.
=> Retry AddContract and harden AddRenewedContract

api/autopilot.go, autopilot/contractor.go, autopilot/hostfilter.go, worker/gouging.go, worker/rhpv3.go, worker/sessionpool.go, worker/worker.go
This PR proposes a new `GougingBreakdown` api type that returns a breakdown of the various gouging checks we perform. While I was at it I decided to refactor the gouging code a bit. We were basically defining what gouging checks need to be performed in two locations (`PerformGougingChecks` and `IsGouging`), which is not ideal of course. I updated the interface a bit and I think it's improved a bit. I never really liked that we were passing around `ignoreBlockheight` bools so I want to propose manipulating the price table instead, I personally think that's a cleaner solution.
The breakdown is just a list of errors, exactly as they're returned from the gouging checker. They should be human readable and can definitely be user facing, although the fields in the breakdown are not …
=> Gouging Breakdown

api/bus.go, autopilot/contractor.go, autopilot/hostfilter.go, internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/pruning_test.go
This PR fixes a bug in the contractor where a contract would get refreshed over and over again, each time doubling it renter funds, leading to the user's entire wallet balance being locked up in a single contract. We had foreseen this refresh loop but the check we added to prevent it from happening did not take into account the contract price (which is taken into account when doing the checks that indicate a refresh is needed).
=> Fix Contract Refresh Loop

autopilot/contractor.go, autopilot/hostfilter.go
If a contract needs to be archived, we do not have to perform any checks that might result in a contract refresh or renewal. This avoids a panic where the block height exceeds the contract's end height used when computing the new contract's collateral.
Fixes #262
=> Fix Usable Contract Panic

bus/client.go, worker/client.go
When `Client.Object` returns entries, it includes a leading / in each result. This caused a problem when calling `Client.Object` with the child path.
=> API client: trim leading / from object path

api/autopilot.go, autopilot/autopilot.go, autopilot/client.go, internal/testing/pruning_test.go
Took me a while to realise where the NDF came from but realised it was the worker's interactions buffer. 
I rewrote the test in a way that should 100% prevent an NDF from occurring. I can be sure of that because I shut the worker down manually, that's obviously a bit sketchy but if it prevents the NDF it's well worth it imo. I've also removed the `Retry` (for the check at least) and tweaked the failed interactions and downtime to push it right before the threshold, and then over it, making the integration test way more solid.
=> Fix HostPruning NDF

autopilot/contractor.go, autopilot/contractorspending.go
This PR fixes 2 things:
1. use the active contracts returned by the bus to determine what hosts we have contracts with. The worker might not return all contracts.
2. do the same for computing the remaining funds. Just because we failed to fetch a revision from a host, doesn't mean that we didn't allocate money for it. Prevents allocating more tokens per period than the allowance.
=> Use all active contracts to determine used hosts and not just the ones returned by the worker

api/worker.go, worker/worker.go
When a node is synced it makes no sense trying to upload a file because it is likely to fail down the line because of various block height related errors being thrown, so I added a check for that and return a 503 status code and error message indicating consensus is not synced.
Example upload error:
```
4b6bf45a: Write: host rejected Write request: ReadResponse: communication error: host expected to post at most 676011510135535960064 collateral, but contract has host posting 950240678641284834918: rejected for low paying host missed output
```
=> Return 503 Service Unavailable if consensus is not synced

autopilot/hostfilter.go
The gouging breakdown was not initialised causing the `Gouging` checkmark in the UI to be green all the time. Reported by some beta testers in the community:
=> Fix HostInfo

autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostscore.go, autopilot/hostscore_test.go
This PR ensures the host scoring does not use host settings for hosts that are considered gouging. This prevents a panic when calculating the `hostPeriodCostForScore` which uses the `core` package to calculate all kind of different costs like the `RPCAppendCost` for instance. Instead of extending the `core` package with overflow math, I think we should instead perform the gouging checks and avoid the scoring checks if we know the host is gouging.
Fixes #283
=> Fix HostScore overflow panic

api/bus.go, bus/bus.go, bus/client.go, internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/cluster_test.go, worker/client.go, worker/worker.go
Closes https://github.com/SiaFoundation/renterd/issues/295
Return a slice of `api.ObjectMetadata` instead of ´[]string`.
The metadata contains the name which is the string we returned before as well as the size of the file/folder.
=> When listing objects, return an array of metadata instead of just the object names

internal/stores/metadata.go, internal/stores/metadata_test.go
It turns out `contractsForHost` returned all contracts regardless of what host was being passed. This is not good. This means pruning a single host archives all your contracts. I fixed it and added a dedicated unit test.
=> Fix MetadataStore helper

go.mod, go.sum
- Fixed an issue where the entire UI errors - UI is now compatible with the updated objects endpoint schema.
- The sync screen now shows the correct network block height when using the Zen testnet.
- The unlock form now times out after 5s and shows a new 'Error, daemon did not respond' error - this occurs when the wallet is re-indexing.
- The hosts explorer column state icons are now more clear, some columns now use a gray negative or non-initialized state.
- The network block height is now estimated. renterd no longer uses SiaStats for anything so the 3rd party data privacy toggle has also been removed.
=> ui: v0.12.0

internal/stores/metadata.go
I noticed some of my archived contracts didn't have their host key field populated. That's not a big deal but it's probably best to make sure it's set correctly, it makes it easier to revert archiving a contract should that ever be necessary and it's just inconsistent so I updated it.
=> Archived Contracts Missing Host

api/autopilot.go, autopilot/autopilot.go, internal/stores/hostdb.go, internal/stores/sql.go, internal/testing/cluster.go, internal/testing/pruning_test.go
I added validation to the autopilot config. For the time being I've only added a check for `MaxDowntimeHours`. I wanted to "quickly disable" host pruning on my node and updated the `MaxDowntimeHours` setting to 9999999999. It turns out this overflows the duration and essentially disables the prune condition on `recent_downtime`
=> Autopilot Config Validation

autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostscore.go, autopilot/hostscore_test.go
This PR fixes a log line and prevents the host from being scored if we find it is gouging. There's really no need to score a host if we know it is gouging because we a) can't even perform all checks and b) its score will always be 0 anyway.
=> Autopilot Minor Fixes

cmd/renterd/main.go, internal/node/node.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
This refactors the download code to match the upload code in regards to limiting the ongoing overdrive during a download.
The overdrive starts at 0 and as slow responses come in increases to 5. 
NOTE: before this PR the download code would just launch 1 worker per shard right away.
=> Limit download overdrive

internal/stores/metadata.go, internal/stores/metadata_test.go, internal/testing/cluster_test.go
Fixes a query that failed for UTF-8 characters within the path name of an object.
Related to https://github.com/SiaFoundation/renterd/issues/308 but the UI probably also needs an update. I can manually create objects through the API that contain special characters and show up in the UI, but I can't create such dirs or files through the UI @alexfreska
=> Add support for UTF-8 object paths

api/bus.go, bus/bus.go, bus/client.go, bus/contractlocking.go, bus/contractlocking_test.go, cmd/renterd/main.go, internal/node/node.go, internal/testing/cluster.go, worker/rhpv3.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go, worker/worker_test.go
Locking contracts is a bit fragile under a lot of load because there is no way to know how long the contract needs to be acquired for by a worker. If a host is very slow, the contract might be released before the worker is actually done using it.
To fix that, this PR adds a new endpoint that allows for extending the duration of an acquired lock. Locks will now be acquired for 30s by default and if the operation isn't done within half of that time, the duration is extended by another 15s.
=> Improve contract locking

internal/testing/cluster_test.go, worker/rhpv3.go, worker/transfer.go, worker/worker.go
The test wasn't waiting for accounts to be funded. So the uploads would time out. Due to a bug the uploads wouldn't fail though and result in the downloads trying to download empty roots. Which caused the errors on the CI.
This PR fixes the bug and updates the test to wait for accounts to be funded.
=> Debug `TestParallelDownload` NDF

worker/rhpv3.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
When we discuss the code internally we use the term host v2 and v3 and we don't really use the "sector store" abstraction anyway. It's not like the host is a composite of multiple stores or something so I figured it might make sense to rename `SectorStoreProvider` to `HostProvider` so `withHostV3` can return `HostV3` and things are easier to read.
=> Rename SectorStore to HostV2|3

autopilot/accounts.go, bus/client.go, worker/transfer.go
Now that we download from all active contracts, we refill all active contracts... this might lead to a lot of fund errors because active contracts are not necessarily suited to refill ephemeral accounts with.. the host might be offline, the host might be gouging etc etc.
This PR updates the refill code to 
a) try all contracts for any given host rather than randomly selecting one (this was a bug)
b) only log errors if the host has at least one contract that's in the contract set
=> Refill Active Contracts

worker/rhpv3.go
use separate ctx to schedule an ea sync to ensure a cancelled context doesn't prevent us from updating the bus (happens in production quite often when doing benchmarks)
=> Schedule Sync

autopilot/contractor.go
Fixes #322 by moving the contract cap into the renewal code.
=> Move contract capping code into renewal method

api/contract.go, autopilot/contractor.go, internal/testing/cluster_test.go
This PR updates the worker's contracts endpoint to return all contracts and only attach a revision if possible. This cleans up the logic in the autopilot and makes it less prone to errors.
This should also fix contracts not expiring when a revision can't be fetched.
=> Change /rhp/contracts/active to return all contracts

worker/gouging.go, worker/rhpv3.go, worker/transfer.go, worker/transfer_test.go, worker/worker.go
This PR fixes an issue where gouging checks fail after a while since we never update the consensus state within the gouging checker. So instead of attaching a gouging checker to the context, we attach a function to create a gouging checker on demand.
While going through the code to see what calls to update, I ended up doing a few refactors as well. Mostly to achieve the following structure for all endpoints calling RPCs.
1. The RPC is a function (not a method) located in `rhpv3.go`
2. The RPC is called by an exposed method on the `host` type. 
3. The method on the `host` is called by a method on the `worker` that has the same name but essentially only calls `withHost`.
There might be a few leftovers that also require updating but I think this really improves the overall readability since …
=> Fix long running uploads failing due to host price gouging

worker/transfer.go, worker/transfer_test.go, worker/worker.go
Since v3 hosts don't require any cleanup, this PR refactors `withHostV3` to `newHostV3` to reduce overall nesting and decrease the likelihood of mistakes happening due to the increased usage of named variables.
=> Refactor withHostV3 to newHostV3

api/bus.go, bus/bus.go, internal/node/node.go, internal/testing/cluster_test.go, worker/gouging.go
To avoid accidentally nuking your contract set when your machine is on sleep or the VM you run renterd in is suspended, this PR adds the last block's timestamp to the consensus state.
If more than 60 minutes (6 block times) have passed since the latest block, we only check that the host is at least on the same block height as we are since we may no longer be synced.
Closes https://github.com/SiaFoundation/renterd/issues/367
=> Consider last block's timestamp in gouging

worker/rhpv3.go, worker/worker.go
After renewing a contract we weren't adding the host transaction to the txnSet. So broadcasting it would always fail. This PR fixes that.
=> Fix failure to broadcast renewal txns

autopilot/scanner.go, worker/worker.go
As the title suggests we should abort scanning as soon as one scan fails since that should never be the case to begin with. The autopilot will then retry in the next iteration.
We also shouldn't scan if we don't consider ourselves as online.
=> Don't scan hosts while being offline and abort scan if endpoint returns an error

worker/rhpv3.go
The revision mismatch is caused due to an issue in `siad` which will be fixed in `hostd`. Until then, this change will serve as a workaround.
NOTE: The "proof verification failed" - error is a side-effect of the revision number mismatch. So it's also fixed by this PR.
=> Fix revision mismatch errors

internal/testing/blocklist_test.go, internal/testing/cluster.go, stores/hostdb.go
Turns out the blocklist doesn't work (in some cases) when the blocklist entry was added prior to the host being announced. This is because the code that executes when new hosts are being added, differs from the code that executed when allowlist/blocklist entries get updated (for performance reasons).
There wasn't any test for this because the test cluster allows adding `n` hosts, but doesn't allow creating a host, to then later add it, allowing for us to allowlist/blocklist the host before it announces. That's basically what I've added so I could extend the tests to cover this (not-so-)edge case.
The main change is in the `blocks` method where we used to split off the host from the `NetAddress` to check with the entry, which is the reason it was not working.
Fixes #401
=> Blocklist Fix

api/worker.go, worker/upload.go, worker/worker.go
Since we punish hosts for failing we need to apply a decay to their estimates to ensure they have a means to recover from errors, making sure they will eventually get picked again. I track sector upload estimates now, and only apply decay to those, ensuring that applying decay makes hosts more and more likely to get picked.
We do not apply decay to any statistic that gets exposed. There's some arbitrary constants being introduced here, I figure they're fine but maybe we want to tweak those. I've tweaked the stats slightly so it's very clear what they represent, some stats pertain to slab upload speeds while others give the more raw sector upload speeds.
=> Decay Upload Estimates

autopilot/accounts.go, autopilot/autopilot.go, autopilot/contractor.go
I recently added a contracts cache (of sorts) to the `contractor`. Turns out this generates quite some spam on production nodes, because it's trying to refill archived and renewed accounts. I ended up removing the cache all together simply because it gets messy and in the way of the contractor flow/readability.
=> Fix Account Spam

stores/metadata.go
We ran into an issue where updating the `contract_sectors` table after renewing a contract would result in a UNIQUE constraint violation. After creating the archived contract and the new contract.
Since the method was updating the db quite inefficiently anyway we decided to refactor it.
Previously it would do:
1. Create archived contract
2. Create renewed contract by inserting a new row into the contracts table
3. Update contract set table
4. Update contract sectors join table
5. Delete old contract
Now it's doing:
1. Create archived contract
2. Update the old contract's row instead of inserting a new contract
This should be a lot faster since it touches only 2 tables without insertions and also doesn't update any foreign keys in a join table, potentially violating constraints.
=> Use update in addRenewedContract instead of insertion

api/bus.go, autopilot/autopilot.go, autopilot/migrator.go, bus/bus.go, bus/client.go, stores/metadata.go, stores/metadata_test.go, worker/transfer.go
This PR updates `UnhealthySlabs` which is crucial for migrations. We were not returning slabs with a negative health, which is unlikely but possible if the slab has lots of sectors on the same hosts. We were also not returning any slabs that have sectors that don't belong to a contract. This shouldn't happen but we witnessed it first hand on our own nodes...
This PR will be followed up with more health related changes to improve both the performance of this query as well as trying to simplify health in general because it's getting hard to wrap your head around all the various edge cases.
=> Update Health Query

bus/bus.go, internal/testing/cluster_test.go, stores/metadata.go, worker/worker.go
When deleting objects through the worker endpoint instead of the bus the "/" at the beginning of the key isn't trimmed, causing the deletion to not happen without an error.
This PR fixes this and makes sure a 404 is returned when deletion fails due to an unknown key.
=> Fix bug in object deletion when using worker endpoint

autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostinfo.go, autopilot/ipfilter.go
The redundant IP check should always be performed as the last check before determining whether a contract can be used or not. 
If we update the IP filter and the contract fails a later check, subsequent contracts might be blocked due to their IP address even though they should be used since the first contract on the subnet failed a different check anyway.
This PR also updates the order we use to look at contracts when checking them. We start with the ones having the most data to make sure that we drop the contract(s) with the least amount of data when a redundant ip range is detected.
=> Improve redundant IP check

api/contract.go, internal/testing/cluster_test.go, stores/hostdb.go, stores/metadata.go, stores/sql.go, worker/rhpv3.go, worker/spending.go
That way we have a fallback value in the autopilot in case we can't fetch a revision but still want to perform some checks.
=> Record size of a contract alongside spending metrics

autopilot/migrator.go
```
2023-06-20T15:58:02+02:00       DEBUG   autopilot.migrator      autopilot/migrator.go:122       281 potential slabs fetched for migration
2023-06-20T15:58:02+02:00       DEBUG   autopilot.migrator      autopilot/migrator.go:157       281 slabs to migrate
2023-06-20T15:58:02+02:00       INFO    autopilot.migrator      autopilot/migrator.go:169       migrations interrupted - updating slabs for migration
2023-06-20T15:58:07+02:00       DEBUG   autopilot.migrator      autopilot/migrator.go:122       281 potential slabs fetched for migration
2023-06-20T15:58:07+02:00       DEBUG   autopilot.migrator      autopilot/migrator.go:157       281 slabs to migrate
```
we have to ignore the signal right before starting the loop because we fetch slabs twice for no reason now (see timestamps)
=> Ignore Signal

api/autopilot.go, autopilot/autopilot.go, autopilot/contractor.go, cmd/renterd/main.go, internal/node/node.go, internal/testing/cluster.go
To avoid keeping contracts around that we can't revise or renew anymore anyway.
The PR also increases 2 timeouts.
=> Archive contracts when reaching the revision submission buffer of the host

api/autopilot.go, autopilot/hostfilter.go, hostdb/hostdb.go, metrics/metrics.go, worker/interactions.go, worker/rhpv2.go, worker/rhpv3.go, worker/transfer.go, worker/transfer_test.go, worker/upload.go, worker/worker.go
This PR refactors metrics and interactions a bit in the worker.
Everything the worker records now goes through a metrics recorder as a metric.
The metric is then turned into an interaction which is sent to the bus.
Even scans and pricetable updates are now handled that way and contain metric information.
Whether a metric is considered a successful interaction is now determined by `isSuccessfulInteraction`. That way we can easily exclude some errors from causing an interaction to not be successful. 
This PR also removes the recording of metrics for rhpv2 RPCs. Because the only interaction that still happens over rhpv2 is scanning hosts which is explicitly recorded in the corresponding handler.
=> Refactor metrics recording

worker/worker.go
I've seen quite a few `rejected for bad file size` errors recently and it seems like we aren't locking the revision before renewing a contract. This PR fixes that.
=> Fix revision locking on renewals

autopilot/contractor.go, autopilot/hostfilter.go
Some contracts might be up for renewal but not considered unusable yet. These contracts should be kept in the set instead of dropping them if the renewal fails.
Contracts that are up for renewal will be dropped if they haven't renewed by the second half of the renewal window.
=> Don't drop contracts that are usable and up for renewal from the set

api/autopilot.go, api/params.go, autopilot/autopilot.go, autopilot/client.go, autopilot/hostinfo.go, autopilot/migrator.go, autopilot/scanner.go, autopilot/scanner_test.go, internal/testing/cluster_test.go
This PR updates the response returned by `/api/autopilot/status`. I went back and forth a lot on the response types but eventually just tried to stay consistent with the rest of the API (returning a `ParamDuration` and `ParamTime`, specifying the duration unit in milliseconds). 
Example status response
```json
{
"configured": true,
"migrating": false,
"migratingLastStart": "0001-01-01T00:00:00Z",
"scanning": false,
"scanningLastStart": "2023-06-27T16:05:18+02:00",
"synced": true,
"uptimeMS": "39870"
}
```
=> Autopilot Status

cmd/renterd/main.go
I originally wanted to cleanup the autopilot folder but I ran `renterd` from the repo yesterday to test something and noticed it had removed the `autopilot` directory. Kind of annoying and I think many ppl pull in the repo, build and run it so we should probably stick to removing autopilot.json and nothing more.
=> Minor Migration Change 

stores/metadata.go
If only empty objects exist, `NumObjects > 0` but we won't be able to find slices, resulting in an error.
=> Add COALESCE to ObjectStats to avoid returning NULL if no slices exist

autopilot/contractor.go, cmd/renterd/main.go, internal/testing/cluster_test.go, worker/rhpv3.go, worker/worker.go
This PR increases some timeouts to make sure the contract maintenance picks up on empty accounts and schedules them for a refill.
=> Increase timeouts for better account refills

worker/interactions.go, worker/worker.go
We noticed some contract churn due to hosts getting a worse interaction score over time because of hundreds and thousands of failed dial interactions. 
The problem is that dial is a very low-level operation and we don't know whether it fails due to us closing the context because we don't need the connection anymore (e.g. overdrive when downloading) or because the host is actually timing out. So we are limiting recorded interactions to more high level ones such as fetching a pricetable, scanning a host or downloading a sector where we can say with certainty that the interaction failed due to the host or because we interrupted it.
=> Don't record dial metrics in worker

bus/bus.go
Since we batch quite a few interactions when recording them insertions sometimes take a couple of seconds.
When it takes longer, another worker or the even the same might try to record another batch.
When 2 batches are applied at the same time we run into locking failures on the table and due to the retry mechanism the transactions keep blocking each other while getting retried.
To fix that, this PR adds a queue for recording interactions to make sure batches don't compete with each other.
=> Queue batches of interactions to record instead of trying to apply them as they come in

object/object.go, object/object_test.go
The implementation of ChaCha we use makes use of a `uint32` counter meaning that the maximum size of an object is `64 *  4GiB` which is `256GiB`. To work around this we overflow into the last 8 bytes of the `nonce` and reset the counter for every `256GiB`.
=> Extend object encryption to support files larger than 256GiB

.github/workflows/test.yml, internal/testing/cluster_test.go, worker/rhpv3.go
The locking we have right now was acquiring a transport's lock while holding the lock of the pool. 
The transport dials a connection while holding that lock.
So if a transport is timing out on a dial and another thread is trying to dial the same host that is timing out at the moment, it will block on acquiring the transport lock while the pool lock is also acquired, preventing other threads from creating transports. 
After this PR, the locking will no longer overlap. So a transport timing out with host A can't block creating a transport with host B.
=> Avoid overlapping locking between transport and transportpool

bus/bus.go, stores/hostdb.go, stores/metadata.go, stores/sql.go
For the same reason as in https://github.com/SiaFoundation/renterd/pull/463 we are also applying spending updates in series to avoid a `retryTransaction` to block out another transaction for an extended period of time.
=> Apply contract spending updates in series

api/bus.go, bus/bus.go, bus/client.go, internal/testing/cluster_test.go, stores/wallet.go, wallet/wallet.go, wallet/wallet_test.go
This PR updates the /bus/transactions endpoint with a 'before' parameter as well as forces it to return the latest transaction first. 
Closes https://github.com/SiaFoundation/renterd/issues/475
=> Extend /bus/transactions endpoint with 'before' parameter

autopilot/contractor.go, autopilot/hostfilter.go, internal/testing/cluster_test.go, worker/download.go
This PR will contain a couple of fixes to the download code we merged recently. It should drastically lower the memory footprint of `renterd` (on large downloads) because of how we handle concurrent slabs.
=> Download F/U

autopilot/contractor.go, autopilot/hostfilter.go
If we have a contract with a host that is on the same subnet as another one we want to migrate data away from it. We might not be able to do that if we stop refreshing the contract though since it might run out of funds while migrating the data.
So if a contract is meant to be refreshed but fails the redundant IP check, we still allow it to be refreshed.
=> Allow for refreshing contracts with hosts that have a redundant IP subnet

alerts/alerts.go, autopilot/autopilot.go, autopilot/client.go, autopilot/migrator.go, bus/bus.go, bus/client.go, worker/client.go, worker/worker.go
This PR adds the alert system from `hostd` to `renterd`'s autopilot, worker and bus.
Initially there is an info alert that notifies users of ongoing migrations.
=> Add alert system

api/bus.go, bus/bus.go, bus/client.go, internal/testing/cluster_test.go, stores/metadata.go, stores/metadata_test.go
By popular demand this PR adds support for renaming objects atomically.
=> Add support for renaming objects in bus API

cmd/renterd/main.go
This PR changes `renterd seed` to print the actual seed to `stdout` while the remaining logging goes to `stderr` as usual. That way it's easier to use the output of `renterd seed` in scripts.
Closes https://github.com/SiaFoundation/renterd/issues/495
=> Print seed to stdout instead of stderr with regular logging

autopilot/accounts.go, autopilot/migrator.go, worker/rhpv3.go
Fixes an issue with downloads on our Arequipa node
```
couldn't download object '/s5/H23lb7IatJJ0U_QX-kOTkF2enHrtaKXmyJ81CMKiBzKm': failed to download slab: completed=1, inflight=0, launched=30 downloaders=118 unused=0 errors=
3e37b161: ReadSector: remaining budget is insufficient
662dbfb2: ReadSector: remaining budget is insufficient
443c7ae7: ReadSector: remaining budget is insufficient
4074d176: ReadSector: ReadResponse: [failed to set budget limit on stream; insufficient budget for bandwidth]
9ce46fd4: ReadSector: ReadResponse: couldn't read subscription response: insufficient budget for bandwidth
4b804458: ReadSector: ReadResponse: [failed to set budget limit on stream; insufficient budget for bandwidth]
c8dc6403: ReadSector: remaining budget is insufficient
```
=> Increase download budget

autopilot/autopilot.go, autopilot/migrator.go, bus/bus.go, bus/client.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go
This PR adds a 'health' column to the slabs table which is periodically recomputed before migrations.
NOTE: tested on my node so far and updating the health of all 12k slabs takes around 4 seconds.
=> Health caching

api/worker.go, bus/client.go, internal/testing/cluster_test.go, internal/testing/migrations_test.go, worker/worker.go
This PR adopts the `opts ...FooOptions` pattern for the `Object` client method to make using it a bit more self-explanatory.
=> Make Object method of bus client more user-friendly

autopilot/autopilot.go, internal/testing/cluster_test.go, worker/client.go, worker/rhpv2.go, worker/rhpv3.go, worker/worker.go
Adds a new endpoint to the worker which allows for submitting a contract's revision to the network.
This can serve multiple purposes such as periodically publishing revisions to limit a host's ability to submit an old revision in case they lose data.
=> Add /rhp/broadcast/:id endpoint to worker

object/slab.go, stores/metadata.go, stores/metadata_test.go
Slabs returned through the API now contain their latest computed health. That way the UI doesn't need to compute the health on the client-side anymore and instead it is consistent with the health the autopilot uses for migrations.
=> Add Health field to Slab

worker/worker.go
This small rewrite avoids jape flagging the handler as writing multiple responses.`Handler writes multiple responses (previous write at siafoundation/renterd/worker/worker.go:1065:5)`
=> Multiple Response Write

api/worker.go, worker/worker.go
`jape` can't handle using constants from another package in `DecodeForm`, it panics with `panic: unhandled expr type (*ast.SelectorExpr)`. We should fix it in the analyzer but until that's fixed I decided to remove the query string constants since we were hardly consistent about using constants for query string params anyway.
edit: when all jape related fixes are merged it probably makes sense to do a full pass of our API and extract all query strings into constants as a `MINOR` improvement/cleanup
=> Remove QueryString Const

autopilot/contractor.go, autopilot/hostfilter.go
When a contract needs to be renewed we divide them into two categories essentially, the ones in the first half of the renewal window and the ones in the second. We consider contracts still in the first half to be usable. Those usable contracts we want to keep regardless of whether renewals fails or were halted (e.g. because of insufficient balance or out-of-sync-periods). This was not happening causing a bunch of nasty side-effects.
If we don't keep those contracts, they drop off from the set without knowing the reason (`reason: "unknown"` in the logs), but not only that, we think we have to form new contracts since we don't end up with `cfg.amount` contracts after renews and refreshes.
On arequipa this led to two waves of contract churn, causing ~85% of the contract set to be replaced, …
=> Fix Contractor Renewal Bug

api/bus.go, bus/bus.go, bus/client.go, internal/testing/pruning_test.go, stores/metadata.go, stores/metadata_test.go, worker/rhpv3.go
This PR exposes two new routes in the `bus` API that return the amount of data that can be pruned from a contract (or across all contracts). I use the (cached) `size` field on the contract and compare it against the amount of contract sectors. These routes will have `POST` counterparts in the worker API to list the sectors from a contract and perform the actual sector deletion.
- `size` field was being set to the old revision file size, thus lagging one sector
- `size` wasn't being copied over to the renewed contract
`NOTE` naming was bothering me a bit in this PR but I couldn't find a better alternative
=> Sector Deletion pt1 - prunable data

internal/testing/cluster_test.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go
Some endpoints behaved incorrectly due to the `LIKE` operator in SQL not being case-sensitive. 
This PR fixes that and extends the test suite with relevant testing.
Closes https://github.com/SiaFoundation/renterd/issues/501
=> Make object_id case-sensitive

api/bus.go, autopilot/autopilot.go, autopilot/contractor.go, bus/bus.go, bus/client.go, internal/testing/cluster_test.go, stores/wallet.go, wallet/wallet.go, wallet/wallet_test.go
This PR adds a new GET endpoint to the bus called /wallet.
The idea is to have more consistency between the hostd and renterd APIs so the response matches the response of hostd's /wallet endpoint apart from one missing field which we can't populate yet.
This exposes the scan height of the wallet for the first time, gives more information about confirmed balance and actual spendable balance and makes 2 other endpoints (balance, address) obsolete. 
Closes https://github.com/SiaFoundation/renterd/issues/451
=> GET /bus/wallet endpoint

api/autopilot.go, autopilot/autopilot.go, autopilot/contractor.go, internal/testing/cluster_test.go, internal/testing/pruning_test.go
This PR addresses one of the issues reported in https://github.com/SiaFoundation/renterd/issues/500.
Hosts can be scanned without configuring the autopilot or waiting for the consensus to be synced.
=> Allow for scanning hosts without configuring autopilot or syncing blockchain

api/autopilot.go, autopilot/hostinfo.go, internal/testing/cluster_test.go
This PR addresses part of https://github.com/SiaFoundation/renterd/issues/500. Instead of not returning hosts that we don't have in the autopilot cache yet we mark them as `IsChecked = 'false'` and still return them when the filter mode is set to 'all'.
=> Return all hosts in /autopilot/hosts when FilterMode is 'all' without skipping the ones that aren't cached

hostdb/hostdb.go, stores/hostdb.go, worker/interactions.go
Persisting every pricetable and host setting puts a lot of pressure on the database. Since we already persist settings and price tables in the hosts table, we stop doing so on every interaction.
=> Don't persist host settings and pricetable for every host interaction

api/bus.go, build/env.go, bus/bus.go, bus/client.go, internal/node/node.go, internal/testing/cluster_test.go, object/object.go, object/slab.go, stores/autopilot_test.go, stores/hostdb_test.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go, stores/settingsdb_test.go, stores/sql.go, stores/sql_test.go, worker/download.go, worker/upload.go, worker/worker.go
This PR is the final upload packing PR. After merging it, users will be able to enable upload packing through the corresponding setting.
After some testing I decided to not store the partial slabs in the database and instead in a file. Storing them in the database worked but the performance was horrible. Individual 4 kib files took around 5-40s to be added to the MySQL buffer. MySQL also started printing warnings related to the redo log capacity.
Using separate files I was able to do 5+ files per second which is reasonable considering multiple fsyncs are required per file and considering that my test node was running off of HDDs and not SSDs.
=> Upload packing support

api/bus.go, bus/bus.go, bus/client.go, internal/node/node.go, internal/testing/cluster_test.go, wallet/wallet.go, wallet/wallet_test.go
Adds the "unconfirmed" field to the /wallet response.
=> Return unconfirmed siacoins in /wallet endpoint

cmd/renterd/main.go
I think we should deprecate some CLI flags before v1.0.0 now that we still have the chance.
The following flags I think we should deprecate in favor of their environment variable:
- `db.password`
- `bus.apiPassword`
- `bus.remoteAddr`
- `worker.apiPassword`
- `worker.remoteAddrs`
I figured we'd best move the bus/worker remote addresses since we're expecting them to configure the passwords through the environment variables. It also separates _actual_ node config from infrastructure related configuration. Added bonus is we can make worker api password plural and accepts a different password per worker.
I'm fine with closing this PR all together by the way. I don't feel very strongly but at the same time I have this now-or-never feeling. If merged I'll immediately create a PR to make the …
=> Deprecate CLI Flags

.github/workflows/test.yml
We recently added some integration tests that push us over the 15' mark, although to be fair we've had some slow tests in the test suite for quite some time:
`TestUploadDownloadBasic passed in 52.07s`
`TestUploadDownloadExtended passed in 67.31s`
`TestParallelDownload passed in 70s`
`TestUploadPacking passed in 96.26s`
`TestSlabBufferStats passed in 52.98s`
In the future I guess we'll have to split up the suite into separate test suites and take a look at the slowest ones to see if we can't get rid if redundant test cases and/or just speed them up in general. I'm sure there's lots of room for improvement there but since we're still "only" at 15 minutes perhaps it's fine to increase the timeout for now.
=> Increase timeout

autopilot/autopilot.go, autopilot/contractor.go, cmd/renterd/main.go, internal/node/node.go, wallet/wallet.go
As the title suggests the autopilot will start broadcasting revisions periodically as part of the contract maintenance. By default this happens every 24 hours for now but it is configurable.
=> Have autopilot periodically submit contract revisions

api/bus.go, api/contract.go, bus/bus.go, bus/client.go, internal/testing/pruning_test.go, stores/metadata.go, stores/metadata_test.go
Debugging sector pruning I was a little annoyed with what the `bus` returned. I think we should perhaps slightly refactor it so the responses are a bit nicer to work with. 
- should be able to easily query a contract's size and the amount of data that's prunable
- I think we should keep `contract/prunable` but return a response rather than a number with an aggregated field + size breakdowns
=> Contract Size

autopilot/migrator.go, bus/bus.go, internal/node/node.go, stores/hostdb_test.go, stores/metadata.go, stores/sql.go, stores/sql_test.go
On Arequipa an upload failed due to the database transaction being rolled back after the buffer was deleted on disk. To avoid that in the future, the buffer is removed after the transaction is applied to the db successfully.
=> Fix bug where uploads fail due to the buffered slab being missing from disk

bus/bus.go, stores/metadata.go
This PR avoids usage of the `SIGN` function as well as avoid an underflow in the unsigned integer if the contract size is smaller than it's sector counts. This should be impossible but I've found two occurrences on my node where the size is 0 and the count is 1. 
On `arequipa` I noticed the response of `/contracts/prunable` contained some empty structs so rewrote the handler to ensure that's no longer possible
=> Contract Size Query

go.mod, go.sum
- The failed to migrate slab alert now lists the associated objects/files.
- The host explorer now has an interactive map. Filtered hosts can be selected via the list or map, and hosts on the map are colored based on whether renterd is actively contracting with the host. For hosts with active contracts the size of the hosts on the map is based on renterd's used storage, for hosts without active contracts the size is based on the hosts remaining storage.
- New users are now more clearly instructed to configure autopilot and to wait for enough contracts before files can be uploaded.
- File upload and directory creation are now disabled until enough contracts are formed.
- Node profile information now includes the build version.
- The connectivity and login check no longer depends on …
=> ui: v0.27.0

stores/hostdb.go, stores/metadata.go, stores/migrations.go, stores/sql_test.go
I found out we were missing indices on the 2nd field of our composite primary keys in all of our join tables.
- contract_set_contracts (db_contract_id)
- contract_sectors (db_contract_id)
- host_blocklist_entry_hosts (db_host_id)
- host_allowlist_entry_hosts (db_host_id)
I decided to use `SetupJoinTable` as mentioned in the `gorm` docs and add a migration to handle existing setups. I tested this extensively on SQLite databases, haven't tested it on MySQL yet but seems like this is something that would work on MySQL if it passes SQLite validations.
Will validate it on my MySQL node when approved/green.
=> Fix SQL Performance: missing indices

.github/workflows/test.yml, internal/testing/cluster_test.go
We've had this NDF for a while in TestNewTestCluster. Turns out the host's price table may have been updated which caused the `DeepEqual` to fail. I reversed the order of the assertions so we are notified should the host be `unusable` and I've replaced the deep equal with a length check as well as a check to see if all hosts are in the result.
Could consistently reproduce in a loop, verified that the NDF was gone too, then reverted CI changes.
```
cluster_test.go:254: result for 'usable' should match the result for ''
```
```
[{Host:{KnownSince:2023-08-23 07:36:46.138355825 +0000 UTC LastAnnouncement:2023-08-23 07:36:46 +0000 UTC PublicKey:ed25519:913a0a12468c972156f4e642becc81fc3d8764b90bde8c892b3e577995a5dbc6 NetAddress:127.0.0.1:46731 …
```
=> TestNewTestCluster NDF 

api/bus.go, autopilot/autopilot.go, bus/bus.go, bus/client.go, hostdb/hostdb.go, internal/testing/pruning_test.go, stores/hostdb.go, stores/hostdb_test.go, stores/migrations.go, worker/interactions.go, worker/rhpv3.go, worker/worker.go
Saving large amount of historic data harms. the performance of regular operations such as uploads and upload packing.
Especially using SQLite since tables of a database can't be locked independently for writing.
To avoid that, the goal is to create another database dedicated to historic data which doesn't interfere with the main database's operations.
=> Drop interactions db in preparation for a dedicated database for time series 

stores/metadata.go, stores/migrations.go, stores/sql_test.go
```
{"level":"warn","date":"2023-08-18T18:13:14Z","component":"db","msg":"SLOW SQL >= 500ms","elapsed":"19005.002ms","rows":1,"sql":"SELECT COUNT(DISTINCT db_sector_id) * 4194304 as sectors_size, COUNT(*) * 4194304 as uploaded_size FROM `contract_sectors`"}
```
I found that performing a distinct count on `db_sector_id` is super slow on arequipa. The UI performs that action quite a lot (essentially with every on_focus). The problem is only for SQLite but since we add the `index` annotation regardless of the dialector I figured we can just add it on both SQLite and MySQL databases. An extra index on such an important table/column won't hurt us.
=> Fix SQLite Slow DISTINCT

stores/metadata.go, stores/metadata_test.go, stores/migrations.go
Updating the health currently locks SQLite on a large node for more than a minute. To prevent that this PR changes 2 things.
1. slabs get a new "health_invalid" column and we only invalidate the health on slabs when some event happens that might have triggered a change. e.g. archiving a contract, adding a slab to the db, updating the contract set etc.
2. we don't compute the health for all slabs at once. Instead we do so in batches of 10k slabs at once which equals around 1.2TiB of uploaded sectors
=> Improve performance of refreshing cached slab health

stores/metadata.go
The query in `RefreshHealth` was actually updating all slabs instead of respecting the batch limit. Fixed by this PR.
=> Fix update query in RefreshHealth

stores/metadata.go
The query was previously not using an index. The new one is faster and does use indices.
=> Optimise query for ObjectsBySlabKey

bus/client_test.go, cmd/renterd/main.go, config/config.go, go.mod, go.sum, internal/node/node.go, internal/testing/cluster.go, stores/logger.go
Adds support for YAML configuration files for all CLI flags and environment variables. Checks for `renterd.yml` in the current directory. If the file doesn't exist, the startup should continue as it does today. The path can be overloaded by setting the `RENTERD_CONFIG_FILE` environment variable.
Having support for a config file will make renterd easier to package.
Example:
```yml
seed: clutch cook castle mistake slush arrange horse nothing forest potato oil wash
http:
address: 127.0.0.1:10080
password: sia is cool
```
The priority for settings is currently:
1. default values
2. yaml
3. flags
4. environment variables
=> Support YAML config

api/autopilot.go, autopilot/autopilot.go, autopilot/client.go, internal/testing/cluster_test.go
The UI moved to use `autopilot/state` (which we added to be consistent with `hostd`), now that the UI stopped using it we can fully deprecate the status route.
=> Deprecate `autopilot/status` route

autopilot/hostscore.go
While going through the logs I noticed we have contracts with hosts as old as 1.5.4 that we fail to interact with. 
This PR updates the scoring to not form contracts with versions below 1.5.9 which is about 3% of hosts on the network.
=> Update versionScore weights

cmd/renterd/main.go, stores/metadata.go
The PR also won't abort mid shutdown if any module fails to shut down. Instead renterd will print the error and eventually exit with exit code 1.
=> Shut down api last to avoid other modules getting stuck

api/bus.go, api/worker.go, autopilot/autopilot.go, bus/bus.go, bus/client.go, cmd/renterd/main.go, internal/testing/cluster_test.go, internal/testing/pruning_test.go, stores/hostdb.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go, stores/sql.go, worker/client.go, worker/worker.go
This PR adds supports for buckets to `renterd`. A bucket is a collection of objects that have been uploaded to `renterd` with some unique properties
- Two objects can have the same key if they are within different buckets
- A bucket can only be deleted if it is empty
- A bucket is not created implicitly, instead it has to be created manually before adding objects
- Operations can only be performed on a single bucket at a time with a few potential exceptions
In a sense a buckets are like folders but with stronger isolation. e.g. it's not possible to rename objects from one bucket to another or batch delete from multiple buckets at once. There is also a lot of room to extend buckets in the future by attaching metadata to them and assigning them specific properties such as different default …
=> Add support for buckets

docker/Dockerfile
When deduping the dockerfiles I apparently messed up and forgot about the api port, which is 9880 instead of 9980 when building it for the testnet. This PR corrects that mistake by simply not passing the api port since we default to the appropriate ports anyway because of the environment files that have the correct build tags on them.
E.g. `env_default` and `env_testnet` have the `DefaultAPIAddress` which is set correctly.
I had to get rid of the `EXPOSE` instructions too since those don't really make sense any more. That's unfortunate, I considered some alternatives like exposing both testnet and default ports, or generating a dockerfile but those don't seem like the right way to go either... The `EXPOSE` instruction serves as mere documentation so functionality-wise we can remove …
=> docker: fix testnet image

build/env_default.go, build/env_testnet.go, cmd/renterd/main.go, config/config.go, docker/entrypoint.sh
So after some research it turns out That the S3 specs are not meant to support running the API on an endpoint + path. 
e.g. `/api/s3`. So to avoid that `renterd` will spin up a new web server on a different port if `S3` is enabled.
This fixes issues people have reported regarding the authentication failing.
=> Run S3 api on different port

api/worker.go, autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostscore.go, worker/worker.go
Also cap the amount of expected storage in `isOutOfCollateral` using the host's remaining storage.
=> Update renterFundsToExpectedStorage to use rhpv3 pricing

stores/metadata.go, stores/metadata_test.go, stores/sql.go
This PR prevents an upload from failing just because a contract couldn't be found. Instead a warning is logged.
It also updates the `CreatedAt` timestamp in `AddRenewedContract` to make it easier to see when a contract has been renewed. In combination with the timestamp from the logging it should allow us to tell whether a contract that can't be found was renewed at that moment.
=> Don't fail markPackedSlabUploaded when a contract is missing

stores/metadata.go, worker/migrations.go, worker/upload.go, worker/worker.go
This PR updates the upload manager to return a set of used contracts. This avoids looping the sectors after calling upload/migrate and build it manually, but it also makes sure the contracts contain potential renewals.
=> Used Contracts

internal/testing/cluster_test.go, object/object.go, worker/upload.go, worker/worker.go
I was seeing how to implement etags and got side-tracked on a mini-refactor. It's a bit hard to see in the diff but it does deduplicate a bunch of code we had. I went back and forth on it a bit so definitely don't mind to discuss it further.
I extended the worker with two methods:
`func (w *worker) upload`
`func (w *worker) uploadMultiPart`
that each wrap an upload and then handle the object and (potential) partial slab data with the bus. I moved this in and out of the upload manager but eventually figured that it should not be handled by the upload manager, at the cost of duplicating persisting the partial slabs and setting it on the object.
Most importantly we now spin a goroutine to persist packed slabs, so the request that pushes it over the limit isn't blocked by the upload. I think …
=> Upload Refactor 

api/bus.go, api/worker.go, bus/bus.go, bus/client.go, go.mod, go.sum, internal/testing/s3_test.go, s3/backend.go, s3/s3.go, stores/metadata.go, stores/metadata_test.go, stores/multipart.go, worker/client.go, worker/worker.go
This PR contains a number of changes I had to make to get Nextcloud working with my renterd node.
The most notable change is the introduction of a new endpoint for listing objects within a bucket that reflects the `ListObjects` functionality of S3 more. That was necessary for 2 reasons.
1. the current ObjectEntries endpoint doesn't support querying without delimiter. The query has also grown a bit out of hand so updating it with yet another flag might have been possible but also been a nightmare.
2. the current SearchObjects endpoint does support searching without delimiter and could've been extended but it returns a slice so we can't update the response without breaking compatibility
Maybe in the future we will be able to deprecate the ObjectEntries endpoint and use the ListObjects …
=> Various S3 fixes

api/worker.go, autopilot/autopilot.go, autopilot/migrator.go, stores/metadata.go, worker/client.go, worker/migrations.go, worker/worker.go
This PR logs the number of shards we migrated and it updates slabs that for whatever reason did not need to be migrated after all. This because we've seen some weird migration behaviour on arequipa where it blows through ~5k slabs with very poor health, only to skip migration and leave them in poor-health-status.
=> Migration Logs

internal/testing/cluster.go, internal/testing/s3_test.go, stores/metadata.go, stores/multipart.go, stores/slabbuffer.go, worker/client.go
f/u to 610 which adds a regression test
Also fixes a bug related to the official amazon client and multipart uploads. Reason for that bug was that different clients seem to behave differently around passing etags to `CompleteMultipartUpload`. So sometimes the etag would reach the backend with quotes surrounding it and sometimes not.
=> Fix prune slab edge case

worker/rhpv3.go
This PR <https://github.com/SiaFoundation/renterd/pull/502> increased our download budget because some calls were failing due to the infamous "insufficient budget for bandwidth" error. I believe Chris added padding but for very small files it's not enough.
I added logging with price table details (hit me up if you are interested, there's no hidden or 0H costs that aren't dealt with) but decided to just increase the padding 🤷‍♂️ . We can simplify the expected read cost when the entire network has upgraded to `hostd`, it were pretty arbitrary over-estimates to begin with. Verified that it works on my node. 
This was actually an issue highlighted by the integrity checker also, added logging but hadn't gotten around investigating it more closely.
Fixes #618
=> Insufficient Bandwidth

api/bus.go, api/worker.go, bus/bus.go, bus/client.go, internal/testing/cluster_test.go, stores/multipart.go, stores/sql.go, worker/worker.go
This is a f/u to enable pre-sharding encryption when using the native multipart upload API. The S3 API doesn't support it so it was disabled by default but through the native API we can actually provide an encryption offset.
Also adds some general testing for the native API since we only had testing for multipart uploads through S3.
=> Add support for pre-sharding encryption to native multipart upload

api/bus.go, build/env_default.go, build/env_testnet.go, bus/bus.go, bus/client.go, stores/metadata.go, stores/metadata_test.go, stores/slabbuffer.go, worker/upload.go, worker/worker.go
This PR extends the `UploadPackingSettings` with a new setting called `SlabBufferMaxSizeSoft`. It's essentially a threshold value after which we'll start synchronously uploading packed slabs with every consecutive upload until the buffer size drops this value again. This essentially just "blocks" parallel uploaders for a bit, giving the background loop a chance to catch up and offload some of the slab buffers on to the network.
I decided not to add any compat code for current `renterd`'s out there since having a 0 value essentially reverts to blocking uploads (which we had before). Default value is 4GiB, which is on the low side but fine I think.
=> SlabBufferMaxSizeSoft Setting

build/env_default.go, build/env_testnet.go, internal/testing/cluster.go
Upload packing has been released for a while and worked great so far. Time to not consider it experimental anymore and enable it by default. Advanced users can still disable it if they choose to do their own packing.
=> Enable upload packing by default

worker/migrations.go, worker/upload.go, worker/worker.go
This PR gets rid of `Migrate` in the upload manager and now exposes `UploadShards`. We were using `.Migrate` in places where it doesn't really make sense only because that method allowed uploading shards individually. I also exposed a `lockPriority` that allows prioritising synchronous packed slab uploads as well as deprioritising the asynchronous ones. I decided to bump the lock and default timeout from 5 to 10 minutes to compensate for that. It should get rid of the context deadline exceeded error Nate was seeing, even though that error is not that big of a deal if it's not happening all the time.
=> Upload Priority

api/account.go, bus/accounts.go, bus/bus.go, internal/testing/cluster_test.go, stores/accounts.go, stores/migrations.go
To avoid adding a huge amount of drift to accounts whenever the bus isn't shut down correctly, we mark accounts as not being shut down cleanly and then avoid adding the drift the next time we sync the account.
=> Resync accounts upon unclean shutdown

internal/testing/s3_test.go, s3/backend.go, stores/metadata.go, stores/multipart.go
Fixes
- CopyObject where src == dst
- CopyObject overwrites the destination now
- CompleteMultipartUpload overwrites destination now
- Fixes range in `GetObject`
=> Various S3 fixes to get rclone mount working

.github/workflows/publish.yml
Makes naming of release assets consistent with `hostd`.
To test it I temporarily added this branch to the triggers and verified the release asset names here:
https://github.com/SiaFoundation/renterd/pull/640/checks?sha=1d031557998ad087231e3420ae7e6d114404fe47
`NOTE`: I changed the docker tag suffix from `-testnet` to `-zen` to be more consistent with the naming we use for our release assets, making it inconsistent with `hostd` so maybe we can change it there too
=> Release Assets

stores/metadata.go, stores/metadata_test.go
Noticed some contention in the logs regarding the slab health updates in `UpdateSlab`. 
So I updated the health refresh code to respect the same lock that `UpdateSlab` and `UpdateObject` use.
I also noticed that the `Assign` isn't working in combination with `Take`. So I fixed that as well and added some testing.
=> Reduce lock contention when refreshing slab health

README.md, bus/bus.go, bus/client.go, internal/testing/cluster.go, internal/testing/cluster_test.go
We deprecated these two routes a while ago in favour of `/wallet`, time to remove them. Confirmed with Alex UI is good to go.
=> Deprecate Wallet Routes

stores/migrations.go, stores/sql.go, stores/sql_test.go
I noticed that our Arequipa node was missing a few indices. This PR adds them.
NOTE: Seems like `AddColumn` doesn't create indices so `MigrateColumn` should be used instead.
=> Add missing database indices

api/worker.go, internal/testing/cluster_test.go, worker/client.go, worker/serve.go, worker/worker.go
This fixes an issue observed when mounting files via `rclone`. 
Essentially `rclone` would use the invalid size we return to fire invalid range requests, causing issues with downloads.
=> Fix GetObject returning invalid object size when range is requested

stores/metadata.go
To avoid locking up the database for 60s every 30 seconds.
NOTE: Deployed this on Arequipa and so far there are no more db locks leading to multiple retries.
=> Invalidate slab health in SetContractSet in batches

api/autopilot.go, autopilot/ipfilter.go, worker/rhpv2.go
We are returning `deleted` and `remaining` as num roots instead of num bytes. It should be number of bytes to be consistent with `ContractPrunableData` which returns the amount of prunable data in bytes.
=> fix RHPPruneContractResponse, remove unused type, update ipfilter cache

object/slab.go, object/slab_test.go, worker/download.go, worker/migrations.go
This PR reduces the memory overhead of migrations by reducing the shards we reconstruct before starting the migration upload.
e.g. at 75% health a 10/30 slab is missing 5 shards. With this PR only 16 shards should be held in memory instead of 30.
=> Change Reconstruct to ReconstructSome to only reconstruct missing slabs for migration

api/bus.go, stores/metrics.go, stores/metrics_test.go
This PR implements contract set churn metrics.
Depends on https://github.com/SiaFoundation/renterd/pull/670
=> Metrics: Contract set churn

README.md, api/autopilot.go, autopilot/autopilot.go, autopilot/client.go
We have a `debug` route that allows triggering the autopilot loop. I figured we should probably move it, and make it a regular route, before releasing v1.0. The endpoint will try and trigger the loop, it will get triggered if it was waiting but it won't interrupt an ongoing loop. 
@alexfreska I think it would be cool if the UI would call this endpoint when the user successfully updates the configuration, this would likely improve the first time user experience as we wouldn't have to spend time waiting on the loop.
@peterjan note to self: update postman docs
=> Autopilot Loop Trigger

worker/download.go
Looks like we were always preallocating a full sector when downloading a sector from a host even if we were only interested in a small part of it. When downloading lots of small files like text files this might end up allocating a lot of memory in a short time.
=> Reduce ram used when downloading lots of small files

bus/bus.go, internal/testing/s3_test.go, stores/metadata.go, stores/migrations.go, stores/multipart.go
If a bucket is deleted the leftover multipart uploads should just be deleted as well
=> Fix deletion of bucket failing for empty buckets with registered multipart uploads

autopilot/host_test.go, autopilot/hostscore.go, autopilot/hostscore_test.go
Closes https://github.com/SiaFoundation/renterd/issues/697
This PR shifts the scoring function from a 20% ratio to a 150% ratio. It also becomes more aggressive and will cut off any hosts below a 150% ratio by giving them a score of 0.
=> Update collateral scoring

worker/upload.go
This PR came from a community member copy pasting some logging wrt failed uploads:
```
couldn't upload object: couldn't upload object: failed to upload slab: remaining=3, inflight=7, launched=43 uploaders=45 errors=
d6e647d7: AppendSector: WriteResponse: i/o timeout
43c0e39e: unable to fetch revision with account: LatestRevision: failed to fetch pricetable, err: host price table gouging: {{   } {   cost per TiB exceeds max ul price: ~33.86 SC > ~33.33 SC}}
494f866a: AppendSector: WriteResponse: i/o timeout
557a7150: AppendSector: WriteResponse: i/o timeout
63993ddc: AppendSector: WriteResponse: i/o timeout
78e8e981: AppendSector: ReadResponse: [failed to finalize write program; program finalizer failed; not enough storage remaining to accept sector]
fdc6ce9c: AppendSector: ReadResponse: …
```
=> Fix Upload Overdrive

stores/metadata.go, stores/metadata_test.go, stores/sql.go
Make sure a migration can never corrupt a slab by changing any sector roots or the order of the sectors within a slab.
=> Add sanity check to UpdateSlab to prevent migrations from changing the number or order of shards in a slab

go.mod, go.sum
- Wallet now instructs new users to fund their wallet when there are no transactions yet.
- Hosts last scan column now properly displays unscanned values rather than a very large time ago value.
- The wallet balance tooltip now shows spendable confirmed and unconfirmed values.
- The maxDowntimeHours setting default value is now 336.
- Added support for the minRecentScanFailures autopilot hosts setting.
- Siacoin and number input placeholders now match the suggested value.
- Extremely small siacoin values will now show as hastings by default rather than 0SC.
- Fixed an issue where the wallet balance graph would not show the first data point.
- The autopilot loop is now triggered after settings are successfully updated.
- Files are now paginated.
- Refined the warnings in the files feature …
=> ui: v0.32.0

api/bus.go, api/contract.go, autopilot/autopilot.go, autopilot/contractor.go, bus/bus.go, bus/client/contracts.go, internal/testing/cluster_test.go, stores/hostdb.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go, stores/sql.go
This is the preparation for another PR which adds automatic pruning of contracts to the autopilot if they don't appear on chain.
It adds the following possible states to a contract which get updated by the bus as it receives incoming blocks
- "pending" - default for contracts added to the bus
- "active" - is set as soon a contract appears on chain
- "complete" - is set as soon as the storage proof appears on chain
- "failed" - is set when an active contract doesn't become 'complete' by the end of its proof window
=> Add tracking of on-chain state for contract 

stores/hostdb.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go, stores/slabbuffer.go, stores/sql_test.go
I noticed an issue on our nodes where migrations were seemingly migrating too many shards. After some digging I found out that health was misrepresented. We were migrating 15 sectors on a .75 health slab only because the .75 was wrong. This means we have a bug in our health invalidation but I wasn't able to pinpoint where we're failing to invalidate slabs.
This PR hardens us against that. It does so by changing `health_valid` from a bool to a random timestamp in the future. The validity period is chosen randomly between 12 and 72 hours from the time the health was refreshed. By doing so we effectively avoid having to recalculate the health of all invalidated slabs at once.
I considered using GORM hooks for the invalidation by they have a very weird way of handling associations. When you …
=> Health Invalidation

autopilot/contractor.go, autopilot/hostfilter.go, internal/testing/cluster_test.go
To avoid contracts that don't get confirmed on chain or simply reorged from sticking around, the autopilot will delete them after 18 blocks of being pending which matches hostd's current behaviour.
=> Have autopilot delete unconfirmed, pending contracts after some time

stores/migrations.go, stores/multipart.go
I noticed we have some indices missing:
```
2023-11-06T14:54:34Z	WARN	stores/sql.go:163	missing index	{"table": "dbMultipartUpload", "field": "ObjectID"}
2023-11-06T14:54:34Z	WARN	stores/sql.go:163	missing index	{"table": "dbMultipartUpload", "field": "DBBucketID"}
2023-11-06T14:54:34Z	WARN	stores/sql.go:163	missing index	{"table": "dbMultipartUpload", "field": "MimeType"}
```
After pushing the migration I noticed this migration, which we could duplicate.
I figured being explicit is better but it doesn't really matter I guess.
```
{
ID: "00020_missingIndices",
Migrate: func(tx *gorm.DB) error {
return performMigration00020_missingIndices(tx, logger)
},
},
```
@ChrisSchinnerl  did we manually manipulate that table? It almost seems as if those indices were dropped manually or something... …
=> MultipartUpload indices

api/bus.go, api/params.go, autopilot/contractor.go, bus/bus.go, bus/client/metrics.go, internal/testing/cluster_test.go, stores/metadata.go, stores/metrics.go, stores/metrics_test.go, stores/sql_test.go
This updates the metrics endpoint to be more consistent with the `hostd` endpoint by requiring the client to provide a start time, a number of intervals to fetch as well as the length of an interval.
The updated query attempts to split up all the metrics over a specific timeframe into intervals and returns the first metric per interval if any.
=> Metrics: Update endpoint to use intervals 

go.mod, go.sum
- The configuration now has zen-specific suggested/default values for number of contract hosts and shard values.
- The bucket context menu now allows you to edit the bucket policy and toggle the read access between public and private.
- The simple configuration mode now shows download and upload estimates and pricing.
- Currency display can now be configured to siacoin, fiat, or both along with a preference for when only one can be displayed.
- Fixed an issue with file search where selecting a file would navigate to the path without the bucket.
- The configuration now includes a setting for a migration surcharge multiplier which allows you to set a factor for increasing the max download price when trying to repair critically low health sectors.
- The contract count shown in onboarding …
=> ui: v0.33.0

autopilot/autopilot.go
This PR blocks until the autopilot is funded. This usually only happens once, because we strict compare against 0H, but is important for FTUE. If you aren't immediately requesting funds from the faucet, you might have synced both the wallet and consensus, leaving you in a situation where you have to wait for the next iteration of the autopilot loop to have it form contracts (which is 30' worst case by default).
=> Block Until Funded

api/setting.go, cmd/renterd/main.go, internal/testing/cluster.go, internal/testing/s3_test.go, stores/metadata_test.go
I think something might've gotten mixed up when we added s3 key requirements. AccessKeyIDs [should be between 16-128](https://docs.aws.amazon.com/IAM/latest/APIReference/API_AccessKey.html) characters (and are usually 20 in AWS S3) and secret keys are always 40. I'm assuming that's where the 40 came from so I added that assertion and updated the access key id assertions.
=> S3 AuthenticationSettings validation

api/multipart.go, api/setting.go, api/slab.go, bus/bus.go, bus/client/multipart-upload.go, bus/client/slabs.go, internal/testing/cluster_test.go, object/object.go, object/slab.go, stores/metadata.go, stores/metadata_test.go, stores/multipart.go, stores/multipart_test.go, stores/slabbuffer.go, worker/download.go, worker/upload.go, worker/worker.go
This PR uses an update instead of create now when completing a multipart upload. 
That's possible now since we recently added the `object_index` to the slices and we no longer rely on the ID for the insertion order.
This also gets rid of the separate `PartialSlabs` field in the `object.Object` since workers won't be able to deduct the right download order. Instead partial slabs are now part of the regular slabs but without any slices.
Closes https://github.com/SiaFoundation/renterd/issues/769
=> Use update instead of CreateInBatches in CompleteMultipartUpload

stores/metadata.go, stores/metadata_test.go
This prunable data query is rather slow because we have to `LEFT JOIN contract_sectors`. We need that because we want to include contracts without sectors too. I figured in this case it makes sense to split one query into two: one where we use `WHERE NOT EXISTS` to catch everything we would miss out on if we were to `INNER JOIN`.
In the contract size query (so fetching size details for a single contract) I kept the `LEFT JOIN` since it's bound by the `fcid` anyway. I considered getting rid of it all together because we only use it in the worker to escape early. We could also return a custom error and return a 400 when the user supplies a contract to prune but there's no sectors to prune. This would remove a `bus` route though (`/contract/:id/size`) and I wasn't sure whether that was a …
=> Optimise Contract Sizes

worker/alerts.go, worker/download.go, worker/upload.go, worker/worker.go
This PR adds alerts for both upload and download failures. 
An open question is how to handle migration related up - and download failures. I haven't added those yet since those errors already bubble up through migration failure alerts. What's unfortunate though is that we lose some context by having the autopilot register those.
=> Upload & Download Failure Alerts

api/worker.go, worker/client/rhp.go, worker/worker.go
With 1.0 coming we should probably just get rid of these routes to avoid having to mark them as deprecated in 1.1.
=> Remove Registry Endpoints

autopilot/autopilot.go
Scheduling a trigger when the wallet receives its first deposit makes things really smooth on first setup - so I vote we merge something like this. It essentially replaces `blockUntilFunded` which I had to remove because we can't block for other reasons (host infos). I should not have removed it but instead replaced it with a trigger. This PR does that.
edit: I don't think it's worth adding a test, it's very NDF prone, I verified it manually
=> Schedule Trigger When Funded

.golangci.yml, api/autopilot.go, api/state.go, api/worker.go, build/meta.go, cmd/renterd/main.go, config/config.go
Add tagliatelle linter to the golangci-lint configuration to make sure our struct tags follow the goCamel naming convention.
=> Add Tag Linting

wallet/wallet.go
wallet.SiacoinElement values are returned by some endpoints but the type did not have struct tags.  This fixes that so the encoded output conforms to our standards.  I searched the code for other instances of structs with an ID field having no tags and the only other instance I found was AutopilotConfig in internal/node/node.go, but this doesn't matter because that type isn't marshaled/unmarshaled anywhere.
=> Fix Struct Without JSON Tags

api/wallet.go, api/worker.go, autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostfilter_test.go, autopilot/workerpool.go, bus/bus.go, bus/client/wallet.go, go.mod, go.sum, stores/metadata.go, worker/client/rhp.go, worker/download.go, worker/rhpv3.go, worker/worker.go
That way we can do so after locking the contract to avoid exceeding the max collateral when uploading at the same time.
As a side - effect, since we only pass a pricetable to `RPCRenew`, we also use rhpv3 estimates now.
=> Compute new collateral for renewals in worker instead of the autopilot

worker/contract_lock.go, worker/download.go, worker/host.go, worker/memory.go, worker/net.go, worker/rhpv2.go, worker/rhpv3.go, worker/upload.go, worker/uploader.go, worker/worker.go
I decided to open this PR because I was at a point where I made a few small changes and everything still compiled... I figured I might as well get this merged already to have a nicer diff in consecutive PRs where I'll try and unit test the upload manager. 
The nice thing about these changes is that the upload and download managers are initialised in the same way, with all of their dependencies being nice clean interfaces. This PR adds a (temporary) interface called the `ObjectStore`. It's temporary because I might split it off into more granular interfaces down the road.
Next step is to mock the `Host`, `HostManager`, `MemoryManager` and `ObjectStore` which allow us to unit test both uploads and downloads.
=> Worker Cleanup

docker/Dockerfile, docker/entrypoint.sh, stores/migrations.go, stores/sql.go
Seems like Debian ships with an old version of SQLite which didn't have `ALTER TABLE foo DROP COLUMN` yet.
So it's trying to copy the table and drop it. This PR fixes that.
It's also migrating our image to alpine to get a more recent version of sqlite.
=> Fix migration 35 failing due to foreign key constraint

api/contract.go, autopilot/contractor.go, autopilot/hostfilter.go, cmd/renterd/main.go, worker/host.go, worker/rhpv3.go
When refreshing a contract that is not below the collateral threshold we no longer enforce a minimum new collateral. 
Also when refreshing a contract that isn't out of funds, we don't increase the funds we put in the refreshed contract.
Also fixes a panic when we renew/refresh without a valid price table
=> Fix panic on refresh and minCollateral calculation

autopilot/autopilot.go, autopilot/contractor.go, bus/bus.go, bus/client/wallet.go, wallet/wallet.go, wallet/wallet_test.go
This PR changes 2 things.
1. funding a transaction will use the largest outputs first
2. redistribution happens in batches to avoid creating huge transactions
=> Redistribute wallet in batches

worker/download.go
This PR fixes the following panic:
```
2023-12-18T20:15:19.113550941Z panic: runtime error: index out of range [0] with length 0
2023-12-18T20:15:19.113658636Z 
2023-12-18T20:15:19.113682316Z goroutine 11993312 [running]:
2023-12-18T20:15:19.113700056Z go.sia.tech/renterd/worker.(*slabDownload).nextRequest(0xc0090d40e0, {0x16e1860?, 0xc00cb00ff0}, 0xc01039a090, 0x1)
2023-12-18T20:15:19.113716001Z     /renterd/worker/download.go:939 +0x385
2023-12-18T20:15:19.113732441Z go.sia.tech/renterd/worker.(*slabDownload).overdrive.func5()
2023-12-18T20:15:19.113749406Z     /renterd/worker/download.go:896 +0x110
2023-12-18T20:15:19.113765726Z created by go.sia.tech/renterd/worker.(*slabDownload).overdrive in goroutine 11993056
2023-12-18T20:15:19.113796558Z     /renterd/worker/download.go:888 +0x1eb …
```
=> Download panic

autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostfilter_test.go
Arequipa kept refreshing a specific contract in a loop because the autopilot considered the contract out-of-collateral but just before refreshing the contract we didn't. So we didn't enforce a minimum on the collateral expected to be in the contract after the refresh.
To fix this I changed the `isOutOfCollateral` check to be more in line with `isOutOfFunds` one. Instead of looking at a theoretical amount of funding the contract might have after a refresh, we use the remaining funds in a contract to determine how much storage it is still good for and then expect the amount of remaining collateral to cover 5% of that storage.
Only when we refresh the contract, we use the new `renterFunds` to determine the `minNewCollateral` since increasing the `renterFunds` might push a contract over the …
=> Fix out-of-collateral algorithm

api/object.go, internal/testing/cluster_test.go, stores/metadata.go
Added due to https://github.com/SiaFoundation/renterd/issues/834
cc @alexfreska
=> Extend /objects/stats response with `numUnfinishedObjects` and `totalUnfinishedObjectsSize`

api/contract.go, autopilot/accounts.go, autopilot/autopilot.go, autopilot/contract_pruning.go, autopilot/contractor.go, bus/bus.go, bus/client/contracts.go, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/pruning_test.go, internal/testing/uploads_test.go, stores/metadata.go, stores/metadata_test.go, worker/upload.go, worker/worker.go
This also allows us to deprecate the existing endpoint for fetching all contracts of a set
Related to https://github.com/SiaFoundation/renterd/issues/716#issuecomment-1858244940
=> Add option to filter /contracts endpoint by contract set and return sets in contract metadata

bus/bus.go, bus/client/contracts.go, internal/testing/blocklist_test.go, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/gouging_test.go, stores/metadata.go, stores/metadata_test.go
Since it has a subset of the functionality of `/contracts`
=> Remove /bus/contracts/sets/:set endpoint

autopilot/autopilot.go
There is no reason to defer a cancel in the autopilot loop. This is actual a big issue because we pass these contexts to goroutines and then go on to cancel them.
=> Stop using a context with deferred cancel in the autopilot loop

cmd/renterd/main.go
Updates main.go to match `hostd` by making use of the `build` package. The resulting logging looks like this 
```bash
2023-12-21T18:03:39+01:00	INFO	renterd/main.go:398	renterd	{"version": "v0.7.1-45-gf1febab2", "network": "Mainnet", "commit": "f1febab2", "buildDate": "2023-12-21T16:10:27+01:00"}
```
and
```bash
Commit: f1febab2
Build Date: 2023-12-21 16:10:27 +0100 CET
```
=> Make use of go generated commit and version

worker/rhpv3.go
Cerlancism reported the following errors. These can only by caused if the renter thinks its synced, but in reality it's not. This happens on the testnet sometimes when a lot of blocks are mined in short succession. We already have an "ignore-list" for errors after which we try contract payment, so I figured we best add this one too. I also increased the withdrawal expiry since we really don't use that for anything. The withdrawal message just has to have a sane expiry.
```
075c746d: unable to fetch revision with account: LatestRevision: failed to fetch pricetable, err: PriceTable: couldn't read RPCPriceTableResponse: ReadResponse: failed to process payment: failed to process account payment: withdrawal request expired
84956180: unable to fetch revision with account: LatestRevision: failed …
```
=> Increase withdrawal expiry

stores/slabbuffer.go, stores/slabbuffer_test.go
This caused buffers to be closed multiple times which led to rare error messages in the logs
=> Fix same buffer being in 'completedBuffers' multiple times

bus/client/client_test.go, cmd/renterd/main.go, internal/node/node.go, internal/testing/cluster.go, internal/testing/pruning_test.go, stores/metadata.go, stores/metadata_test.go, stores/multipart.go, stores/sql.go, stores/sql_test.go
Pruning slabs is quite a slow operation so this PR does 2 things.
1. Slightly improves the queries by reducing the nesting
2. Keep a background loop for pruning slabs which instead of pruning in a synchronous way is either triggered to prune or prunes every hour. It also comes with a 30s cooldown to better batch slab pruning
This is not a huge change but it makes quite the difference for nodes on slower disks with lots of files trying to override existing objects. When lots of objects are added at the same time I have seen my node spend a minute on a single query.
=> Prune slabs periodically

stores/sql.go, stores/sql_test.go
This fixes an issue where startup would fail due to missing tables. Using `DELETE`, we make sure the reset operation is atomic.
=> Change ResetConsensusSubscription to delete from tables instead of dropping them

cmd/renterd/main.go
For a first time user it might not be obvious that configuring `renterd` via a config file is possible. This PR updates the usage info of `renterd` to inform users about that option and makes sure a config file is always created for the user to modify instead of relying on them creating it.
=> More verbose usage information for CLI

worker/serve.go
We seem to be running into an edge case where `DownloadObject` is stuck forever since writing to the `io.PipeWriter` never finishes. 
Looking at `serveContent` we never seemed to close the corresponding reader in case `serveContent` exits without reading all the data from it.
=> Close pipeReader at the end of serveContent

README.md, api/autopilot.go, autopilot/contractor.go, autopilot/hostscore_test.go, go.mod, go.sum, internal/testing/host.go, stores/autopilot_test.go, wallet/wallet.go
So far we've created 1 output per contract we want to form as part of the contract maintenance. That works but is not optimal since a large node with 200 outputs will frequently run into transactions which are too large for the transaction pool when trying to send a greater amount of Siacoins. 
Now that we spend unconfirmed outputs when forming contracts, we can get away with fewer outputs. So this PR sets that number to 10 outputs and allows the wallet to grow up to 30 before starting to defrag the outputs the same way `hostd` defragments outputs.
=> Defrag wallet implicitly and reduce wallet maintenance to 10 outputs

worker/download.go, worker/downloader.go
Pushing this separately since it clears up another PR I'm working on. There's no code changes here, I'm merely separating the `downloader` into its own file (same as we do the `uploader`) and I'm getting rid of download ids, which are a debug leftover.
=> Cleanup download.go and remove debug code

api/worker.go, internal/testing/cluster.go, internal/testing/host.go, worker/rhpv3.go
stumbled into `RPCReadRegistry` while reading and figured we might as well remove the last remaining (unused) code revolving the registry
=> Remove unused registry code

worker/rhpv2.go
This gets rid of the panic but I'm not sure when the returned proof is off. I added some extra context to the error.
Fixes #897
=> Sanity check VerifySectorRangeProof input to avoid a panic

worker/host.go
With this change I hope to get rid of the following error in the log. It does not happen a lot and it happens for the same host, causing me to believe it's simply due to the host being slow and connecting to it taking longer than whatever leeway we put on the price table validity.
```
{"level":"error","date":"2024-01-13T03:39:48Z","component":"autopilot.accounts","msg":"failed to fund account: couldn't fund account: failed to fund account with ~500.8 mS;FundAccount: ReadResponse: failed to read price table: no price table found\n","accountID":"ed25519:614c0fa737b04dc447d39c489c8911a9bfc614ec86897d90f0053c9be152cd3f","hostKey":"ed25519:fba406818f558676e117323f45665f3affbb10bb025f74548fafe66df0dd5274","balance":"499218792671999618136517","expected":"1 SC"}
```
Fixes #801
=> Make sure we use a valid price table when funding an account

api/metrics.go, bus/bus.go, internal/testing/cluster_test.go, stores/metrics.go
This PR updates the metrics query to use a recursive query for recomputing the periods and then joining the metrics with the periods.
That has the advantage of getting rid of the integer rounding and casting we do right now to determine the period for each metric. Instead periods are essentially precomputed and metrics are then matched to periods.
=> Improve metrics queries

worker/host.go, worker/host_test.go, worker/migrations.go, worker/mocks_test.go, worker/pricetables_test.go, worker/rhpv3.go, worker/upload.go, worker/upload_test.go, worker/uploader.go, worker/worker.go
This PR uses the host's block height to set the expiry on the withdrawal message. Nate noticed a renter spamming the host with expired withdrawal messages, I think this was caused by a bug in `refreshUploaders` so I added a unit test for it in this PR.
=> use the host's block height when setting an expiry on EA withdrawal messages

worker/download.go, worker/host.go, worker/interactions.go, worker/spending.go, worker/upload.go, worker/worker.go
This PR slightly improves how we handle host interactions on worker shutdown by swapping out the flush context with the context we pass to the worker on shutdown, essentially allowing interactions to be flushed for as long as we allow the worker to shut down gracefully. On shutdown we also set the interval to 0 essentially immediately flushing the interactions to the bus. Both these changes ensure that all interactions that occur during a worker shutdown have every chance of making it into the database.
=> improve shutdown of host interaction recorders

worker/worker.go
I noticed that most of the churn on Arequipa comes from host being offline while other nodes report they are not. To rule out scans being fragile this PR scans twice if necessary.
Ran this on Arequipa and immediately after startup I'm seeing `renterd-arequipa  | 2024-02-09T13:49:43Z	INFO	worker.worker	worker/worker.go:1430	successfully scanned host ed25519:ec7389996f3cf39fe5073b82d98c65145936863082d6af16a307a6180b750cfc after retry` so it seems like it's making things a bit more robust.
=> Scan twice before recording a failed scan

worker/host.go, worker/interactions.go, worker/worker.go
```go
2024-02-13T21:48:42.216288715Z panic: no interaction recorder attached to the context
2024-02-13T21:48:42.216340814Z 
2024-02-13T21:48:42.216344851Z goroutine 2280 [running]:
2024-02-13T21:48:42.216348238Z go.sia.tech/renterd/worker.HostInteractionRecorderFromContext(...)
2024-02-13T21:48:42.216351103Z     /renterd/worker/interactions.go:48
2024-02-13T21:48:42.216354429Z go.sia.tech/renterd/worker.(*host).FetchPriceTable.func1.1({0x1a408e8, 0xc003dbec40}, 0xc20ff046e0?)
2024-02-13T21:48:42.216357465Z     /renterd/worker/host.go:199 +0x305
2024-02-13T21:48:42.216360621Z go.sia.tech/renterd/worker.(*transportPoolV3).withTransportV3(0xc000a7f2f0, {0x1a408e8, 0xc003dbec40}, {0x3c, 0x51, 0x24, 0x5a, 0x69, 0xb4, 0x87, ...}, ...)
2024-02-13T21:48:42.216363567Z …
```
=> Remove context value interaction recorder

stores/migrations.go, stores/migrations/mysql/main/migration_00003_peer_store.sql, stores/migrations/mysql/main/schema.sql, stores/migrations/sqlite/main/migration_00003_peer_store.sql, stores/migrations/sqlite/main/schema.sql, stores/peers.go, stores/peers_test.go, stores/sql.go
This PR has our `SQLStore` implement the `syncer.PeerStore` in preparation of switching out our `SingleAddressWallet` for the one in `coreutils`. It has a unit test to cover SQLite and I ran the migration on a MySQL node, other than that it was not tested.
=> add SQL impl. for syncer.PeerStore

api/setting.go, worker/gouging.go
I discovered something quite nasty on my node, where I had a couple of critical downloads that were failing to migrate because we were applying the "MigrationSurchargeMultiplier" over and over again to the `MaxDownloadPrice`, eventually causing an overflow.
```
9e5bd369: failed to apply surcharge multiplier of 10 to 60.3 TS, overflow detected
DEBUG PJ: setting adjust max dl price 6.03 KS
DEBUG PJ: setting adjust max dl price 60.3 KS
...
DEBUG PJ: setting adjust max dl price 603 GS
DEBUG PJ: setting adjust max dl price 6.03 TS
DEBUG PJ: setting adjust max dl price 60.3 TS
```
Since that is the worst thing to happen to a critical migration I figured it'd be best to a) extend the gouging settings validation to ensure a user never enters a combination that overflows and b) stop preventing a …
=> Ensure applying the MigrationSurchargeMultiplier never prevents a download

worker/downloader.go, worker/downloader_test.go, worker/uploader.go, worker/uploader_test.go
To avoid a potential deadlock where we never receive a response since the request gets queued but not processed
=> Fail upload/download request if uploader/downloader was already stopped

stores/metadata_test.go, stores/types.go
This adds a new `bCurrency` type which will eventually replace `currency` and the 2 field currency we use right now.
It's nicer because it requires only a single column and can still be used for comparisons or sorting if we ever need that.
The reason it was added now is because we are migrating the wallet db pretty soon anyway so we can make use of this type instead of keeping the old one.
=> New binary currency type for SQL

alerts/alerts.go, bus/bus.go, bus/client/alerts.go, internal/testing/cluster_test.go
Closes https://github.com/SiaFoundation/renterd/issues/957
=> Add pagination to alerts endpoint and add another endpoint to dismiss all alerts at once

bus/bus.go, bus/client/alerts.go, worker/downloader_test.go
When writing the docs I had a slight change of heart. This PR merges the dismiss routes and makes "all" a query param.
=> Merge alert dismiss routes

autopilot/alerts.go, autopilot/contractor.go
This PR adds host info to the contract set change alert, as requested in #963
**REQUIRES UI CHANGE**
This PR requires an accompanying UI change to ensure the alert is displayed properly. I'm wondering whether we should create a list of alerts + properties in the frontend, and only display those keys and alerts. That way we could always maintain backwards compatibility in the backend, but tweak or add alerts. We can merge that separately from the frontend and then when the frontend made the required changes we can get rid of the redundant/old compat code we had to add. Downside would be that every new alert or added property would need a UI update to get displayed.
**Example screenshot:**
**Example JSON:**
```json
{
"id": "h:f27b88af9f84c7b51121b902d91c7ec5b0d557470f6f9a9b871c333101b1bace", …
```
=> Extend contract set change alerts with host info

stores/migrations.go, stores/migrations/mysql/main/schema.sql, stores/migrations/sqlite/main/schema.sql, stores/migrations_metrics.go, stores/migrations_utils.go
Recently had to add a metric migration and found that we don't properly build the path in `performMigration`, it always uses `main`:
```go
// build path
var path string
if isSQLite(db) {
path = fmt.Sprintf("migrations/sqlite/main/migration_" + name + ".sql")
} else {
path = fmt.Sprintf("migrations/mysql/main/migration_" + name + ".sql")
}
```
Tested it with a dummy metrics/main migration on my MySQL node.
=> Fix wrong path in metric migration

api/multipart.go, api/object.go, bus/bus.go, bus/client/multipart-upload.go, internal/testing/cluster_test.go, s3/backend.go, worker/worker.go
That way a client doesn't need to generate a key themselves. 
This PR also gets rid of the `disablePreshardingEncryption` flag and instead looks at the encryption key to determine whether encryption is enabled and an offset is necessary. This should offer better protection against misusing the multipart upload API. For everyone already using it correctly, this change is backwards compatible.
=> Add `generateKey` flag to multipart create endpoint

internal/testing/cluster_test.go, stores/metadata.go, stores/metadata_test.go
Testing the latest change to the object stats on my HDD node, I realised how slow the operation is. 
This changes gets Arequipa to <1s response time.
=> Improve performance of objects stats

worker/host.go, worker/interactions.go, worker/worker.go
One issue we have right now is that a host might get scanned over and over until the worker flushes its buffer of scan results to the bus. Which made me think that we should probably try to get rid of the buffering altogether now that we no longer have 80k hosts we need to scan on every new node.
Running this right now on my own node for testing. In the meantime it's ready for review.
=> Remove host interaction recorder from worker

worker/rhpv3.go
This PR gets rid of `shutdownCtx` usage in the accounts and adds a `withAccountLock` helper. 
(Just pulling this out of #882  to try and get that merged.)
=> Stop using the worker's shutdown context for unlocking accounts

alerts/alerts.go, bus/bus.go, bus/client/alerts.go, internal/testing/cluster_test.go
This gets rid of dismiss "all" again to avoid a race condition where a user may dismiss alerts they haven't had a chance to read yet and adds pagination to get alerts endpoint.
=> Change response type for paginated alerts request

alerts/alerts.go, autopilot/alerts.go, autopilot/churn.go, autopilot/contractor.go, bus/bus.go, bus/client/alerts.go, internal/testing/cluster_test.go
This is done by introducing an accumulator which is reset every time the alert was dismissed by the user.
Depends on https://github.com/SiaFoundation/renterd/pull/987
=> Accumulate churn information into single alert instead of registering multiple

object/object.go, object/slab.go, worker/bench_test.go, worker/download.go, worker/host.go, worker/host_test.go, worker/mocks_test.go, worker/rhpv3.go, worker/upload.go, worker/upload_utils.go, worker/uploader.go
This PR aims to identify the theoretical max throughput of an `uploader` that is not constraint by the network or memory.
It also applies a few changes to bottlenecks encountered during benchmarking.
=> Add upload benchmark for uploader with mocked hosts

bus/bus.go, stores/metadata.go, stores/metadata_test.go, worker/download.go
Right now we print a lot of "successfully marked sector as lost" regardless of whether the host was actually supposed to have that sector or not. e.g. a contract with a host might have expired and the host doesn't need to have a sector but we still log this message, confusing the operator of the node.
This PR moves the log line to the bus to make sure we only print it when there was actually an associated contract in the db for a given contract.
=> Only log lost sectors if sector was part of an active contract

alerts/alerts.go, bus/bus.go, bus/client/alerts.go, internal/testing/cluster_test.go
Related to https://github.com/SiaFoundation/renterd/issues/1001
cc @alexfreska
=> Allow for filtering paginated alerts by severity

stores/metrics.go, stores/metrics_test.go, stores/migrations/mysql/metrics/migration_00001_idx_contracts_fcid_timestamp.sql, stores/migrations/mysql/metrics/schema.sql, stores/migrations/sqlite/metrics/migration_00001_idx_contracts_fcid_timestamp.sql, stores/migrations/sqlite/metrics/schema.sql, stores/migrations_metrics.go
After doing some manual testing on Arequipa with about 34 million recorded contract metrics, I noticed that using multiple simpler queries (one select per contract per period) is a lot faster when combined with a composite index than a single more complex query.
This PR reduces the time it takes to display the contracts graph from about 25s down to <1s on the current set of data.
Combined with the granularity change of only recording one metric per contract every 5 minutes, a large host like Arequipa should only produce around 30 million rows a year.
=> Improve `findAggregateContractMetric` performance and introduce 30 second granularity for contract metrics

stores/metadata.go
`RefreshHealth` often failed on Arequipa as soon as `slabs` was updated. It immediately returned a `database is locked` error. It also happened only while migrating which explains the deadlock since migrations also update the `slabs`.
To avoid that, this PR changes the slab update to happen in a single query. That way `SQLite` knows that the transaction is a write transaction right away and doesn't start out  as a read transaction that is then aborted.
Another small change I'm testing, since I'd like to avoid creating the temporary table after updating the slabs, is a new query for updating the objects which doesn't depend on the temporary table. The upside of this query is that it updates any object which is out-of-sync with its slabs rather than just the ones modified. However it will …
=> Fix lock contention in RefreshHealth

autopilot/autopilot.go
Running tests locally a bunch I found the autopilot logs have a bunch of unnecessary noise because we run the autopilot loop after it's been shut down.
=> Reduce logger noise

stores/metadata.go, stores/metadata_test.go
I noticed on our integrity node an object wasn't properly getting its health refreshed. After digging in a bit I found we are currently setting the health of an object to be the `MIN` slab health across _all_ objects. Arequipa has a good example, currently all files are at 50% health... I have yet to performance test this change, I know the change that essentially broke the query was performance oriented, so perhaps we should/could deploy this on arequipa and see the effect it has there. I added a unit test for `RefreshHealth` too.
=> Update refresh health query

stores/multipart.go
By optimistically deleting multipart uploads we avoid starting out with a read-ten that then fails to upgrade to a write txn while the db is busy with other tasks.
=> Improve locking for deleting multipart uploads in parallel

stores/subscriber.go, stores/types.go, stores/wallet.go
This PR implements the interfaces necessary to process chain updates. I introduce the `db` types here, migrations come later.
=> implement wallet.ApplyTx and wallet.RevertTx

api/host.go, api/worker.go, autopilot/contractor.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, worker/worker.go
Previously we didn't log failed host scans but this PR changes it so that we ignore certain errors but log the remaining ones. That should reveal any unexpected errors. 
e.g. quite a few scans fail due to the key handshake failing which seems to be mostly related to hosts reannouncing themselves with a new key as part of upgrading from `siad` to `hostd`.
This PR also adds a minor functional changes which is moving the `timeout` into the `scanHost` method to reapply the full timeout on the second scan.
=> Improve logging for failed host scans

stores/metadata_test.go, stores/migrations.go, stores/migrations/mysql/main/migration_00005_zero_size_object_health.sql, stores/migrations/sqlite/main/migration_00005_zero_size_object_health.sql
Closes https://github.com/SiaFoundation/renterd/issues/1036
Due to a bug in `refreshHealth` which is fixed now, 0-byte objects which were created by the UI as folders had a health != 1.
This PR fixes that and extends testing to make sure `RefreshHealth` doesn't update 0-byte files anymore.
=> Fix "folder health misinterpreted"

bus/bus.go, internal/test/e2e/cluster_test.go
I encountered the following error on my node:
```
2024-03-06T08:46:30Z    ERROR   autopilot       autopilot/autopilot.go:266      wallet maintenance failed, err: failed to redistribute wallet into 3 outputs of amount ~3.333 KS, balance ~14.56 KS, err couldn't broadcast the transaction: transaction set is empty
```
It happens because we don't properly return early if there's nothing to be redistributed and instead go and broadcast an empty txn set.
=> Prevent broadcast of empty txn set in WalletRedistribute

autopilot/accounts.go
The account refill alert is too spammy and most of the time doesn't require action by the renter. This reduces the alert frequency so that only actionable errors are alerted.
=> Reduce occurences of account refill alert

api/object.go, internal/test/e2e/metadata_test.go, internal/test/e2e/s3_test.go, object/object.go, s3/backend.go, s3/s3.go, stores/metadata.go, stores/metadata_test.go, stores/multipart.go, stores/sql_test.go, worker/client/client.go, worker/upload.go, worker/worker.go
- refactor database code to reduce deadlocks + add test for triggering deadlocks
- turn ETag into md5 hash and set it on objects in `backend.go` 
- Fix ListObjects not returning etag or modtime
=> Various `rclone` related fixes/improvements

.github/workflows/project-add.yml
This will add all `renterd` issues and prs to the project board.
This is a workaround for the super low "project-add" workflow limit in the project's workflow menu.
=> Add workflow to automatically add issues and prs to project board

.golangci.yml
Keep getting `WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.` but it seems like we already have `unused` so I'm removing `deadcode`
=> Remove deadcode linter

internal/test/e2e/s3_test.go, s3/backend.go
This PR fixes an issue with markers not reflecting the name of the objects when returned through the S3 API. We trim the leading slash from objects but not from markers. This causes tools like rclone to fail at pagination.
=> Fix markers in S3 API

.github/workflows/test.yml, .golangci.yml, api/host.go, api/object.go, api/param.go, api/setting.go, autopilot/hosts.go, bus/client/metrics.go, bus/client/slabs.go, bus/client/wallet.go, cmd/renterd/config.go, cmd/renterd/main.go, hostdb/hostdb.go, internal/test/e2e/cluster_test.go, stores/metadata_test.go, worker/client/client.go, worker/mocks_test.go, worker/rhpv2.go, worker/rhpv3.go, worker/worker.go
I believe `golangci` upgraded to `1.57.0` and it's giving us a bunch of lint errors. I wanted to tackle most of them and disable some others but it turns out you can't mix and match `enabled-checks` and `disabled-checks`. 
I ended up:
- enabling diagnostic preset
- enabling style preset
- disable `ifElseChain`
- disable  `exitAfterDefer`
edit:
- disabling all the things
I pretty much made sure not to disable something we previously had enabled, and I enabled one or two options that I think make sense. Like `deferInLoop` for example. Here is the list of options: https://go-critic.com/overview#checks-overview
=> Update `gocritic` enabled/disabled checks to fix linter

README.md, api/setting.go, autopilot/autopilot.go, autopilot/hostscore.go, build/env_default.go, build/env_testnet.go, internal/test/config.go, worker/gouging.go
By removing the `MinMaxCollateral` from the gouging checks, we stop avoiding interactions with hosts that are only considered to be gouging due to their collateral settings.
That means we only care about the `MaxCollateral` setting in the scoring algorithm. The result is that a host with insufficient `MaxCollateral` will be dropped from the contract set due to bad score if enough hosts with a good score exist.
=> Remove redundant `MaxCollateral` from gouging checks

autopilot/alerts.go, autopilot/autopilot.go, autopilot/migrator.go, internal/test/e2e/migrations_test.go
=> Extend migration failure alerts with affected objects

internal/test/e2e/s3_test.go, worker/client/client.go
A result of moving to a HEAD request which doesn't have a body and requires checking the status code.
=> Fix S3 HeadObject endpoint not correctly checking 404

worker/worker.go
Closes https://github.com/SiaFoundation/renterd/issues/1088
Updates `scanHost` to be a bit more generous with the timeout and apply it to each step of the scanning process. That way, if resolving the IP address took 3 seconds and fetching the settings takes 4 we won't fail the scan if fetching the price table takes another 4 seconds.
We also log both errors now when a scan fails twice.
=> Update logging in scanHost and apply timeout to each step of the scanning progress

worker/migrations.go, worker/mocks_test.go, worker/upload.go, worker/upload_test.go, worker/worker.go
That way we avoid adding a `contractSector` for a migrated slab that we just deleted because the sector wasn't found
=> When migrating a slab, only set contracts for new shards

bus/bus.go, bus/uploadingsectors.go, bus/uploadingsectors_test.go
This PR is a result of investigating a lost sector alert on my node. I realised that we sometimes mistakenly prune sectors from recently renewed contracts, which then leads to those sectors being reported lost on downloads. This happens because the sectors cache in the bus doesn't properly take into account renewals, this PR fixes that by moving sectors from the old contract into the new contract and by mapping every incoming fcid to the latest fcid. Thereby ensuring that all sectors end up linked to the renewed contract at all times.
=> Properly handle contract renewals in the sectors cache

api/host.go, autopilot/autopilot.go, autopilot/autopilot_test.go, autopilot/contractor.go, autopilot/host_test.go, autopilot/hostfilter.go, autopilot/hosts_test.go, autopilot/hostscore.go, autopilot/hostscore_test.go, autopilot/scanner.go, autopilot/scanner_test.go, autopilot/workerpool.go, bus/bus.go, bus/client/hosts.go, hostdb/hostdb.go, internal/test/e2e/cluster_test.go, internal/test/e2e/pruning_test.go, stores/hostdb.go, stores/hostdb_test.go, worker/client/rhp.go, worker/host.go, worker/host_test.go, worker/interactions.go, worker/mocks_test.go, worker/pricetables.go, worker/pricetables_test.go, worker/rhpv3.go, worker/worker.go
We currently have two `Host` types. One in the `hostdb` package and one in the `api` package. Merging these removes unnecessary nesting and cleans up our API interfaces since we should exclusively return types from the `api` package. The `hostdb` package is now left with announcements stuff, which will be removed by `its-happening` after which we can remove the `hostdb` package entirely.
=> Merge host types

internal/node/transactionpool.go, internal/node/transactionpool_test.go
`UnconfirmedParents` would only ever return direct parents for a txn but not grandparents and so on. Leading to hosts not knowing about certain parents yet and txns failing.
=> Fix "transaction spends nonexisting siacoin output" when refreshing contracts

cmd/renterd/main.go, config/config.go, docker/entrypoint.sh
Both already exist in `hostd` and are nice UX improvements.
=> Add --env cli flag and --openui

.github/workflows/ui.yml
- Use the ui update composite action from shared workflows
- The shared action has refinements to the behaviour:
- Opens new PR branch per version
- Only opens a PR if the specific UI module was updated
=> ci: use shared ui update action

.github/workflows/publish.yml, .github/workflows/test.yml
To fix:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-go@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> Update deprecated GitHub actions

.github/workflows/ui.yml
- When the UI action that builds Go modules completes it will call a repo dispatch
=> ci: remove polling for repo dispatch

stores/metadata.go, stores/metadata_test.go, stores/multipart.go, stores/sql.go
This speeds up deletions and avoids redundant deletions in scenarios where files get deleted rapidly. e.g. when running `rclone sync` which might replace lots of files one-by-one.
It also puts the pruning of slabs into a background goroutine. There is no reason for an object deletion to fail when pruning slabs fails. This might lead to brief inconsistencies on the object stats endpoint but will greatly improve the speed at which we can delete objects and also reduce the database locking necessary when pruning slabs.
Closes https://github.com/SiaFoundation/renterd/issues/1149
=> Batch pruning of slabs after deleting objects from the database

internal/test/e2e/cluster.go, worker/upload.go
@freopen noticed that partial slabs weren't uploading before the limit was reached anymore and [debugged it](https://github.com/SiaFoundation/renterd/commit/716091ba82e81dfe74449e926b2386fd445d2128#r140736503)
That's a very good catch thanks for reporting! This PR should take care of the issue.
=> Move threadedUploadPackedSlabs out of bufferSizeLimitReached

stores/sql.go, stores/sql_test.go
Because we loop over our retry intervals and sleep at the end of the loop we actually don't retry after the last configured interval. We just sleep and then return the error. This PR fixes that and adds a test to assert we log every attempt properly.
=> Ensure retryTransaction retries after every retry interval

stores/metadata.go, stores/metadata_test.go
`fetchUsedContracts` would sometimes be missing a entry for contracts that were renewed mid upload, in those cases it was possible for the output to contain an entry for the `renewedFrom` file contract id and not the current id
=> Ensure fetchUsedContracts can deal with renewed contracts properly

internal/test/e2e/cluster.go
Running tests locally now spam "record not found" warnings.
```
2024/04/16 12:20:49 /Users/peterjan/code/siafoundation/renterd/stores/peers.go:192 record not found
[0.154ms] [rows:0] SELECT * FROM `syncer_bans` WHERE net_cidr IN ("127.0.0.1/32","127.0.0.0/31","127.0.0.0/30","127.0.0.0/29","127.0.0.0/28","127.0.0.0/27","127.0.0.0/26","127.0.0.0/25","127.0.0.0/24","127.0.0.0/23","127.0.0.0/22","127.0.0.0/21","127.0.0.0/20","127.0.0.0/19","127.0.0.0/18","127.0.0.0/17","127.0.0.0/16","127.0.0.0/15","127.0.0.0/14","127.0.0.0/13","127.0.0.0/12","127.0.0.0/11","127.0.0.0/10","127.0.0.0/9","127.0.0.0/8","126.0.0.0/7","124.0.0.0/6","120.0.0.0/5","112.0.0.0/4","96.0.0.0/3","64.0.0.0/2","0.0.0.0/1") ORDER BY expiration DESC,`syncer_bans`.`id` LIMIT 1
2024/04/16 12:20:49 …
```
=> Apply production defaults for database logger in testing too

internal/test/e2e/gouging_test.go, worker/host.go
That way we can use the data on a host that we consider to be gouging as long as they are not download gouging.
Closes https://github.com/SiaFoundation/renterd/issues/1075
=> Allow for downloading from hosts which are gouging as long as they are not download gouging

api/host.go, autopilot/contractor/contractor.go, autopilot/contractor/evaluate.go, autopilot/contractor/hostfilter.go, autopilot/contractor/hostscore.go, autopilot/contractor/hostscore_test.go, internal/test/e2e/cluster_test.go, stores/hostdb.go
Closes https://github.com/SiaFoundation/renterd/issues/1113
This makes it easier to figure out how much data we store with a host and cleans up the `contractor` a bit.
=> Add 'storedData' field to `api.Host` type

internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go
I find myself committing a custom test logger that logs on `DEBUG` level quite often when I run into an NDF on the CI. Figured it's fine to have `DEBUG` level logging by default in all e2e tests.
=> use debug level logging in testing

bus/client/client_test.go, cmd/renterd/main.go, internal/node/node.go, internal/test/e2e/cluster.go
Refactor leftover I'm guessing(?) we weren't using it so I removed it.
=> Remove SlabPruningCooldown from the bus config.

autopilot/autopilot.go, autopilot/contractor/evaluate.go, internal/test/e2e/cluster.go, internal/test/e2e/gouging_test.go
Seems like we passed the current period instead of the configured period. This PR fixes that.
=> Fix evaluation endpoint returning 0 usable hosts due to gouging on period

stores/metadata.go, worker/download.go, worker/host_test.go, worker/pricetables.go, worker/rhpv2.go, worker/rhpv3.go, worker/upload.go, worker/worker.go
This PR updates a few spots where we return `ctx.Err()` instead of `context.Cause(ctx)` to make sure we return the proper shutdown error instead of the standard "context was cancelled".
=> Update ctx.Err() usage to context.Cause(ctx)

stores/hostdb_test.go, stores/metadata.go, stores/metadata_test.go, stores/multipart_test.go, stores/sql.go, stores/sql_test.go
Making slab pruning asynchronous introduced some NDFs where we run into various `database is locked` related errors, this PR wraps three methods that trigger these NDFs and blocks on the bg loop pruning the necessary slabs. While testing I found we're not properly closing connections in some tests.
=> Fix NDFs in `stores` unit tests.

autopilot/contractor/alerts.go, autopilot/contractor/alerts_test.go, autopilot/contractor/contractor.go
I noticed a handful of "Host has lost sectors" alerts on my node and `arequipa`.  Since we hint at blocking these hosts and since these alerts aren't really all that actionable I introduced a threshold, as Nate suggested in the last engineering sync. This is hardcoded to be 1% of the host's stored data.
=> Only register lost sectors alert if the percentage of sectors lost exceeds a certain threshold.

autopilot/contractor/evaluate.go
Not doing so caused slight differences in the returned value. e.g. it seemed like the number of usable hosts can improve by manually tweaking settings but no recommendation was returned.
Deployed this to Arequipa for testing @alexfreska 
If you set the target to `300` it should give you a recommendation now.
```bash
--- Current contracts ---
Contracts: 266
--- Target contracts ---
Contracts.Amount: 300
--- Before ---
MaxDownloadPrice: 1 KS
{
"hosts": 722,
"usable": 273,
"unusable": {
"blocked": 0,
"gouging": {
"contract": 12,
"download": 109,
"gouging": 131,
"pruning": 7,
"upload": 24
},
"notAcceptingContracts": 83,
"notScanned": 86
},
"recommendation": {
"gougingSettings": {
"maxRPCPrice": "10000000000000000000",
"maxContractPrice": "5000000000000000000000000",
"maxDownloadPrice": …
```
=> Call checkHost the same way before and during evaluation the autopilot config

stores/sql.go, stores/sql_test.go
Caught these errors on `renterd` shutdown, fixed by adding a `context.DeadlineExceeded` case in `abortRetry`.
```
2024-04-23T10:49:08Z INFO  bus  successfully saved 392 accounts
2024-04-23T10:49:42Z ERROR SQL  trace {"error": "context deadline exceeded", "elapsed": "34.701151966s", "rows": 0, "sql": "\nDELETE\nFROM slabs\nWHERE NOT EXISTS (SELECT 1 FROM slices WHERE slices.db_slab_id = slabs.id)\nAND slabs.db_buffered_slab_id IS NULL\n"}
2024-04-23T10:49:42Z WARN  sql  transaction attempt 1/7 failed, retry in 200ms,  err: context deadline exceeded
2024-04-23T10:49:42Z WARN  sql  transaction attempt 2/7 failed, retry in 500ms,  err: context deadline exceeded
2024-04-23T10:49:43Z WARN  sql  transaction attempt 3/7 failed, retry in 1s,  err: context deadline exceeded
2024-04-23T10:49:44Z …
```
=> Handle `context.DeadlineExceeded` when retrying a transaction

.github/workflows/codeql.yml, .github/workflows/test.yml
Our jobs are kind of slow so I was looking at ways to speed them up. I couldn't really find any low hanging fruit but ended up extracting two steps (lint & analyze) I think should be run separately because they do not depend on the `os` or `go-version`. It saves us roughly a minute so nothing ground breaking. 
I ended up removing the `dev` trigger for the CodeQL job. I'm fine reverting that change but I feel we run that a lot without any real upside (so far). I can't remember the time it failed and made me change my PR for the better, since it takes more than two minutes on every single run maybe it's fine to only run it when we merge dev.
=> Extract build steps that are independent of `os` and `go-version` into separate job

autopilot/autopilot.go, autopilot/autopilot_test.go
Fixes https://github.com/SiaFoundation/renterd/issues/1215
=> Update current period in autopilot within for-loop

.github/workflows/test.yml, internal/test/e2e/cluster.go, internal/test/e2e/gouging_test.go, stores/slabbuffer.go
This PR fixes the following race
```
==================
WARNING: DATA RACE
Write at 0x00c002b56060 by goroutine 199842:
go.sia.tech/renterd/stores.(*SlabBufferManager).RemoveBuffers()
Error: /Users/runner/work/renterd/renterd/stores/slabbuffer.go:367 +0x744
go.sia.tech/renterd/stores.(*SQLStore).MarkPackedSlabsUploaded()
Error: /Users/runner/work/renterd/renterd/stores/metadata.go:2528 +0x2b0
...
Previous read at 0x00c002b56060 by goroutine 199673:
go.sia.tech/renterd/stores.(*SlabBufferManager).SlabsForUpload()
Error: /Users/runner/work/renterd/renterd/stores/slabbuffer.go:313 +0x18c
go.sia.tech/renterd/stores.(*SQLStore).PackedSlabsForUpload()
Error: /Users/runner/work/renterd/renterd/stores/metadata.go:2467 +0x1d0
go.sia.tech/renterd/bus.(*bus).packedSlabsHandlerFetchPOST()
... …
```
=> Fix race in `SlabBufferManager`

internal/sql/migrations.go, internal/sql/sql.go, stores/metadata.go, stores/metadata_test.go, stores/sql/database.go, stores/sql/mysql/common.go, stores/sql/mysql/main.go, stores/sql/mysql/metrics.go, stores/sql/sqlite/common.go, stores/sql/sqlite/main.go, stores/sql/sqlite/metrics.go
This is the first method migrated to the new raw sql database type. Starting with a smaller one to keep things easy.
NOTE: `DeleteObject` is different for SQLite and MySQL on purpose. SQLite is less granular when it comes to locking so in my experience performing the writing operation sooner rather than later in the txn reduces the frequency of locking errors.
MySQL on the other hand seemed to benefit from reading the value first to avoid the optimistic locking MySQL performs in the common case.
I'm sure now that we keep these implementations separate we will find many more spots where reorganising queries within transactions will help us improve performance for individual database engines.
=> Migrate RenameObject to raw SQL

autopilot/autopilot.go, autopilot/contractor/evaluate.go, autopilot/contractor/hostscore.go, autopilot/contractor/hostscore_test.go
Run into a panic setting up a `testnet` node. Turns out the new UI sends configs for evaluation even though the autopilot hasn't been configured yet. We should probably create a `UI` issue for this as well but we need to harden against this on both sides.
```
http: panic serving 127.0.0.1:60434: runtime error: integer divide by zero
goroutine 1368 [running]:
net/http.(*conn).serve.func1()
/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:1898 +0xb0
panic({0x101e977a0?, 0x10245df30?})
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
math/bits.Div64(0x14000884f88?, 0x10121e12c?, 0xc18b450f0ba1dff0?)
/opt/homebrew/Cellar/go/1.22.2/libexec/src/math/bits/bits.go:520 +0x170
go.sia.tech/core/types.Currency.quoRem64({0x8459515cec0?, 0x8489330?}, 0x0) …
```
=> Avoid panic when evaluating config if autopilot is not configured

README.md, cmd/renterd/config.go
I updated `renterd` to suggest MySQL for production usage, in my opinion making a distinction between small/personal nodes and anything else confuses people. It's also kind of annoying because if you turn your 10TB node into a 100TB node you'll have to migrate databases. I know SQLite works perfectly fine up until 50TB+ even but since MySQL performs better we might as well suggest it for usage in production?
Extending docs with MySQL setup guides can be tracked here https://github.com/SiaFoundation/docs/issues/77 - I don't think we need to add that to `renterd`'s `README`.
=> Recommend MySQL for production setups

autopilot/contract_pruning.go, autopilot/contractor/alerts.go, autopilot/contractor/contractor.go, stores/sql/mysql/main.go, worker/rhpv2.go, worker/worker.go
With this update Arequipa has been pruning all night without producing any "EOF" alerts. 
That's because the responses become small enough so that the host doesn't close the connection.
1000 roots per batch is significantly smaller than the 500k we had before but the roundabout with `hostd` should be fast enough to not cause too much of a slowdown. It's also a lot better for `hostd`'s db since it won't have to commit as many changes at once.
=> Update worker constants for pruning 

autopilot/contractor/contractor.go, autopilot/contractor/hostfilter.go
I noticed on Arequipa that sometimes after a reboot 6 or so contracts are added to the set which before failed to refresh. That is a result of the refresh failures not being persisted.
That reminded me that we probably don't want to forgive a failed refresh if a contract wasn't in the set to begin with since it will only increase churn if it causes another contract to be pushed out of the set for the next 6 hours instead.
=> Forgive failed refresh only when contract is in set

autopilot/contractor/hosts_test.go
Tweaked the `alpha` in `TestScoredHostsRandSelectByScore`, hopefully we don't ever have to look at it again now. Failed with `50476 49524 9.06304`.
=> Fix TestScoredHostsRandSelectByScore NDF

stores/hostdb.go, stores/sql.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
Unfortunately this PR doesn't yet get rid of the `dbAllowlist` and `dbBlocklist` types. That's because `updateBlocklist` is still using them and it probably doesn't make sense to update that before merging `its-happening`.
=> Migrate allowlists and blocklists to raw SQL

stores/metrics.go, stores/metrics_test.go, stores/sql/database.go, stores/sql/metrics.go, stores/sql/mysql/metrics.go, stores/sql/sqlite/metrics.go, stores/sql/types.go
I'll get rid of the `dbContractPruneMetric` type when I migrate `PruneMetrics`.
=> Migrate ContractPruneMetrics to raw SQL

stores/metadata.go
Turns out on nodes like gompa archiving 200 contracts in a single transaction is a bit too much to handle for MySQL. Especially when the contracts are large due to the cascade delete happening.
It will try to archive 200 contracts over a very long time, fail and then the contracts never actually get archived.
This way it still takes a while but it makes steady progress.
=> Archive contracts one-by-one

bus/bus.go
Probably got lost in a merge somewhere, but we should definitely only broadcast the update when we're synced or otherwise a fresh start is horrible.
=> Only broadcast consensus update when we are synced

worker/rhpv2.go
`areq` has an alert for unexpected response size (very old host), figured getting rid of the exact math is probably ok, reused `maxMerkleProofResponseSize` to avoid duplicating the const
=> Get rid of exact math for sector roots response size

autopilot/contract_pruning.go
The sector roots RPC used to return all sector roots, this was fixed in https://github.com/SiaFoundation/hostd/commit/e6dfc96fa0f8aab45ce0c87de0f87ffe477f83a5 and released in https://github.com/SiaFoundation/hostd/releases/tag/v1.0.2-beta.4 . We should ignore the error for old hosts.
=> Ignore sector roots range prune alert on old hosts

stores/metadata.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go, worker/host.go, worker/pricetables.go, worker/worker.go
- Minor tweak to slab health update to speed it up by making use of indices
- Make sure recording a host scans doesn't abort after 30 seconds when db is under heavy load
- Make sure recording price tables doesn't abort after 30 seconds when db is under heavy load
- Register new price tables in the background, unblocking operations faster and preventing the record operation from being cancelled after a timeout
=> Minor fixes related to slow db queries

stores/chain_test.go, stores/metadata.go, stores/metadata_test.go, stores/slabbuffer.go, stores/slabbuffer_test.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
This PR removes GORM from
- `SearchObjects`
- `AddPartialSlab`
- `Slab`
- `RefreshHealth`
- `PackedSlabsForUpload`
- `ObjectMetadata` 
and removes
- `contractsForHost` (unused) together with `TestContractsForHost`
=> Various migrations in metadata.go

worker/host.go
This fixes a little edge case leading to unnecessary log spam which will be obsolete once we have RHPv4 since fetching costs will be free then anyway.
=> Ignore price table gouging when syncing account

stores/accounts.go, stores/autopilot.go, stores/chain.go, stores/hostdb.go, stores/hostdb_test.go, stores/metadata.go, stores/metadata_test.go, stores/metrics.go, stores/multipart.go, stores/multipart_test.go, stores/peers.go, stores/settingsdb.go, stores/slabbuffer_test.go, stores/sql.go, stores/sql/main.go, stores/sql_test.go, stores/types.go, stores/types_test.go, stores/wallet.go, stores/webhooks.go
This removes GORM from our production code entirely. It's now only used in tests.
Therefore `db` was renamed to `gormDB` to make it clear that it's no longer to be used.
`bMain` is now `db`.
=> Remove GORM from production code

cmd/renterd/main.go
The contractor uses the same submission buffer the host does, this causes race conditions between the contract's maintenance and the uploaders. I figured it's fine to add a 1h leeway to the buffer to ensure we handle the contract properly before we run into the buffer. The host returns an `internal error` when this happens so we (mistakenly) penalise it for being a bad host and failing the sector upload.
```
{"level":"debug","ts":"2024-07-16T15:46:44Z","logger":"worker.worker.uploadmanager","caller":"worker/uploader.go:138","msg":"sector upload failure was penalised","uploadError":"failed to upload sector to contract fcid:6556f6b59512c18c273cf8dca642a8f1344eb9f8d66cf1909155ece4421a5a81; AppendSector: ReadResponse: host responded with error: 'internal …
```
=> Add 1h leeway to revision submission buffer

internal/test/e2e/gouging_test.go, worker/gouging.go, worker/host.go
Often times when critical migrations fail it is because we don't fund the ephemeral account when the host is considered price gouging. Since we have checks in place that will prevent uploads, as well as checks that prevent drastically overpaying on downloads, I think the best approach is to allow refilling ephemeral accounts, even if the host is price gouging. Of course we do want _some_ checks so I extracted the unused defaults check. In practice that final refill should be enough to get all data migrated away from that host. 
```
failed to migrate slab; failed to download slab for migration: failed to download slab: completed=8 inflight=0 launched=29 relaunched=0 overpaid=0 downloaders=377 unused=1 errors=22 72e8ea2c: ephemeral account balance was insufficient …
```
=> Ensure critical migrations succeed by refilling EAs on hosts that are gouging their prices

autopilot/accounts.go, autopilot/autopilot.go
Encountered this error on `renterd` side a lot when trying to fund ephemeral accounts. Turns out the contract is too close to the proof window to be revised, so funding is not possible. I passed down the `revisionSubmissionBuffer` and return early in `refillWorkerAccount`.
```
{"level":"debug","ts":"2024-07-16T16:04:56Z","logger":"autopilot.autopilot.accounts","caller":"autopilot/accounts.go:158","msg":"failed to fund account: couldn't fund account: unable to fetch revision with contract: LatestRevision: ReadResponse: host responded with error: 'internal error'\n","accountID":"ed25519:b3143551b31919df6f23d0f9636ba5d263db0b686a8ebfb787a46e1d47ead5d1","hostKey":"ed25519:da2e16500a5413f31170a37334e91eeccf38af620861991bad21a9e9eb9061e7","balance":"-1807848587969294024770","expected":"1 SC"} …
```
=> Take revision submission buffer into account when refilling ephemeral accounts

autopilot/migrator.go, internal/chain/chainsubscriber.go
There's no point in migrating trying to migrate the remaining unhealthy slabs if we encounter `ErrConsensusNotSynced`. Instead we log and interrupt the migrations, essentially pausing migrations until the next iteration of the autopilot loop. Happend on `arequipa`, resulting in 100k+ migration alerts. Looking at block deltas, block `479246` seems like a likely culprit.
```
479003 2024-07-14T23:20:29Z 31m7s
479017 2024-07-15T01:50:12Z 40m35s
479040 2024-07-15T06:02:13Z 36m53s
479068 2024-07-15T10:26:56Z 39m13s
479077 2024-07-15T12:18:08Z 33m41s
479114 2024-07-15T19:06:26Z 30m51s
479116 2024-07-15T20:03:21Z 33m40s
479134 2024-07-15T23:22:41Z 35m23s
479138 2024-07-16T01:07:29Z 40m10s
479177 2024-07-16T06:36:39Z 32m27s
479215 2024-07-16T12:12:58Z 34m30s
479246 2024-07-16T17:25:16Z 1h1m3s …
```
=> Interrupt migrations when consensus becomes unsynced

api/contract.go, autopilot/accounts.go, worker/worker.go
There's a PR to be merged where I suggest adding an `InSet` method to the `ContractMetadata`. I found a spot where I could use it myself so I figured I'd PR it. There's one or two places where we fetch all contracts, and then fetch contract set contracts, which is a subset of the contracts we just fetched.
=> Remove redundant contracts call

autopilot/alerts.go, autopilot/migrator.go
The repairs update the health of slabs to 100% so even when the refresh fails we can at least try and migrate the slabs we already know are in bad health.
=> Don't interrupt migrations when refresh fails

api/setting.go
Related to https://github.com/SiaFoundation/web/pull/671
Changes the json to not omit any fields, making it a bit more obvious what fields are available to configure.
=> Update price pinning json

api/events.go, internal/chain/chainsubscriber.go, internal/test/e2e/events_test.go, internal/worker/cache.go, internal/worker/cache_test.go
This PR invalidates the worker cache when we process host updates. The host's IP is on the contract metadata so when a host re-announces that metadata is not properly invalidated. We have a cache entry expiry of 5' so it's not that big of a deal but this PR addresses it by updating the metadata.
Fixes #1371
=> Invalidate worker cache on host updates

autopilot/alerts.go, autopilot/migrator.go
There's not much of an upside to using a random id for health refreshes. This PR dismisses the alert when health refreshes succeed, ensuring these critical alerts auto-dismiss if they succeed. Bit of a trade off obviously but I like this better (?).
=> Use constant id for health refresh failure alerts

autopilot/migrator.go, autopilot/scanner/scanner.go, internal/utils/stats.go, worker/download.go, worker/downloader.go, worker/upload.go, worker/uploader.go
In time we can probably get rid of this altogether, until then perhaps we can tuck it away in `internal/utils`.
=> Remove `stats` package

api/wallet.go, bus/bus.go, bus/client/wallet.go, bus/routes.go, internal/node/syncer.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go
This PR adds a new `/wallet/send` endpoint which is a lot easier to use than the existing 2-step solution.
Other endpoints like the ones for forming and renewing contracts will also be updated to be single endpoints on the bus rather than multiple. The existing endpoints will remain in the API until we are ready for a breaking v2.0.0.
The biggest advantage of this endpoint over the existing one is the fact that it's type agnostic. Switching from v1 to v2 transactions can happen without the consumer of the API being aware of the transition.
=> Add /wallet/send endpoint

stores/metadata_test.go
This test failed locally for me about 1% of the time but on the CI I've seen it pop up several times. Figured an appropriate fix is to wait for a prune loop and then run our assertions, avoiding the retry loop as well as the NDF, passes 1000x locally.
=> Fix TestRenameObject NDF

.github/workflows/test.yml, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, internal/test/e2e/host.go
This ensures the host has more than one spendable output to work with, avoiding the NDF where it fails to fund a contract formation txn. This PR also fixes the deadlock we've been seeing by passing a buffered error channel to the host's volume manager.
=> Fix TestContractApplyChainUpdates NDF

api/metrics.go, bus/bus.go, internal/bus/walletmetricsrecorder.go, internal/sql/migrations.go, internal/test/e2e/metrics_test.go, stores/metrics_test.go, stores/sql/metrics.go, stores/sql/mysql/migrations/metrics/migration_00002_idx_wallet_metrics_immature.sql, stores/sql/mysql/migrations/metrics/schema.sql, stores/sql/sqlite/migrations/metrics/migration_00002_idx_wallet_metrics_immature.sql, stores/sql/sqlite/migrations/metrics/schema.sql
This PR adds a recorder in the bus that periodically records wallet metrics. 
Kept it simple, figured that is fine for now, couple of things I considered were:
- expose the update interval
- increasing interval and add a `Trigger` which we call on `FundTransaction`
=> Record wallet metrics in the bus

api/setting.go, bus/bus.go, internal/test/config.go, internal/test/e2e/cluster_test.go
This PR adds default values for the `PricePinSettings`. The UI only needs a default for the `ForexEndpointURL` but I figured we might as well add a sane default for all values, except for the actual pins, for documentation purposes.
=> Add default values for PricePinSettings

api/events.go, bus/routes.go, internal/worker/cache.go, internal/worker/events.go, internal/worker/events_test.go
It seems like right now the cached contracts are not updated when a new contract is added. This fixes that.
I noticed because the worker failed to refill ephemeral accounts in my open PR since the cached contracts were always 0 because the cache was initialized before the contracts had been formed.
=> Add contract additions to worker cache

cmd/renterd/node.go
Refactoring the node setup it looks like I made `autopilot.Run` blocking. This prevents S3 setup from successfully completing.
Fixes #1473
=> Fix node setup

.github/workflows/test.yml, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go
```
cluster_test.go:1343: failed to accept block: reorg failed: couldn't apply block 293::4086dccb: block 293::4086dccb is invalid: transaction 1 is invalid: siacoin input 0 double-spends parent output (previously spent in txid:e70a27c3149f481a3d89a70dfc92eeab939d4d05e4b6a3490fc57f546af70dc7)
```
=> Fix TestEphemeralAccountSync NDF

internal/sql/migrations.go
Occasionally we have to perform a migration only on the SQLite db and not the MySQL db or vice versa (see `00020_idx_db_directory`). Up until now MySQL would fail though with "empty query". Since it's nice to have a nice overview of migrations I think we should allow empty migrations and not execute them when we find they're empty.
=> Allow empty migrations

api/host.go, api/object.go, autopilot/autopilot.go, autopilot/scanner/scanner.go, autopilot/scanner/scanner_test.go, bus/bus.go, bus/client/hosts.go, bus/routes.go, internal/test/e2e/cluster_test.go, stores/hostdb.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
Gets rid of `/hosts/scanning` by adding an extra filter option to the `/hosts` endpoint.
=> Merge hosts endpoints

bus/routes.go, internal/test/e2e/cluster.go, stores/sql/sqlite/migrations/main/migration_00019_settings.sql
Hm look like this slipped through. When I saw the issue I was surprised because I was sure I added it, but it looks like I'm not populating the autopilots if the setting isn't found and we return the default settings.
Fixes https://github.com/SiaFoundation/renterd/issues/1532
=> Populate autopilots in pinned settings

.github/workflows/test.yml, autopilot/scanner/scanner.go, autopilot/scanner/scanner_test.go
Fixes https://github.com/SiaFoundation/renterd/issues/1538
=> Have scanner wait for batch to finish before starting a new one

stores/sql/sqlite/migrations/main/migration_00021_archived_contracts.sql, stores/sql/sqlite/migrations/metrics/migration_00004_contract_spending.sql
In SQLite index names have to be unique across all tables, not like in MySQL where it has to be unique within each table. For SQLite the migration errors out with `Error: index idx_contracts_proof_height already exists`, this PR fixes that by recreating all indices. I don't think we can get around that in SQLite, either that or we have to do it from the application side but I don't see an issue recreating them, it was super fast on arequipa.
=> Fix migration_00021_archived_contracts for SQLite

internal/sql/migrations.go, stores/sql/mysql/migrations/main/migration_00022_remove_triggers.sql, stores/sql/mysql/migrations/main/schema.sql, stores/sql/sqlite/migrations/main/migration_00022_remove_triggers.sql, stores/sql/sqlite/migrations/main/schema.sql
Seems like we forgot to remove the triggers from the schema when we removed them. So I did that here and added another migration to remove them.
=> Remove unused SQL triggers

internal/test/e2e/cluster_test.go, internal/utils/web.go, worker/client/client.go
We are inconsistent when it comes to escaping the bucket name in the query string. This PR makes the behaviour consistent and allows for bucket names with spaces in them. I'm wondering whether we should allow special characters in bucket names. If not we should add an assertion in create bucket.
Related to https://github.com/SiaFoundation/renterd/issues/1498
=> Fix inconsistent URL escaping for the 'bucket' parameter

api/bus.go, autopilot/autopilot.go, autopilot/contractor/evaluate.go, autopilot/contractor/evaluate_test.go, autopilot/contractor/state.go, bus/bus.go, bus/routes.go, internal/gouging/gouging.go, internal/worker/cache.go, internal/worker/cache_test.go, worker/gouging.go
Icarus experienced large contract churn on 9/20 around 10pm, ~60 contracts got removed from the set. The logs indicate hosts were considered gouging because their recommended transaction fee exceeded a certain amount.  We hit a renew window around that time as well as a considerable drop in hash rate (40%), the theory is that the transaction pool clogged up causing the hosts to set higher transaction fees, which in turn caused renters to flip out about it.
We use the recommended fee when we renew contracts with the host. It's expressed as a fee per byte so we multiply it by `4096`. This PR updates the gouging checks to compare the recommended fee against the max contract price, essentially protection against the same exploit but with a (configurable) setting that's a bit more lenient.
=> Compare recommended fee against contract price

.github/workflows/test.yml, alerts/prometheus.go, api/prometheus.go, api/utils.go, bus/routes.go, internal/prometheus/encoder.go, internal/prometheus/encoder_test.go, internal/prometheus/metric.go, worker/worker.go
Continuation of https://github.com/SiaFoundation/renterd/pull/1068
Addressed some of the concerns in the reviews:
- Move `PrometheusMetric` method to original type where possible
- Move `writeResponse` logic to api package
- Improve handling slices of Prometheus marshallable types
- Disable type checking in `jape`
=> Prometheus encoding

.github/workflows/publish.yml, .github/workflows/test.yml, docker/Dockerfile
Changes `go build` calls to be consistent with `hostd` by adding `netgo` and `timetzdata` until we move to the common workflow.
=> Build binaries with `netgo`

.github/workflows/test.yml, autopilot/workerpool.go, internal/test/e2e/cluster_test.go, worker/client/client.go, worker/worker.go
Test ran 6*50 times without failing with this fix.
NDF that was fixed: `cluster_test.go:1386: account shouldn't be marked as clean shutdown or not require a sync, got true false`
Example: https://github.com/SiaFoundation/renterd/actions/runs/11496423699/job/31998008008
The problem was that after the restart of the cluster, when we first fetch the account, the account gets created and sometimes synced (since created accounts are unclean and need to be synced).
Whenever it got synced before the check the test failed.
While debugging I noticed that the GET route for fetching accounts only returns the account id which I thought was odd anyway so I updated it to return the full account. So the route returns the freshly created, unclean account right away without a chance to sync it. Which …
=> Fix `TestEphemeralAccountSync` NDF

stores/sql/mysql/chain.go, stores/sql/sqlite/chain.go
A panic due to updating entries in the database while not having fully consumed the `rows` cursor yet.
=> Fix panic in TestBlocklist

autopilot/contractor/hostscore.go, autopilot/contractor/hostscore_test.go, autopilot/scanner/scanner.go
Closes https://github.com/SiaFoundation/renterd/issues/1595
The value `0.1` was picked mostly because it seemed reasonable that when comparing a perfect host to another one that fails in a single category would be 10x more likely to get picked as a host.
Similarly when compared to a host that fails in every category a perfect host would be 10,000,000x more likely to be picked.
So there is still an exponential component to it but the approach in this PR lessens the impact of potential temporary issues or bugs.
=> Limit lowest possible sub-score for a host

internal/bus/chainsubscriber.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, stores/chain_test.go, stores/sql/chain.go, stores/sql/main.go
Fixes an issue when resyncing a node on MySQL since MySQL will return `n == 0` when a row wasn't updated. Which is expected when resyncing.
=> Drop n == 0 checks in chain.go

api/worker.go, internal/memory/memory.go, worker/download.go, worker/mocks_test.go, worker/upload.go
This is one of the multiple steps required to merge the autopilot + migrations into the bus.
With both the worker and autopilot requiring the ability to upload, we need to isolate the upload manager.
To do that we need to isolate shared dependencies between upload and download manager.
Trying to achieve this in the smallest possible bites, I'm starting with the memory manager.
=> Move memory manager from worker to dedicated package

.changeset/check_for_existing_migration_00027_remove_directories_and_skip_both_00020_idx_db_directory_and_00020_remove_directories_if_already_applied.md, internal/sql/migrations.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/mysql/metrics.go, stores/sql/sqlite/main.go, stores/sql/sqlite/metrics.go
Renaming `00027_remove_directories` to `00020_remove_directories` when merging in `master` back into `dev` has a nasty side-effect on nodes that already ran `00027_remove_directories` because the migration will try and run again and look for FKs that have already been removed. 
In hindsight, we should've immediately merged it as a hotfix, into `master` first and then `dev`. Updating the identifier to try and keep it a sequential list of IDs was the second mistake. Migrations should probably just have a descriptive name.
=> Check for pre-existing migration

.changeset/track_contract_elements.md, internal/bus/chainsubscriber.go, internal/sql/migrations.go, stores/chain_test.go, stores/sql/chain.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/chain.go, stores/sql/mysql/migrations/main/migration_00029_contract_elements.sql, stores/sql/mysql/migrations/main/schema.sql, stores/sql/sqlite/chain.go, stores/sql/sqlite/migrations/main/migration_00029_contract_elements.sql, stores/sql/sqlite/migrations/main/schema.sql, stores/sql/types.go
This PR adds a `contract_elements` table which contains elements for all contracts in our database and updates their accumulator proofs. This a requirement for broadcasting file contract related txns such as broadcasting revisions.
=> Track contract elements 

.changeset/add_ratelimit_to_max_drift.md, internal/worker/accounts.go, internal/worker/accounts_test.go
This changes the max drift to be allowed to reset at a certain spending rate. Fixing issues with inaccurate accounting due to v3 pricing while still protecting renters from malicious hosts.
=> Treat max drift as a rate rather than an absolute limit

.changeset/monitor_file_contracts_and_unlock_their_funds_when_they_expire.md, autopilot/contractor/contractor.go, autopilot/contractor/contractor_test.go, autopilot/contractor/hostfilter.go, bus/bus.go, internal/bus/chainsubscriber.go, internal/test/e2e/cluster_test.go, stores/sql/chain.go, stores/sql/database.go, stores/sql/mysql/chain.go, stores/sql/sqlite/chain.go
Fixes https://github.com/SiaFoundation/renterd/issues/1719
=> Unlock contract funds when host is offline

.changeset/remove_hostip_and_siamuxaddr_from_contractmetadata.md, api/contract.go, api/prometheus.go, bus/bus.go, bus/routes.go, internal/upload/uploader/uploader.go, internal/upload/uploader/uploader_test.go, stores/metadata_test.go, stores/sql/rows.go, worker/upload.go, worker/upload_test.go, worker/worker_test.go
Implement https://github.com/SiaFoundation/renterd/issues/1691
=> Remove HostIP and SiamuxAddr from ContractMetadata

.changeset/enforce_s3_bucket_name_validation_rules_on_bucket_creation_request.md, api/bucket.go, api/bucket_test.go, bus/routes.go, internal/test/e2e/cluster_test.go
Closes https://github.com/SiaFoundation/renterd/issues/1583
Right now we don't have any naming rules on buckets except for the name not being an empty string. Since that is not particularly useful and opens up room for odd edge cases, this PR adds the same bucket name validation rules that S3 has. That way any bucket name valid on S3 is also valid in `renterd` which makes it very easy to migrate buckets back and forth if so desired.
=> Bucket name validation

.changeset/add_openapiyml_file_with_autopilot_routes.md, .github/workflows/test.yml, api/prometheus.go, api/setting.go, internal/gouging/gouging.go, internal/gouging/gouging_test.go, internal/test/config.go, openapi.yml
Added an openapi.yml spec with the specifications for the autopilot routes and a CI step to validate it. The goal is to eventually have a complete spec for the V2 API that we can use to generate API docs as well as making sure that there is always a valid spec for every given commit in the repo.
=> Add openapi.yml file with autopilot routes

.changeset/implement_support_for_pruning_using_rhp4.md, bus/pruning.go, bus/routes.go, internal/rhp/v4/rhp.go, internal/test/e2e/cluster.go, internal/test/e2e/pruning_test.go
Closes https://github.com/SiaFoundation/renterd/issues/1676
=> Implement support for pruning using RHP4

.changeset/improve_migration_out_after_foreignkey_check_fails.md, stores/sql/sqlite/common.go
If `PRAGMA foreign_key_check` fails after running a migration, `renterd` currently outputs totally useless information. I updated the code to scan for all errors and indicate what FK failed on what table on what row.
Before:
```
failed to create node: failed to perform migrations: migration X failed: transaction failed (attempt 1): foreign key constraints are not satisfied, err sql: expected 4 destination arguments in Scan, not 0
```
After:
```
failed to create node: failed to perform migrations: migration X failed: transaction failed (attempt 1): foreign key constraint violation in table 'slabs': row 2423432, foreign key buffered_slabs
```
=> Improve error output after a failed FK constraint check

.changeset/fix_default_settings_not_being_used_everywhere_if_settings_are_not_found_in_database.md, bus/routes.go, bus/settings.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, internal/test/e2e/host.go
Fixes a bug I encountered while testing where deleting the settings from the database caused uploads to fail rather than using the defaults as intended.
=> Fix default settings not being used consistently

.changeset/dont_perform_full_slab_prune_on_startup.md, stores/sql.go
If the database is busy due to lots of slabs requiring pruning, this can prevent renterd from starting. Instead the background loop should handle this.
Ran this on gompa to get it to break out of a restart loop
=> Don't prune slabs on startup

.changeset/allow_worker_id_to_be_empty_when_worker_is_disabled.md, cmd/renterd/config.go
Closes https://github.com/SiaFoundation/renterd/issues/1766
=> Allow worker id to be empty when worker isn't enabled

.changeset/fix_hosts_that_fail_the_pre_scan_checks_not_having_a_failed_scan_recorded_.md, bus/routes.go, bus/scanning.go, internal/test/e2e/cluster_test.go
I noticed that hosts which fail the checks before the actual scan appeared quite a lot in the logs of gompa. Turns out that we never consider these hosts scanned which caused them to end up in every batch of the scans. This PR fixes that.
=> Fix hosts failing `shouldScanHost` check appearing in every batch

.changeset/speed_up_slab_pruning_query.md, api/prometheus.go, stores/bench_test.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
This PR speeds up the selection of slabs to prune by about 3x on gompa
```
Limit: 100 row(s)  (cost=209e+9 rows=100) (actual time=3622..3622 rows=100 loops=1)
-> Nested loop antijoin  (cost=209e+9 rows=2.09e+12) (actual time=3622..3622 rows=100 loops=1)
-> Filter: (slabs.db_buffered_slab_id is null)  (cost=124725 rows=1.23e+6) (actual time=0.7..131 rows=358768 loops=1)
-> Covering index lookup on slabs using idx_slabs_db_buffered_slab_id (db_buffered_slab_id = NULL)  (cost=124725 rows=1.23e+6) (actual time=0.699..110 rows=358768 loops=1)
-> Single-row index lookup on <subquery2> using <auto_distinct_key> (db_slab_id = slabs.id)  (cost=580736..580736 rows=1) (actual time=0.00965..0.00965 rows=1 loops=358768)
-> Materialize with deduplication  (cost=580736..580736 rows=1.71e+6) (actual …
```
=> Improve slab pruning query

.changeset/fix_error_output_in_the_renterdlog.md, autopilot/autopilot.go, bus/bus.go, bus/routes.go, cmd/renterd/node.go, internal/accounts/accounts.go, internal/bus/pinmanager.go, internal/bus/walletmetricsrecorder.go, internal/rhp/dialer.go, internal/rhp/v3/rhp.go, internal/sql/sql.go
Having spent some time in our `renterd.log` recently I noticed a lot of entries that appear to log an object rather than the structured logs with context you would expect. I think we string replaced `err` to `zap.Error(err)` or something and forgot to check the instances where we have to switch the logging method and use the one that logs the variadic key pairs. 
Example:
```
2025-01-08T14:28:58Z	DEBUG	worker.worker.fallbackdialer	Failed to resolve host, using cached IP{error 26 0  dial tcp: lookup pikrue.spdns.org: operation was canceled}	{"hostKey": "ed25519:82aec15c5786b9037b74ca0b59e958724641c4c71093916c2749dc22a5392de3", "host": "pikrue.spdns.org"}
```
=> Improve error logging

.changeset/fragment_the_wallet_into_larger_outputs.md, autopilot/autopilot.go, internal/test/e2e/cluster_test.go
I want to propose a change in how we redistribute wallet outputs. I understand this feels a little arbitrary but my node runs so much smoother after making this change and I personally don't understand why we wouldn't give ourselves a little leeway when it comes to spendable and usable outputs in our wallet. The current logic really doesn't make sense to me, so definitely we have to tweak it a bit I think. 
Some extra context:
On my node I ran into several occasions where my wallet was trying to spend nonexisting siacoin outputs. I can't reproduce it and the logging I had was not sufficient to debug it any further. I only had an output ID but it never appeared in the logs other than the error message, it wasn't present in the database either so I'm a bit puzzled. 
It happend on contract …
=> Fragment the wallet into outputs with a larger value

.changeset/dont_return_an_error_when_a_v1_contract_doesnt_contain_any_sectors_to_prune.md, .changeset/fix_memory_manager_for_downloads_using_the_uploads_config.md, bus/pruning.go, worker/worker.go
Fixes the download manager using cfg.UploadMaxMemory
Prevents the pruning endpoint from returning an error when no sectors for pruning were found to prevent unnecessary errors in logs
=> Fix memory manager config

.changeset/fix_potential_deadlockpanic_when_forcing_a_scan.md, autopilot/scanner/scanner.go, autopilot/scanner/scanner_test.go, bus/scanning.go
I ran into a deadlock on my node forcing a rescan. Because it closes a channel you can even make it panic if you request a rescan twice in short succession. I figured a decent approach would be to keep around a cancel function for the ongoing scan... This allows us to get rid of `shutdownChan` and `interruptChan` and is overall more readable imo.
a scan is started, which we derive from the context given down to us. If we have to re-scan we can call cancel and wait for ongoing scans to be interrupted and start again.
=> Prevent deadlock/panic when forcing a rescan

.changeset/fix_upload_bug_that_caused_failures_when_uploading_to_contracts_that_are_being_refreshed_in_the_background.md, internal/test/mocks/contractstore.go, internal/upload/uploader/uploader.go, internal/upload/uploader/uploader_test.go, worker/worker_test.go
I encountered these upload failures on my node and found out we don't properly refresh the uploader's contract ID if it got refreshed/renewed in the background. Possible solution was a host store but I think this is superior, avoids a lot of dependency injection and most annoyingly I found that it's quite cumbersome to get at `api.HostInfo` for a single host...
```
2025-01-10T13:51:23Z    DEBUG   worker.worker.uploadmanager     sector upload failure was ignored       {"uploadError": "failed to upload sector to contract e6237a2a66ffe5d4e6d1e017983d2cffe039f07bbb9f73b82ac5b5ceedb9ef68; contract has reached the maximum number of revisions", "uploadDuration": "0s", "totalDuration": "28.417729ms", "overdrive": false, "hk": "ed25519:05e1b50b4d0104bc1ec30f3ec570f3abcea34e38b903cd24896b718032ef2c6 …
```
=> Fix upload error on contracts being refreshed in the background

.changeset/fix_upload_failure.md, stores/contracts_test.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
When we fetch used sectors we take into account that the contracts could have been renewed during the upload, we don't take into account however that a contract might've been archived in the mean time. This results in a scan failure and eventually ends up failing the upload.
=> Fix failed upload using archived contracts

.changeset/fixed_data_race_when_fetching_a_new_price_table.md, internal/prices/prices.go
The race:
```
=== RUN   TestPricesCache
==================
WARNING: DATA RACE
Write at 0x00c000138c28 by goroutine 9:
go.sia.tech/renterd/internal/prices.(*cachedPrices).fetch()
/home/runner/work/renterd/renterd/internal/prices/prices.go:125 +0x8d0
go.sia.tech/renterd/internal/prices.(*PricesCache).Fetch()
/home/runner/work/renterd/renterd/internal/prices/prices.go:66 +0x304
go.sia.tech/renterd/internal/prices.TestPricesCache.gowrap1()
/home/runner/work/renterd/renterd/internal/prices/prices_test.go:69 +0xa4
Previous read at 0x00c000138c28 by goroutine 8:
go.sia.tech/renterd/internal/prices.(*cachedPrices).fetch()
/home/runner/work/renterd/renterd/internal/prices/prices.go:90 +0x10e
go.sia.tech/renterd/internal/prices.(*PricesCache).Fetch() …
```
=> Fix race when fetching prices

.changeset/fix_issue_where_db_migration_migration_00020_idx_db_directorysql_would_fail_due_to_a_column_being_missing.md, stores/sql/sqlite/migrations/main/migration_00020_idx_db_directory.sql
Closes https://github.com/SiaFoundation/renterd/issues/1803
Some users have been reporting that creating this index fails due to the directory reference being missing on the `objects` table. Which happens when the migrations were run out of order. Easiest fix is to avoid that migration altogether since the table was dropped.
=> Fix creation of directory table related index

.changeset/fix_deadlock_in_test_suite.md, internal/test/e2e/cluster_test.go
There are two tests where we manually close/remove a host, `TestContractFundsReturnWhenHostOffline` and `TestHostScan`, turns out calling `Close` on a test host twice causes a potential deadlock in the syncer because we `Connect` after closing. This has to be fixed in the syncer of course but on our end we can avoid calling `Close` twice and properly remove the host from the cluster instead.
see https://github.com/SiaFoundation/coreutils/issues/100
=> Fix deadlock in test suite

.changeset/use_standard_directories.md, Dockerfile, cmd/renterd/commands.go, cmd/renterd/config.go, cmd/renterd/main.go, cmd/renterd/node.go, config/config.go
Uses standard locations for application data instead of the current directory. This brings `renterd` in line with other system services and makes it easier to manage application data.
- Configuration: `/etc/walletd/walletd.yml`
- Data directory: `/var/lib/walletd`
- Configuration: `~/Library/Application Support/walletd.yml`
- Data directory: `~/Library/Application Support/walletd`
- Configuration: `%APPDATA%\SiaFoundation\walletd.yml`
- Data directory: `%APPDATA%\SiaFoundation\walletd`
- Configuration: `/data/walletd.yml`
- Data directory: `/data`
=> Use standard directories

.changeset/reduce_info_level_logging_spam_related_to_host_scanning_and_pruning.md, autopilot/contractor/contractor.go, autopilot/contractor/hostset.go, autopilot/pruner/pruning.go, bus/scanning.go, internal/accounts/accounts.go
This is a quick PR related to https://github.com/SiaFoundation/renterd/issues/1810 to tackle some of the low-hanging fruits.
On my node the logs were multiple GBs large. After removing the debug logging about half a GB remained. That was mostly 3 issues. 
1. repeatedly logging that pruning 0 bytes from a contract succeeded
2. logging that we failed to scan a host
3. logging that the account balance was reset
Moving these 3 to Debug should significantly reduce the logging. 
There are a few more changes but non as significant
=> Reduce default logging

.changeset/remove_internal_imports_in_main_package.md, cmd/renterd/node.go, internal/utils/web.go
It doesn't prevent you from creating a `renterd` node but the rule states our `main` packages must be free of `internal` imports
=> Remove internal import

.changeset/fix_issue_with_remaining_storage_and_version_scoring_for_v2_hosts.md, autopilot/contractor/hostscore.go, autopilot/contractor/hostscore_test.go, internal/test/e2e/gouging_test.go, internal/test/host.go
This fixes 2 scoring issues with v2 hosts related to version and remaining storage scores and also adds more testing for v2 host scoring.
=> Fix v2 host score check

.changeset/docs_add_descriptions_to_all_routes_and_schemas.md, openapi.yml
This PR updates the description where I felt it was lacking or missing entirely.
One thing I noticed is that most informative descriptions are a bit buried in the schema and object descriptions which aren't visible by default in a swagger editor. For example, the issue I linked mentioned a missing description for what the owner of an account is, which is in the schema but  not immediately obvious indeed
Closes https://github.com/SiaFoundation/renterd/issues/1843
=> Extend docs with descriptions for all routes and schemas

.changeset/add_compate_code_to_migrate_the_config_from_v111_to_v201.md, config/compat.go, config/config.go
Tested with YAML:
```
seed: [ENTER SEED HERE]
directory: "."
autoOpenWebUI: true
network: mainnet
shutdownTimeout: 5m0s
log:
level: info
stdout:
enabled: true
format: human
enableANSI: true
file:
enabled: true
format: human
http:
address: localhost:9980
password: test
autopilot:
enabled: true
heartbeat: 30m0s
migrationHealthCutoff: 0.8
migratorParallelSlabsPerWorker: 2
revisionBroadcastInterval: 168h0m0s
revisionSubmissionBuffer: 150
scannerInterval: 4h0m0s
scannerBatchSize: 100
scannerNumThreads: 10
bus:
persistInterval: 1m0s
announcementMaxAgeHours: 8736
bootstrap: true
gatewayAddr: :9981
usedUtxoExpiry: 24h0m0s
slabBufferCompleionThreshold: 4096
worker:
contractLockTimeout: 1h0m0s
enabled: true
id: worker
accountsRefillInterval: 10s
busFlushInterval: 5s
downloadOverdriveTimeout: 3s …
```
=> Add v111 compat code

.changeset/docs_add_descriptions_to_all_routes_and_schemas.md, .changeset/fix_broadcastexpiredfilecontractresolutions_not_including_unconfirmed_transactions_when_broadcasting_revisions.md, internal/bus/chainsubscriber.go
Fix https://github.com/SiaFoundation/renterd/issues/1856
=> Fix broadcastExpiredFileContractResolutions not including unconfirmed transactions when broadcasting revisions

.changeset/add_dl_query_param_to_download_endpoint_to_be_able_to_change_the_content_disposition_to_attachement.md, .changeset/fix_missing_inferred_mimetype_for_objects_uploaded_via_multipart_uploads.md, api/object.go, bus/routes.go, internal/test/e2e/cluster_test.go, worker/client/client.go, worker/worker.go
We currently don't infer a content type for multipart uploads. Only regular uploads.
To be consistent with regular uploads and common S3 client implementations, this PR changes multipart uploads to also infer the type from the extension and if that doesn't work set it to `application/octet-stream`.
=> Infer mime type when creating multipart upload

.changeset/remove_context_from_bus_initialisation.md, bus/bus.go, cmd/renterd/node.go, internal/test/e2e/cluster.go
We pass a sane timeout to bus constructors to avoid hanging indefinitely, since we now potentially have a reasonably long chain db migration I removed it and added a sane timeout to the two locations that apparently need it. It's mostly because our `Store` requires a context on all of its methods, like initialising the autopilot config.
=> Remove context from bus initialisation

.changeset/fix_renter_expecting_host_putting_up_too_much_collateral_for_v2_contracts.md, bus/bus.go
Depends on https://github.com/SiaFoundation/core/pull/299
Noticed that none of my Zen contracts renewed. This change fixed it.
Need to update go.mod once the dependencies are merged.
=> Fix renewal with insufficient allowance

.changeset/add_hardening_against_writing_incomplete_partial_slab_data.md, internal/download/downloadmanager.go
This PR is related to https://github.com/SiaFoundation/renterd/issues/1889. I can't reproduce it by uploading files myself, but I can reproduce the exact issue by writing an empty slice in place of partial slab data. Note that this won't fail the download, but merely add a log entry to indicate it is in fact a slab without shards.
=> Add hardening to writing partial slab data on download

.changeset/perform_sector_write_and_append_with_single_siamux_transport.md, internal/hosts/manager.go, internal/rhp/v4/rhp.go
Since we are always writing a sector and then appending it makes sense to avoid establishing a siamux connection twice in a row by combining the RPCs. 
If we end up refactoring `renterd` to separately write sectors and append we can split it up again but that probably won't happen soon.
=> Write and append sector with single Siamux transport

.github/workflows/openapi-publish.yml, .github/workflows/openapi-sync.yml
- Workflow for publishing the openapi spec when the file changes on master or via manual trigger.
- Note: this step will throw an error until tomorrow. I reported an issue with this API to the scalar team and they said it would be fixed in the next release (1-2 days).
- Workflow for syncing the openapi spec version field to the repo latest release version. When the versions are out of sync this workflow will open a PR.
- Depends on https://github.com/SiaFoundation/workflows/pull/17 being merged.
=> ci: publish openapi to scalar, sync version

.github/workflows/openapi-sync.yml
=> ci: fix openapi spec sync workflow path

.changeset/reset_chain_state_if_consensusdb_was_deleted.md, internal/bus/chainsubscriber.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, internal/test/e2e/host.go
Some users are reporting that `renterd` seems stuck on the v2 allow height and that it is not properly resetting the chain state, even after deleting the `consensus.db`. That's definitely a regression and it was introduced [here](https://github.com/SiaFoundation/renterd/pull/1655). I believe we added that condition to speed up the test (TestConsensusResync), or maybe because it felt logical at the time.
=> Reset chain state
