internal/stores/objects_test.go
Adds missing test for #6 
https://github.com/SiaFoundation/renterd/pull/6#issuecomment-1290755182
=> stores: add object store test

internal/stores/contracts.go, internal/stores/hostdb.go, internal/stores/wallet.go, rhp/v3/transport.go
Fixed a couple of missing error checks in the rhpv3 transport code and stores.
=> Fix: if-else chain error checks

autopilot/autopilot.go, autopilot/contractor.go, bus/api.go, bus/bus.go, bus/client.go, internal/stores/contracts.go, internal/stores/contracts_test.go, internal/stores/objects_test.go
Have add/renew contract return the contract it just inserted.  
It saves a round trip to the bus when the autopilot forms and renews contracts.
=> Return added/renewed contract

worker/api.go, worker/client.go, worker/worker.go
`/rhp/prepare/form` and  `/rhp/prepare/renew` go through the `bus` now
=> Remove Worker Routes

bus/api.go, bus/client.go, internal/testing/cluster.go, internal/testing/cluster_test.go, worker/worker.go
This PR adds an integration test that asserts object uploads/downloads work.
=> Upload Download Object

autopilot/api.go, internal/stores/hostdb.go
Just a few smaller things I noticed while going through the API
=> Small refactor

internal/node/node.go
Now that we moved to a sql database a lot of the folders aren't used. This PR cleans up the directory structure a bit and gets rid of those unused folders.
=> Cleanup Directory Structure

api/bus.go, autopilot/hostfilter.go, bus/bus.go, cmd/renterd/main.go, internal/stores/hostdb_test.go, internal/testing/cluster_test.go, worker/gouging.go, worker/worker.go
Small PR to allow overriding the redundancy settings on a per-file basis.
=> Redundancy Override

.github/workflows/test.yml
Add https://github.com/siafoundation/action-golang-analysis to the Github Actions workflow to get annotations from `jape.Analyzer` instead of running commands in a shell.
=> Add Analyzer

autopilot/autopilot.go, autopilot/contractor.go, bus/bus.go, bus/client.go
This PR adds wallet maintenance to the contractor, redistributing the wallet balance into `numHosts` outputs to ensure the autopilot can smoothly form and renew contracts.
=> Wallet Maintenance

autopilot/autopilot.go, autopilot/contractor.go, autopilot/ipfilter.go, autopilot/migrator.go, internal/node/node.go, worker/client.go
just some logging - no real changes
=> Autopilot Logging

autopilot/contractor.go, internal/stores/contracts.go, internal/stores/objects.go, internal/stores/sql.go
This PR originally was meant to get rid of all `gob` types but we're already tackling that in #117 - my PR had some small changes/fixes I wanted to take along with me so I've extracted them in a separate PR here.
=> DB Updates/Fixes

internal/stores/sql.go
=> Custom Logger

worker/transfer.go
Adds the same tracing we already have for uploads to downloads as well.
=> Add download tracing

cmd/renterd/web.go
This PR adds `pprof` routes from the standard library which allows profiling the server
=> Runtime Profiling

go.mod, go.sum, object/slab.go
This PR is a temporary workaround for https://github.com/klauspost/reedsolomon/issues/240
=> Disable AVX2 support for reed solomon when reconstructing slabs

internal/stores/metadata.go
Database transactions which first read and then write seem to be quite likely to fail if something else updates the database in the meantime. It seems like the contract set updates are especially affected.
So considering that we don't need perfect consistency in `SetContractSet` I removed the transaction to avoid "database is locked" errors.
=> Remove transaction from SetContractSet

cmd/renterd/dist/index.html
/api/wallet/balance changed to /api/bus/wallet/balance
=> Fix issue #152

internal/stores/metadata.go, internal/stores/metadata_test.go
I noticed that my node kept migrating slabs even though no contracts were actually bad. After some digging it turns out that a renewal or refresh of a contract caused slabs to be repaired. This PR fixes that.
=> Fix slabs becoming unhealthy when contracts are renewed

autopilot/accounts.go, autopilot/contractor.go, autopilot/hostfilter.go
Reverts SiaFoundation/renterd#187
=> Revert "Consider host unusable without price table"

worker/worker.go
Now that we have a logger we should at the very least log the download errors. I also write the error to the response writer if the error occurs on the first slab... it's better than nothing I guess.
=> Worker Download Errors

internal/stores/hostdb.go
I'm testing my node with MySQL and found a bug in the blocklist. I am currently manually testing it on my node. It's a little annoying to test because in testing all of our hosts are on localhost.. so writing a decent integration test is a little annoying.
edit: confirmed working on my node:
```
SELECT COUNT(*) FROM host_blocklist_entry_hosts;
63571
```
using blocklist
```
[
"45.148.30.56",
"51.158.108.244",
"siacentral.ddnsfree.com",
"siacentral.mooo.com"
]
```
=> MySQL blocklist fix

autopilot/contractor.go, autopilot/hostfilter.go, worker/gouging.go
Slight refactor of the gouging code since the price computation was a bit off in some spots.
=> Fix upload gouging checks

bus/contractlocking.go, internal/testing/cluster_test.go, worker/transfer.go
=> OOM  debug

autopilot/hostfilter.go
Noticed a lot of "unknown" to show up on my node. This fixes that.
=> Change switch to if-else when counting unusable host reasons

worker/worker.go
figured we can delete the debug logging now that the upload issue HB was facing is resolved, quite verbose
=> Remove Logging

go.mod, go.sum
- The autopilot target price default value calculation has been corrected.
- Siacoin inputs are now easier to use, especially when entering and editing decimal values.
- The txpool and wallet transaction lists now show the specific type of transaction.
- Fixed a bug in the send siacoin transaction flow.
- Host and contract explorer view menus now allow toggling column visibility by group.
- The host explorer view menu now allows toggling column visibility by group.
- Autopilot estimates are now accurately labeled with TiB units.
- renterd now has proper page titles.
- The host menu now provides an option to trigger a manual rescan.
- Autopilot and config features now show any input errors.
- Host and contract tables now show 50 items per page.
- The renterd sidenav no longer flickers when …
=> ui: v0.10.0

worker/worker.go
Content type is derived from the extension and if that doesn't work then from the first bytes of the download.
Closes https://github.com/SiaFoundation/renterd/issues/277
=> Set content-type header when serving objects

api/autopilot.go, autopilot/contractor.go, autopilot/hostfilter.go, internal/stores/hostdb.go, worker/gouging.go, worker/worker.go
This PR bundles some fixes for bugs I found preparing the workshop:
- fix pricetable overwrite
- fix gouging checks error
- fix worker error output
- rename `notscanned` to `notcompletedscan`
=> Various Fixes

go.mod, go.sum
- The files explorer now shows the total size of directories.
- The files feature now supports UTF-8 directory and file names.
- The file menu now provides "Copy URL", and "Copy authenticated URL" functions.
- The files copy metadata option is now disabled in the data is unavailable or fetching.
- The wallet sparklines have been temporarily hidden until we have support for all inflow/outflow events such as returned allowance.
=> ui: v0.13.0

go.mod, go.sum, internal/testing/host.go
Decided to open a separate PR for this since it requires adding a new host setting.
=> Upgrade hostd dependency

go.mod, go.sum
- The files stats bar now displays the total number and size of files.
- The AppNavbar now has two levels, one for global controls and one for filters and stats.
- The autopilot configuration now includes host settings for "redundant IPs" and "max downtime", and a wallet setting for "defrag threshold".
- The hosts explorer table now shows that price table columns are associated with RHPv3 and host settings RHPv2.
- All data values are now TBs rather than TiBs.
- The hosts explorer now explains that autopilot must be configured before using the hosts explorer.
- Corrected a styling issue for custom toast notification such as in the copy authenticated URL files feature.
- Transaction types are properly displayed again.
- The autopilot configuration now shows a monthly spending estimate for …
=> ui: v0.14.0

autopilot/contractor.go, autopilot/hostfilter.go
This PR fixes the issue observed in #343 where contracts won't expire past their expiration height.
=> Fix contracts not expiring for unusable hosts

stores/metadata.go, stores/metadata_test.go
This PR adds a `rawObject` and updates the metadata store to fetch the object using a raw query rather than preloading the sectors using gorm.
fixes #327
=> Raw Object Query

stores/metadata.go, stores/metadata_test.go, stores/migrations.go, stores/sql.go
Cleanup PR that removes an unused join table.
=> Remove unused host_sectors table

bus/bus.go, go.mod, go.sum, internal/testing/cluster_test.go, internal/testing/gouging_test.go, internal/testing/host.go, worker/rhpv3.go
Fixes failing syncs in case the account is completely drained.
=> Sync account balances with contract

.github/workflows/publish - zen.yml, .github/workflows/publish.yml
This fixes the failing workflows.
=> Fix publish workflow

wallet/wallet.go
Adds some context to errors returning `ErrInsufficientBalance` in the wallet to give some insights on why things fail when the reported balance is seemingly enough.
=> Improve wallet errors in case of insufficient balance

autopilot/accounts.go, autopilot/contractor.go, worker/rhpv3.go
Otherwise we get stuck on contracts that have been renewed already since we need to increment their revision to pay but we can't.
=> Don't pay for pricetable with contract in fetchRevisionWithAccount

autopilot/hostscore.go
=> Remove rhpv2 price scoring

bus/bus.go, bus/client.go, internal/testing/cluster_test.go, stores/metadata.go, worker/worker.go
Allows for deleting a folder of objects at once
=> Add batch deletion support

go.mod, go.sum
- The contracts table now includes a data size column.
- Fixed an issue where opening the file search feature would crash the UI.
=> ui: v0.20.0

worker/gouging.go
Download gouging doesn't need to take redundancy into account since downloads don't have any redundancy overhead. e.g. downloading a 40MiB slab only downloads 40MiB and not 120MiB at a 3x redundancy even though the size on the network is 120MiB
=> Remove redundancy from download gouging

worker/interactions.go, worker/rhpv3.go, worker/upload.go, worker/worker.go
running into the ea withdraw timeout again
=> Fix Revision Timeout

stores/hostdb.go
Seems like due to a mismatch between unix timestamps and time.Duration we ended up with some math that is not quite correct. This PR should fix that.
=> Fix uptime/downtime math

api/bus.go, autopilot/contractor.go, bus/bus.go, bus/client.go, cmd/renterd/main.go, go.mod, go.sum, internal/testing/host.go, stores/hostdb.go, stores/sql.go, worker/rhpv3.go, worker/worker.go
A small selection of tweaks / fixes.
=> Minor tweaks

wallet/wallet.go
Closes https://github.com/SiaFoundation/renterd/issues/470
=> More details in insufficient balance error

internal/testing/cluster_test.go
Comparing against an exact balance and drift is a bit too fragile. So we check that the values were initialised.
=> Fix NDF in TestEphemeralAccounts

go.mod, go.sum
- Fixed an issue with the allowlist, removing public keys now works as expected.
- The wallet now sends the correct amount when fee is included in amount.
- Fixed a cursor position issue with Text and TextArea form fields.
=> ui: v0.22.0

cmd/renterd/main.go
Closes https://github.com/SiaFoundation/renterd/issues/497
=> Add '--log-path' flag to CLI

worker/download.go
Closes https://github.com/SiaFoundation/renterd/issues/505
=> Fix division by zero panic in downloadSpeed

go.mod, go.sum
- Currency options now include AUD.
- Contract timeline now always shows contract duration dates, on user interaction the specific labels will activate.
- Max storage and upload price settings now have an "including redundancy" option.
- The Settings dialog is now called App preferences.
- The default contract set description was updated to be more accurate - it does not apply to default migrations.
- The app now includes an auto-lock feature that can be enabled or disabled from the App Preferences menu. The locking inactivity period can also be configured.
- Contract timeline dates are now localized.
- Paginators now properly show loading state when fetching a new page or previous results when revalidating a cached page.
- Inactive sortable table columns now show a subtle caret to …
=> ui: v0.24.0

go.mod, go.sum
- The host explorer now works before autopilot is configured, the table shows the autopilot columns with empty values and tooltips explaining that autopilot is not configured.
- Upload packing can now be enabled from the configuration tab.
- The file stats do not show redundancy factor or health until there is at least 1 byte of data.
- Fixed a crash issue when loading the hosts explorer.
- Wallet balance is now more accurately calculated as spendable + unconfirmed.
- Contracts can now be deleted from the contract context menu.
- The files health feature has been refined to be more accurate and clear and now includes a global health value in the stats bar.
- Host explorer empty states are now more clear.
- Hosts can now be filtered by public key.
- Table headers now freeze in view when …
=> ui: v0.26.0

internal/testing/cluster_test.go, stores/metadata.go
This PR extends some tests in order to figure out what's causing https://github.com/SiaFoundation/renterd/issues/544
Also closes https://github.com/SiaFoundation/renterd/issues/547
=> Extend testing around file size for objects waiting to be packed

internal/testing/cluster_test.go
avoid underflow panic and fatal instead
=> Fix underflow panic

autopilot/autopilot.go
When the ticker fired while blocking we skipped an iteration of the maintenance.
=> Fix edge case when autopilot ticker fires while blocking mid-maintenance

build/env_default.go, build/env_testnet.go, build/network.go
Readds support for testnet builds
=> Fix testnet support

stores/metadata.go
this PR changes the query for the contract size query going from 
```sql
CO-ROUTINE 1
SCAN TABLE contracts AS c USING INDEX idx_contracts_fc_id
SEARCH TABLE contract_sectors AS cs USING AUTOMATIC COVERING INDEX (db_contract_id=?)
SCAN SUBQUERY 1 AS i
```
to 
```sql
SCAN TABLE contracts AS c USING INDEX idx_contracts_fc_id
SEARCH TABLE contract_sectors AS cs USING AUTOMATIC COVERING INDEX (db_contract_id=?)
```
I don't think it'll make _that_ much of a difference but I spotted some SLOW SQL logs so hopefully those go away with this change.
=> Optimise query for ContractSizes

api/bus.go, bus/bus.go, bus/client.go, internal/testing/cluster.go, object/object.go, object/slab.go, stores/metadata.go, stores/metadata_test.go, stores/sql.go, worker/download.go, worker/upload.go, worker/worker.go
This is an alternative implementation of https://github.com/SiaFoundation/renterd/pull/562
=> Add dedicated routes for storing/fetching partial uploads in/from bus

stores/metadata.go
We weren't properly refreshing the health of slabs. I included `health_valid` in the unhealthy slabs query and set `health` to 1 when we update the slab
=> Health Fixes

worker/upload.go
I noticed an upload being stalled after not having enough candidate workers to finish the upload. Stack trace indicates `uploadSlab` can't send a response down the response channel, causing the waitgroup to wait indefinitely and never fail the upload. I think it's easiest to get rid of the waitgroup all together and use a mutex to wait for all responses and go ahead and close the channel.
=> Fix Stalled Upload 

go.mod, go.sum
- Alerts now display a context menu for contract ID values.
- Alerts can now be dismissed, all or one by one.
- The GPU setting now displays the correct device support text.
=> ui: v0.28.0

.github/workflows/publish.yml
Signs Windows releases to satisfy Windows smart screen.
=> Sign windows releases

stores/metadata.go, stores/multipart_test.go, stores/slabbuffer.go, worker/download.go
Fixes a bug where downloads for objects that were uploaded using the S3 multipart upload failed.
=> Fix downloads failing after multipart upload

cmd/renterd/main.go
disable auth flag is not being respected in all cases
=> S3 Disable Auth

cmd/renterd/main.go, config/config.go, s3/s3.go
=> S3: host bucket enabled

go.mod, go.sum
- Initiated an already active upload or download now shows an error.
- Alerts can now be filtered and dismissed by type.
- The not enough active contracts warning no longer flickers.
- The files feature now supports buckets.
- File uploads and downloads can now be canceled from the transfers bar.
- The alert dialog now has a fixed height, so it stays in the same position when an alert is dismissed.
- Fixed an issue with file transfer progress reporting.
- Fixed an issue with the alert dismiss button overflowing.
=> ui: v0.29.0

stores/metadata.go
This is a f/u to the previous PR which improved the performance of `ObjectStats`.
On Arequipa the query for fetching all uploaded sectors still took 13s. This PR changes the total time it takes to about 14s but it does so in individual batches which take about 5s each for 10 million rows.
That should give other queries a window to be executed in between batches and reduce locking errors on large nodes running SQLite.
=> Reduce lock duration on ObjectsStats

autopilot/accounts.go
Changes the refill code to register/log errors related to reaching the max allowed drift
=> Log and register alerts for hosts that have reached the max account drift even if they are not in the set

internal/testing/blocklist_test.go, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/gouging_test.go, internal/testing/migrations_test.go, internal/testing/pruning_test.go, internal/testing/s3_test.go, internal/testing/uploads_test.go, worker/upload.go
This PR refactors the test suite a bit to reduce some of the bloat and redundant code.
There is probably more that can be done such as adding more assertion function but I think it's a good start.
=> Refactor test suite

stores/multipart.go, stores/multipart_test.go
For uploads with many slab slices completing the upload might fail. This PR fixes this by adding the slices in batches.
=> Fix `err: failed to save slices: Error 1390 (HY000): Prepared statement contains too many placeholders`

worker/serve.go
Prevents calling `Seek` after the first call to `Read` by `http.ServeContent`. This doesn't fix any immediate issue atm. but might be useful in the future.
=> Add Seek safeguard to  contentReader

api/bus.go, bus/client/objects.go, internal/testing/s3_test.go, worker/client.go
Closes https://github.com/SiaFoundation/renterd/issues/659
Also manually verified using an rclone mount
=> Fix URL path escaping for objects with special chars in their path

stores/autopilot_test.go, stores/hostdb_test.go, stores/metadata_test.go, stores/metrics_test.go, stores/multipart_test.go, stores/settingsdb_test.go, stores/sql_test.go, stores/webhooks_test.go
Isolates some code from the metrics PR series
=> Introduce testSQLStore

api/bus.go, internal/node/node.go, stores/metadata.go, stores/metrics.go, stores/metrics_test.go, stores/multipart.go, stores/sql.go, stores/types.go
This PR adds contract set metrics to the store and performs a refactor to simplify the creation of a store for testing.
It is supposed to be merged into the main metrics PR and not directly into master.
=> Metrics: Contract set

go.mod, go.sum
- Configuration values such as download and upload utilization are now per month instead of period.
- The configuration now has an advanced mode that allows the user to view and change all settings.
- The configuration is now much simpler by default, only requiring storage amount and price to be set during onboarding.
- Fixed an issue with the upload packing switch and updated the explanation.
- Fixed an issue where file and directory names could not contain the # symbol.
- The configuration page now shows the changed status on fields if the user has made a change but the server values were since updated.
- The default simple configuration automatically sets any unset advanced options to typical defaults. Settings with existing values are not changed.
- Fixed an issue where fiat input …
=> ui: v0.30.0

go.mod, go.sum
- Alerts are now more concise and show an actionable hint when available.
- Fixed an issue where the allowance does not get set the first time saving settings in simple mode.
=> ui: v0.31.0

api/bus.go, stores/metrics.go, stores/metrics_test.go
Depends on https://github.com/SiaFoundation/renterd/pull/675
=> Metrics: Performance metrics

README.md
Update the docker build command by specifying the `Dockerfile` path
=> Update docker build command

api/bus.go, stores/metadata.go, stores/metrics.go, stores/metrics_test.go, stores/types.go
Depends on https://github.com/SiaFoundation/renterd/pull/676
=> Metrics: Contract metrics

api/bus.go, autopilot/autopilot.go, autopilot/contractor.go, bus/bus.go, bus/client/metrics.go, internal/node/node.go, internal/testing/cluster_test.go, stores/metrics.go, stores/metrics_test.go, stores/types.go
Adds contract set churn metrics and contract set metrics to API and adds testing to verify that bus and autopilot are recording them.
=> Metrics: Record contract set churn metrics and contract set metrics

build/env_default.go, cmd/renterd/main.go
=> Lower MaxContractPrice to 1SC by default and raise revision broadcast interval to 1 week

autopilot/alerts.go, autopilot/contractor.go, bus/bus.go, bus/client/hosts.go, hostdb/hostdb.go, stores/hostdb.go, stores/metadata.go, stores/metadata_test.go, stores/migrations.go
This will later be integrated into the scoring code
=> Add a counter for sectors reported as not found by hosts to host db

autopilot/scanner.go
Closes https://github.com/SiaFoundation/renterd/issues/744
=> Fetch host settings after scanning and before pruning hosts to apply most recent settings

api/object.go, bus/bus.go, bus/client/objects.go, internal/testing/cluster_test.go, stores/metadata.go, stores/metadata_test.go, stores/sql.go
'force' allows for a rename operation to overwrite the destination object
Closes https://github.com/SiaFoundation/renterd/issues/754
=> Add force parameter to object renaming endpoint

autopilot/alerts.go, autopilot/migrator.go, internal/testing/pruning_test.go, stats/stats.go, worker/download.go, worker/upload.go
This PR adds a rough estimate to the ongoing migrations alert. On arequipa it indicates it'll take about 2 months to migrate the remaining 1M slabs, which is probably not too far from the truth. It's a rough estimate but useful enough to add it imo.
=> Migration Estimates

cmd/renterd/main.go
Closes https://github.com/SiaFoundation/renterd/issues/648
=> Deprecate CLI Flags

stores/migrations.go, stores/wallet.go
```sql
SELECT * FROM transactions WHERE timestamp >= 0 AND timestamp < 9223372036854775807 ORDER BY timestamp DESC LIMIT 9223372036854775807 OFFSET 0
```
=> Transactions Timestamp Index

autopilot/autopilot.go
This wasn't worth it and it causes weird behaviour on the hosts page when the wallet isn't funded.
=> Remove blockUntilFunded

cmd/renterd/main.go
Closes https://github.com/SiaFoundation/renterd/issues/798
=> Fall back to 127.0.0.1 if localhost doesn't work

worker/download.go, worker/host_test.go, worker/mocks_test.go, worker/upload.go, worker/upload_test.go, worker/uploader.go, worker/worker.go
This PR adds the notion of contracts to the mocks and accomplishes a rudimentary upload/download flow using the actual managers. I already had this more or less this morning, so that's why I kind of skip `UploadShards` which would be a more logical next step I guess. I'll add that next.
=> Contract Mock

go.mod, go.sum
- The wallet balance shown on the wallet page is now spendable plus unconfirmed.
- The contract funding and spending graph now shows a data point for brand new contracts.
- The default suggested pricing for new users is now based on Sia Central averages.
- Fixed an issue where currency was displayed with too many decimals.
=> ui: v0.37.0

stores/migrations.go, stores/migrations_metrics.go
=> Add no-op migration in preparation of dropping previous migrations

go.mod, go.sum
- The contracts table now has a contract sets column that shows all the sets each contract is in.
- The reported average redundancy factor now takes into account multipart uploads.
=> ui: v0.39.0

go.mod, go.sum
- Remove the wallet defrag threshold setting.
=> ui: v0.40.0

api/object.go, internal/testing/cluster_test.go, stores/metadata.go, stores/metadata_test.go, worker/client/client.go, worker/worker.go
Related to https://github.com/SiaFoundation/renterd/issues/860
=> Allow for sorting objects by size

api/object.go, autopilot/migrator.go, bus/bus.go
Closes https://github.com/SiaFoundation/renterd/issues/887
=> Don't register alert when slab for migration wasn't found

worker/serve.go, worker/upload.go, worker/upload_test.go
Hotfix for two deadlocks on `master`
=> Cherry-pick fixes for upload deadlock

cmd/renterd/config.go, cmd/renterd/main.go, config/config.go
Adds `renterd config` to prompt the user and generate a YAML config file
=> Add config command

internal/testing/cluster.go, internal/testing/cluster_test.go
I believe this PR fixes the `TestNewTestCluster` NDF. I did not bother to reproduce the NDF on the CI and then retry after the fix, I did reproduce it locally with logging and found it's a simple race condition between forming contracts and adding them to the set. This helper essentially adds a retry loop to the assertion and might prove handy in the future.
=> fix TestNewTestCluster NDF

.github/workflows/test.yml, internal/testing/cluster.go, internal/testing/cluster_test.go, internal/testing/pruning_test.go
passed 600 times now so should be fine
=> fix TestSectorPruning NDF

api/metrics.go, autopilot/contract_pruning.go, stores/metrics.go, stores/metrics_test.go
noticed a small inconsistency in our metric types
=> use TimeRFC3339 for PruneMetric Timestamp

stores/metadata_test.go
Additional test for the metadata store that focuses on slabs getting reused for multiple objects.
=> TestUpdateObjectReuseSlab

worker/host.go, worker/interactions.go, worker/worker.go
This PR cherry-picks a fix or a panic onto master
=> Fix interaction recorder panic

autopilot/alerts.go, autopilot/contractor.go
Related to https://github.com/SiaFoundation/web/pull/486
=> Dismiss lost sector alerts when there are no lost sectors

stores/migrations.go, stores/migrations/mysql/main/migration_00003_idx_objects_size.sql, stores/migrations/mysql/main/schema.sql, stores/migrations/sqlite/main/migration_00003_idx_objects_size.sql, stores/migrations/sqlite/main/schema.sql, stores/migrations_metrics.go
The "size" on the objects table is missing an index which slows down certain operations tremendously
=> Add database index for size column in objects database

autopilot/churn.go
@alexfreska this will affect the UI too
=> Fix JSON key casing

.github/workflows/ui.yml
- This workflow is having version issues on walletd, syncing all of them to match @n8maninger's update: https://github.com/SiaFoundation/hostd/commit/44bffaf6464b94bfd3005402192e7cf673672e68
=> ci: fix ui workflow

stores/multipart.go, stores/multipart_test.go
The `MultipartUploads` method didn't correctly apply the markers in the SQL query.
=> Fix broken pagination when listing multipart uploads

api/autopilot.go, autopilot/autopilot.go, autopilot/autopilot_test.go, autopilot/client.go, autopilot/contractor.go, autopilot/hostfilter.go, autopilot/hostscore.go, internal/test/e2e/gouging_test.go
This can be integrated into the UI to sanity check settings before applying them and giving users some feedback on what setting might prevent most hosts from seeming valid for contract formation.
=> A endpoint for evaluating autopilot configuration

api/object.go, internal/test/e2e/metadata_test.go, worker/client/client.go, worker/serve.go, worker/worker.go
closes #1010 
**reminders**: 
- update postman docs
- create jape issue to support `HEAD` in client (?)
=> add HEAD object endpoint to worker API

stores/migrations.go, stores/migrations/mysql/main/migration_00006_idx_objects_created_at.sql, stores/migrations/mysql/main/schema.sql, stores/migrations/sqlite/main/migration_00006_idx_objects_created_at.sql, stores/migrations/sqlite/main/schema.sql
We perform a `MAX(objects.created_at)` on that column.
=> Create index on created_at column of objects table

stores/metadata.go
Closes https://github.com/SiaFoundation/renterd/issues/1061
This hint speeds up the query on my node of 500k objects quite a bit. From about 1s down to ~350ms.
=> Add index hint to ObjectEntries

stores/settingsdb.go, stores/types.go, stores/types_test.go
Closes https://github.com/SiaFoundation/renterd/issues/1065
=> Add custom `setting` type to redact settings containing s3 keypairs from logs

autopilot/contractor.go, autopilot/contractor_test.go, autopilot/hostfilter.go
Addresses one of the two tasks in https://github.com/SiaFoundation/renterd/issues/1096
=> Be more forgiving with contracts that fail to refresh by giving them a grace period

worker/upload.go
When mounting a folder with rclone it seems like `upload` frequently fails because the worker can't fetch the packed slabs for upload. Considering that the upload has already succeeded at that point in time we should probably log the error and return a success code.
=> Don't fail upload when failing to fetch packed slab from bus

worker/upload_test.go
Fixes https://github.com/SiaFoundation/renterd/issues/1200
=> Fix TestRefreshUploaders NDF

worker/host.go, worker/upload.go, worker/uploader.go, worker/uploader_test.go
Testing the migration on my node I found that we have to tweak the upload penalty in some cases.
=> Improve sector upload penalty

.github/workflows/publish.yml, autopilot/contractor/contractor.go, autopilot/contractor/hostfilter.go, autopilot/contractor/hostfilter_test.go, internal/node/transactionpool.go, stores/metadata.go, stores/metadata_test.go, worker/gouging.go
This PR cherry-picks the changes to the `publish.yml` workflow that Nate made from `dev` into `master`.
=> Update GitHub actions

stores/multipart_test.go, stores/sql/main.go
Closes https://github.com/SiaFoundation/renterd/issues/1285
=> Fix multipart upload returning ErrObjectNotFound

stores/metadata_test.go, stores/sql/main.go
Seems like our unit test was missing a case
=> Fix DeleteHostSector NULL constraint

stores/sql/types.go
Not really a fix but better safe than sorry
=> Make sure types implement Scanner and Valuer

stores/metadata.go, stores/metadata_test.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
Added a few more migrations since they are rather small.
=> Migrate AncestorContracts to raw SQL

bus/bus.go, cmd/renterd/main.go, internal/bus/alerts.go, internal/bus/pinmanager.go, internal/bus/pinmanager_test.go, internal/node/node.go, internal/test/e2e/cluster.go
=> Ensure temporary downtime of forex API does not prevent startup

bus/bus.go, bus/client/settings.go, internal/test/e2e/cluster_test.go
Related to https://github.com/SiaFoundation/web/pull/671#discussion_r1709892110
=> Populate the price pinning settings returned from the bus with defaults for all autopilots

internal/test/host_test.go
no real changes, we forgot to move this file
=> Move TestHost

internal/test/e2e/contracts_test.go
Race condition between renewals and updating contract set.
=> Fix TestFormContract NDF

cmd/renterd/node.go
Closes https://github.com/SiaFoundation/renterd/issues/956
=> Add check to make sure metrics and main db are not the same

worker/alerts.go, worker/alerts_test.go
Closes https://github.com/SiaFoundation/renterd/issues/1211
=> Handle HostErrorSet in newUploadFailedAlert

api/bus.go, api/events.go, autopilot/autopilot.go, autopilot/contractor/contractor.go, bus/bus.go, bus/client/contracts.go, bus/routes.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, internal/test/e2e/events_test.go, stores/metadata.go, stores/metadata_test.go, stores/sql/database.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go, stores/sql_test.go
Closes https://github.com/SiaFoundation/renterd/issues/1497
=> Update SetContractSet to UpdateContractSet

bus/client/client.go, bus/client/metrics.go, bus/client/slabs.go, internal/bus/forex.go, internal/utils/web.go, internal/worker/events_test.go, webhooks/webhooks.go, worker/client/client.go
Small util to unify response handling. I was on the fence on whether to keep behaviour consistent (in some places, like webhooks and events), but ultimately decided to handle all requests the same.
=> Add util to send http request

internal/sql/migrations.go
we missed it in https://github.com/SiaFoundation/renterd/pull/1491
=> Fix missing metrics migration

api/bucket.go, api/worker.go, bus/routes.go, internal/test/e2e/cluster.go, internal/test/e2e/cluster_test.go, internal/test/e2e/gouging_test.go, internal/test/e2e/metadata_test.go, internal/test/e2e/metrics_test.go, internal/test/e2e/migrations_test.go, internal/test/e2e/pruning_test.go, internal/test/e2e/s3_test.go, internal/test/e2e/uploads_test.go, stores/metadata_test.go, stores/multipart_test.go, stores/sql/mysql/migrations/main/schema.sql, stores/sql/sqlite/migrations/main/schema.sql, stores/sql_test.go, worker/worker.go
Closes https://github.com/SiaFoundation/renterd/issues/1540
=> Remove default bucket

stores/chain_test.go, stores/sql/sqlite/chain.go
=> Fix sqlite revert update failing

stores/chain_test.go, stores/sql/chain.go, stores/sql/mysql/chain.go, stores/sql/sqlite/chain.go
Fixes #https://github.com/SiaFoundation/renterd/issues/1557
=> Extend TestProcessChainUpdate

.github/workflows/publish.yml, .github/workflows/test.yml
Should help with rate limit issues for tests and builds relying on DockerHub.
=> Login to docker hub

cmd/renterd/config.go, cmd/renterd/logger.go
Closes https://github.com/SiaFoundation/renterd/issues/1576
=> Default logging to human readable

api/object.go, bus/client/contracts.go, bus/client/metrics.go, bus/client/slabs.go, bus/routes.go, internal/test/e2e/cluster_test.go, worker/worker.go
Related to https://github.com/SiaFoundation/renterd/issues/1498
=> Ensure consistent usage of query string parameters

cmd/renterd/commands.go, cmd/renterd/config.go, cmd/renterd/main.go
Fix https://github.com/SiaFoundation/renterd/issues/1600
=> Write startup errors to stderr

cmd/renterd/config.go
Fix https://github.com/SiaFoundation/renterd/issues/1612
=> Add extra prompt to enable/disable s3 gateway if user declines configuring it

internal/sql/migrations.go, internal/test/e2e/cluster_test.go, stores/bench_test.go, stores/metadata.go, stores/metadata_test.go, stores/sql/database.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/mysql/migrations/main/migration_00020_remove_directories.sql, stores/sql/mysql/migrations/main/schema.sql, stores/sql/sqlite/main.go, stores/sql/sqlite/migrations/main/migration_00020_remove_directories.sql, stores/sql/sqlite/migrations/main/schema.sql
This PR merges the removal of directories into `master`. Please review carefully because merging it wasn't straightforward because `master` is quite far behind `dev` at this point. ~~I'm still in the process of (re)testing the migrations.~~
edit: tested the migration on both SQLite and MySQL
=> Remove `directories` table

.changeset/remove_partial_setting_updates.md, bus/bus.go, bus/client/settings.go, bus/routes.go, internal/test/e2e/settings_test.go, stores/settings.go
This PR disallows partially updating settings in the `bus`.
=> Remove partial setting updates

api/host.go, autopilot/contractor/contractor.go, autopilot/contractor/hostfilter.go, bus/bus.go, bus/routes.go, internal/gouging/gouging.go, internal/rhp/v3/rhp.go, internal/rhp/v3/rpc.go, internal/rhp/v3/rpc_test.go, internal/rhp/v4/rhp.go, internal/rhp/v4/transport.go, internal/test/e2e/host.go, internal/utils/errors.go, internal/worker/accounts.go, internal/worker/accounts_test.go, stores/sql/main.go, worker/downloader.go, worker/worker.go
Closes https://github.com/SiaFoundation/renterd/issues/1547
=> Implement RHP4 contract renewal and account funding

.changeset/fix_testblocklist.md, internal/test/e2e/blocklist_test.go, internal/test/e2e/host.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
Fix https://github.com/SiaFoundation/renterd/issues/1697
=> Fix TestBlocklist

autopilot/client.go, autopilot/contractor/contractor.go, bus/client/objects.go
fix some function names in comment
=> chore: fix some function names in comment

.changeset/fix_migration_00030_host_sectors.md, stores/sql/mysql/migrations/main/migration_00030_host_sectors.sql, stores/sql/sqlite/migrations/main/migration_00030_host_sectors.sql
DB shouldn't have these tables but seems like I forgot to add `DROP TABLE IF EXISTS` statements.
=> Update migration 00030_host_sectors 

.changeset/fix_ndf_in_testusablehosts.md, stores/hostdb_test.go, stores/sql/main.go
This PR fixes an NDF in `TestUsableHosts` on windows. I think we can theoretically remove `price_table_expiry`.. it was overlooked when we changed the price table behaviour. I figured it wasn't really worth it though at this point because of ongoing developments. Ran this in a loop on the CI and it passed the entire matrix 1000 times.
=> Fix TestUsableHosts NDF

.changeset/fix_syntax_error_in_migration_34.md, stores/sql/mysql/migrations/main/migration_00034_v2.sql, stores/sql/sqlite/migrations/main/migration_00034_v2.sql
Seems like my editor's auto format snuck in a space which breaks the query
=> Remove space after SUBSTR

.changeset/allow_for_bypassing_basic_auth_using_a_renterd_auth_cookie.md, cmd/renterd/node.go, internal/test/e2e/cluster.go, internal/utils/web.go, internal/utils/web_test.go, openapi.yml
Related to https://github.com/SiaFoundation/renterd/issues/1108
=> Allow API authentication via cookie

api/auth.go, api/auth_test.go, api/mux.go, bus/routes.go, cmd/renterd/node.go, internal/test/e2e/cluster.go, internal/utils/web.go
If only we had an `api` package 🤔
=> refactor: Move api auth out of internal

.changeset/ensure_we_set_created_at_on_all_entities_that_have_the_column.md, stores/bench_test.go, stores/sql/main.go, stores/sql/mysql/main.go, stores/sql/sqlite/main.go
I ran into it on the blocklist entries and figured we should fix it. I purposefully left out the migration... figured just fixing it is enough in this case at this particular time.
=> Fix missing created_at values

.changeset/update_api_docs.md, openapi.yml
Made some small improvements to our API docs.
=> Update API docs

.changeset/added_automatic_migration_for_v2_commitments.md, cmd/renterd/node.go
Adds a check when creating the consensus to trigger a resync if the commitment does not match.
=> Migrate v2 commitments

.changeset/fix_address_filter_not_working_on_v2_hosts.md, stores/hostdb_test.go, stores/sql/main.go
Fixes https://github.com/SiaFoundation/renterd/issues/1906
=> fix host filter not working for v2 hosts

.changeset/renamed_blockchaindb_to_consensusdb_and_moved_it_out_of_the_consensus_subdirectory.md, autopilot/pruner/pruning.go, cmd/renterd/node.go
The different name has caused confusion on multiple occasions. This PR fixes that.
=> Rename `blockchain.db` to `consensus.db` for more consistency across daemons

.changeset/added_get_pinnedkey_to_retrieve_the_raw_object_metadata_suitable_for_downloading_using_external_tools.md, object/encryptionkey.go, object/pinned.go, worker/client/client.go, worker/upload_test.go, worker/worker.go
Added `[GET] /pinned/*key` to retrieve the raw object metadata suitable for downloading using external tools.
=> Pinned meta

.changeset/remove_requirement_of_64_byte_alignment_for_client_side_encryption.md, object/encryptionkey.go, object/object_test.go
Changes from indexd
Expand existing `TestEncryptionOffset`
=> Remove requirement of 64 byte alignment for client side encryption
